export type PortalDemo = {
  href: string;
  module: string;
  id: string;
  title: string;
  status: string;
  summary: string;
  fields: Array<[string, string]>;
  flow: string[];
};

// These fixtures never enter operational repositories, RPCs, or reports.
export const portalDemos: PortalDemo[] = [
  { href: "/portal", module: "Beranda", id: "DEMO-HOME-001", title: "Ringkasan persiapan sosialisasi interaksi", status: "Menunggu review", summary: "Contoh ringkasan yang menghubungkan pekerjaan, rapat, dan materi edukasi dalam satu kegiatan.", fields: [["Prioritas", "Review materi sosialisasi"], ["Pekerjaan terkait", "DEMO-TASK-001"], ["Rapat terkait", "DEMO-MEET-001"]], flow: ["Pengurus mengerjakan tugas", "Reviewer memeriksa hasil", "Ringkasan portal mengikuti status pekerjaan"] },
  { href: "/portal/profil", module: "Profil saya", id: "DEMO-PROFILE-001", title: "Pengurus Contoh — Pencegahan & Edukasi", status: "Contoh profil", summary: "Identitas fiktif untuk memperlihatkan informasi profil dan penugasan. Tidak ada akun login yang dibuat.", fields: [["Nama", "Pengurus Contoh"], ["Email", "pengurus@example.invalid"], ["Penugasan", "Anggota Prevention and Education Division"], ["Periode", "Periode demonstrasi"]], flow: ["Identitas diverifikasi", "Pengelola mencatat penugasan resmi", "Pengurus memeriksa profilnya"] },
  { href: "/portal/workspace", module: "Ruang kerja", id: "DEMO-WORK-001", title: "Persiapan sosialisasi etika interaksi", status: "Dalam pengerjaan", summary: "Paket pekerjaan untuk menyiapkan materi, pembahasan, dan publikasi sosialisasi.", fields: [["Penanggung jawab", "Pengurus Contoh"], ["Divisi", "Pencegahan & Edukasi"], ["Hambatan", "Naskah menunggu pemeriksaan reviewer"], ["Hasil yang diharapkan", "Materi sosialisasi siap ditinjau"]], flow: ["Tetapkan pekerjaan", "Pantau tugas dan hambatan", "Tinjau hasil sebelum dipublikasikan"] },
  { href: "/portal/tugas", module: "Tugas", id: "DEMO-TASK-001", title: "Susun materi sosialisasi etika interaksi", status: "Dalam review", summary: "Materi membahas tanggung jawab dalam berinteraksi, etika komunikasi, dan cara menyampaikan pengaduan kepada KPI.", fields: [["Pemilik", "Pengurus Contoh"], ["Reviewer", "Reviewer Contoh, berbeda dari pembuat"], ["Target", "Draf materi untuk satu sesi sosialisasi"], ["Catatan hasil", "Naskah awal selesai; contoh situasi perlu diperiksa"]], flow: ["Tugas dibuat", "Pemilik mulai mengerjakan", "Hasil diajukan", "Reviewer menyetujui atau meminta revisi"] },
  { href: "/portal/rapat", module: "Rapat", id: "DEMO-MEET-001", title: "Rapat persiapan sosialisasi interaksi", status: "Draf agenda", summary: "Contoh rapat koordinasi untuk membahas materi dan pembagian pekerjaan kegiatan edukasi.", fields: [["Agenda", "Review materi, pembagian peran, dan kebutuhan publikasi"], ["Peserta", "Sekretaris Contoh, OIC Contoh, Pengurus Contoh"], ["Tempat", "Ruang rapat contoh"], ["Usulan keputusan", "Materi diperiksa sebelum jadwal kegiatan ditetapkan"]], flow: ["Siapkan agenda", "Catat kehadiran dan pembahasan", "Sahkan notulen dan keputusan", "Buat tugas tindak lanjut"] },
  { href: "/portal/dokumen", module: "Dokumen", id: "DEMO-DOC-001", title: "Draf materi sosialisasi etika interaksi", status: "Draf versi 1", summary: "Contoh metadata dokumen internal. Tidak ada file resmi atau tautan unduhan palsu.", fields: [["Jenis", "Materi edukasi"], ["Klasifikasi", "Internal"], ["Versi", "1.0 — contoh"], ["Pemilik", "Pencegahan & Edukasi"], ["Isi ringkas", "Etika komunikasi, kepedulian, dan prosedur pengaduan"]], flow: ["Unggah dan periksa file", "Isi metadata dan klasifikasi", "Tinjau versi", "Bagikan sesuai izin"] },
  { href: "/portal/notifikasi", module: "Kotak masuk", id: "DEMO-NOTIF-001", title: "Materi sosialisasi membutuhkan review", status: "Belum dibaca", summary: "Contoh pemberitahuan internal saat hasil tugas diajukan kepada reviewer. Tidak dikirim melalui email atau WhatsApp.", fields: [["Penerima", "Reviewer Contoh"], ["Sumber", "DEMO-TASK-001"], ["Pesan", "Periksa naskah dan berikan keputusan atau catatan revisi"], ["Kanal", "Kotak masuk internal"]], flow: ["Hasil tugas diajukan", "Notifikasi dibuat untuk reviewer", "Reviewer membuka pekerjaan terkait"] },
  { href: "/portal/kasus", module: "Kasus & pengaduan", id: "DEMO-CASE-001", title: "Permintaan pendampingan komunikasi antarpengurus", status: "Menunggu triase", summary: "Skenario sepenuhnya fiktif: seseorang meminta pendampingan karena terjadi kesalahpahaman dalam komunikasi kegiatan. Tidak memuat tuduhan atau identitas nyata.", fields: [["Pelapor", "Pelapor Contoh — identitas disamarkan"], ["Penerima awal", "Sekretaris KPI"], ["Tindak lanjut", "Intelligence and Operation Division"], ["Klasifikasi", "Rahasia"], ["Catatan awal", "Verifikasi informasi dan kebutuhan pendampingan sebelum menentukan tindak lanjut"]], flow: ["Pengaduan diterima sekretaris", "Informasi ditriase", "Personel berwenang ditugaskan", "Tindak lanjut dicatat", "Kasus ditutup sesuai keputusan berwenang"] },
  { href: "/portal/editor", module: "Redaksi", id: "DEMO-CMS-001", title: "Mengenal peran KPI dalam menjaga interaksi Masisir", status: "Draf editorial", summary: "Contoh artikel pengenalan tugas KPI dalam pengaturan interaksi, edukasi, dan penerimaan pengaduan. Belum diterbitkan ke situs publik.", fields: [["Jenis", "Artikel edukasi"], ["Bahasa", "Indonesia"], ["Penulis", "Tim Media Contoh"], ["Pembuka", "Interaksi yang tertib membutuhkan pemahaman, tanggung jawab, dan saluran penyampaian informasi yang jelas."], ["Tahap berikutnya", "Pemeriksaan isi oleh reviewer berwenang"]], flow: ["Tulis draf", "Review isi dan sumber", "Persetujuan publikasi", "Terbitkan versi yang disahkan"] },
  { href: "/portal/knowledge", module: "Rujukan", id: "DEMO-KNOW-001", title: "Panduan menyusun notulen yang dapat ditindaklanjuti", status: "Draf rujukan", summary: "Contoh pengetahuan kerja: pisahkan pembahasan, keputusan, penanggung jawab, dan tenggat agar hasil rapat dapat ditelusuri.", fields: [["Kategori", "Tata kerja organisasi"], ["Pemilik", "Sekretariat Contoh"], ["Isi", "Catat agenda, ringkasan pembahasan, keputusan, serta tugas lanjutan"], ["Sumber", "Materi demonstrasi; bukan pedoman resmi"]], flow: ["Susun rujukan", "Periksa sumber dan versi", "Sahkan untuk penggunaan internal"] },
  { href: "/portal/ai", module: "AI internal", id: "DEMO-AI-001", title: "Cerita kegiatan menjadi draf laporan", status: "Menunggu pemeriksaan manusia", summary: "Contoh hasil penyusunan, bukan respons dari provider AI yang sedang berjalan. AI tidak menyimpan atau menyetujui laporan sendiri.", fields: [["Cerita pengurus", "Kami membahas materi sosialisasi, lalu membagi pekerjaan penyusunan naskah dan poster. Naskah perlu direview sebelum kegiatan."], ["Judul hasil", "Laporan persiapan sosialisasi etika interaksi"], ["Ringkasan hasil", "Tim membahas materi dan membagi pekerjaan. Naskah serta poster disiapkan untuk pemeriksaan."], ["Usulan tindak lanjut", "Buat tugas penyusunan naskah dan review materi"], ["Data belum tersedia", "Tanggal kegiatan, peserta, dan bukti dokumentasi"]], flow: ["Pengurus bercerita", "AI menyusun usulan draf", "Pengurus memeriksa dan melengkapi", "Simpan setelah konfirmasi pengguna"] },
  { href: "/portal/keuangan", module: "Keuangan", id: "DEMO-FIN-001", title: "Usulan biaya cetak materi sosialisasi", status: "Draf pengajuan", summary: "Contoh kebutuhan cetak 20 lembar materi. Nilai hanya ilustrasi, tidak masuk saldo atau laporan keuangan resmi.", fields: [["Jenis", "Rencana pengeluaran"], ["Jumlah", "20 lembar × EGP 5 = EGP 100"], ["Kategori", "Materi edukasi"], ["Bukti", "Belum tersedia; bukan transaksi terbayar"], ["Pengaju", "Pengurus Contoh"]], flow: ["Ajukan kebutuhan", "Periksa anggaran dan bukti", "Persetujuan pejabat berwenang", "Catat realisasi dan pertanggungjawaban"] },
  { href: "/portal/evaluasi", module: "Evaluasi", id: "DEMO-PERF-001", title: "Evaluasi persiapan materi sosialisasi", status: "Draf evaluasi", summary: "Contoh evaluasi pekerjaan berdasarkan hasil dan hambatan, tanpa memberi skor kinerja kepada pengurus nyata.", fields: [["Indikator", "Kelengkapan materi dan ketepatan tindak lanjut"], ["Temuan", "Naskah tersedia, tetapi belum melewati review"], ["Hambatan", "Catatan reviewer belum diterima"], ["Rekomendasi", "Tetapkan jadwal review sebelum publikasi"]], flow: ["Kumpulkan bukti pekerjaan", "Catat temuan", "Review evaluasi", "Tetapkan tindak lanjut"] },
  { href: "/portal/handover", module: "Serah terima", id: "DEMO-HAND-001", title: "Paket serah terima materi edukasi", status: "Draf paket", summary: "Contoh daftar yang membantu pengurus penerus memahami dokumen, pekerjaan terbuka, dan akses yang perlu ditinjau.", fields: [["Pengirim", "Pengurus Lama Contoh"], ["Penerima", "Pengurus Baru Contoh"], ["Isi paket", "Draf materi, ringkasan rapat, dan daftar tindak lanjut"], ["Pekerjaan terbuka", "Review materi sosialisasi"], ["Pemeriksaan", "Akses tidak dipindahkan otomatis"]], flow: ["Susun paket", "Periksa kelengkapan", "Penerima memeriksa dan menerima", "Tinjau akses dan arsipkan"] },
  { href: "/portal/akses", module: "Akses & identitas", id: "DEMO-ACCESS-001", title: "Penugasan anggota Pencegahan & Edukasi", status: "Usulan penugasan", summary: "Contoh cakupan izin untuk pengurus fiktif. Tidak membuat pengguna, memberikan izin, atau mengubah akses akun Anda.", fields: [["Akun", "pengurus@example.invalid"], ["Posisi", "Anggota divisi — contoh"], ["Cakupan", "Divisi dan periode demonstrasi"], ["Usulan izin", "Membaca serta membuat tugas sesuai penugasan"], ["Di luar cakupan", "Kasus rahasia dan persetujuan keuangan"]], flow: ["Verifikasi identitas", "Catat jabatan dan periode resmi", "Berikan izin sesuai kebijakan", "Tinjau atau cabut saat penugasan berakhir"] },
  { href: "/portal/operasi", module: "Operasi & audit", id: "DEMO-AUDIT-001", title: "Jejak perubahan draf materi", status: "Contoh peristiwa audit", summary: "Contoh informasi yang dicatat ketika dokumen berubah. Bukan bukti bahwa tindakan ini pernah terjadi di production.", fields: [["Pelaku", "Pengurus Contoh"], ["Tindakan", "Memperbarui draf"], ["Objek", "DEMO-DOC-001"], ["Perubahan", "Versi awal menjadi versi untuk review"], ["Alasan", "Melengkapi contoh etika komunikasi"]], flow: ["Pengguna melakukan tindakan", "Sistem memvalidasi izin", "Perubahan dan audit dicatat bersama"] },
  { href: "/portal/katalog", module: "Katalog layar", id: "DEMO-SCREEN-001", title: "Layar detail tugas dan keputusan reviewer", status: "Contoh spesifikasi layar", summary: "Contoh pemetaan layar ke informasi dan tindakan yang harus tersedia, bukan penilaian kesiapan seluruh sistem.", fields: [["Rute", "/portal/tugas"], ["Informasi", "Pemilik, status, hasil, dan riwayat"], ["Tindakan", "Mulai, ajukan hasil, review, dan revisi"], ["Aturan", "Pembuat atau pemilik tidak boleh menyetujui tugas sendiri"]], flow: ["Pilih pekerjaan", "Buka detail", "Lakukan tindakan sesuai izin", "Periksa riwayat perubahan"] },
  { href: "/portal/pengaturan", module: "Organisasi & periode", id: "DEMO-ORG-001", title: "Periode demonstrasi KPI", status: "Contoh konfigurasi", summary: "Contoh struktur data periode. Tidak membuat periode kepengurusan palsu di Supabase.", fields: [["Organisasi", "KPI PPMI Mesir — contoh konfigurasi"], ["Kode", "DEMO_PERIOD"], ["Tanggal", "Diisi sesuai tanggal yang disahkan"], ["Status", "Mengikuti tanggal dan keputusan kepengurusan"]], flow: ["Konfirmasi data resmi", "Simpan organisasi dan periode", "Hubungkan penugasan serta pekerjaan"] }
];

export function findPortalDemo(href: string | undefined): PortalDemo | undefined {
  return portalDemos.find(item => item.href === href);
}
