"use client";
import {useState} from "react";
import {caseOperationsSchema,type CaseOperations,type EvidenceFields} from "@/platform/intake/case-operations-contract";
const blank:EvidenceFields={title:'',source:'',acquisition:'',condition:'',verification:'UNVERIFIED',location:'',assetId:'',receivedOn:'',verifiedOn:'',verificationNote:'',custodian:''};
const labels:Record<string,string>={title:'Nama / kode bukti',source:'Sumber bukti',acquisition:'Asal dan cara perolehan',condition:'Kondisi saat diterima',location:'Lokasi penyimpanan',custodian:'Penanggung jawab penyimpanan',verificationNote:'Dasar dan hasil verifikasi'};
export function CaseEvidenceRegister({caseId,data,editable,onChanged}:{caseId:string;data:CaseOperations;editable:boolean;onChanged:(data:CaseOperations)=>void}):React.JSX.Element{
 const [draft,setDraft]=useState<{id:string;version:number;fields:EvidenceFields;oldLocation:string}|null>(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function save(){if(!draft)return;setBusy(true);setError('');setNotice('');try{const r=await fetch(`/api/v1/work/cases/${caseId}/operations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:draft.id,expectedVersion:draft.version,action:draft.version&&draft.fields.location!==draft.oldLocation?'EVIDENCE_TRANSFER':'EVIDENCE_SAVE',fields:draft.fields,note})});if(!r.ok)throw new Error(r.status===409?'Register berubah. Muat ulang sebelum menyimpan.':r.status===403?'Akses bukti atau lampiran tidak diizinkan.':'Periksa kelengkapan dan status kasus. Bukti belum tersimpan.');onChanged(caseOperationsSchema.parse((await r.json()).item));setDraft(null);setNote('');setNotice('Register dan riwayat bukti tersimpan.');}catch(e){setError(e instanceof Error?e.message:'Penyimpanan gagal.');}finally{setBusy(false);}}
 return <section className="case-forms"><h3>Register bukti</h3><p>Catat asal, kondisi, verifikasi, dan penyimpanan. Perubahan lokasi selalu dicatat sebagai perpindahan dengan alasan. File tetap mengikuti izin lampiran dan pemindaian keamanan.</p>{error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}{editable&&!draft?<button className="button button--quiet" type="button" onClick={()=>{setDraft({id:crypto.randomUUID(),version:0,fields:{...blank},oldLocation:''});setNote('');setNotice('');}}>Catat bukti</button>:null}
 <ul className="hosted-task-list">{data.evidence.map(e=><li key={e.id}><strong>{e.fields.title}</strong><p>Kode {e.id} · revisi {e.version} · {e.fields.verification}</p><p>{e.fields.condition} · Lokasi: {e.fields.location}</p><details><summary>Riwayat dan perpindahan</summary>{e.history.map(h=><div key={h.version}><h4>Revisi {h.version} · {h.authorName}</h4><p>{h.action} · {h.createdAt}</p><p>{h.note}</p>{Object.entries(h.snapshot).filter(([key,value])=>value&&key!=='assetId').map(([key,value])=><p key={key}>{labels[key]||key}: {value}</p>)}</div>)}</details>{editable&&!draft?<button className="button button--quiet" type="button" onClick={()=>{setDraft({id:e.id,version:e.version,fields:e.fields,oldLocation:e.fields.location});setNote('');}}>Edit / pindahkan</button>:null}</li>)}</ul>{!data.evidence.length?<p>Belum ada bukti dalam register.</p>:null}
 {draft?<form onSubmit={e=>{e.preventDefault();void save();}}><fieldset disabled={busy||!editable}><legend>{draft.version?'Perbarui register':'Bukti baru'}</legend>{Object.entries(labels).map(([key,label])=><label key={key}>{label}<input required={['title','source','condition','location'].includes(key)} maxLength={key==='title'?180:2000} value={String(draft.fields[key as keyof EvidenceFields]||'')} onChange={e=>setDraft({...draft,fields:{...draft.fields,[key]:e.target.value}})}/></label>)}<label>Tanggal diterima<input type="date" value={draft.fields.receivedOn} onChange={e=>setDraft({...draft,fields:{...draft.fields,receivedOn:e.target.value}})}/></label><label>Status verifikasi<select value={draft.fields.verification} onChange={e=>setDraft({...draft,fields:{...draft.fields,verification:e.target.value as EvidenceFields['verification']}})}><option value="UNVERIFIED">Belum diverifikasi</option><option value="IN_REVIEW">Dalam pemeriksaan</option><option value="VERIFIED">Terverifikasi oleh petugas</option><option value="DISPUTED">Dipertanyakan</option></select></label><label>Tanggal verifikasi<input type="date" required={draft.fields.verification==='VERIFIED'} value={draft.fields.verifiedOn} onChange={e=>setDraft({...draft,fields:{...draft.fields,verifiedOn:e.target.value}})}/></label><label>Lampiran yang dapat diakses<select value={draft.fields.assetId} onChange={e=>setDraft({...draft,fields:{...draft.fields,assetId:e.target.value}})}><option value="">Bukti fisik / tanpa berkas digital</option>{data.attachments.map(a=><option key={a.assetId} value={a.assetId}>{a.name}</option>)}</select></label><label>Catatan perubahan / alasan perpindahan<textarea required minLength={3} maxLength={2000} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="button-row"><button className="button button--primary" type="submit">{busy?'Menyimpan…':'Simpan register'}</button><button className="button button--quiet" type="button" onClick={()=>setDraft(null)}>Batal</button></div></fieldset></form>:null}</section>;
}
