"use client";
import {CaseSectionEditor} from "./case-section-editor";
import {CaseEvidenceRegister} from "./case-evidence-register";
import {caseOperationsSchema,type CaseOperations} from "@/platform/intake/case-operations-contract";
import {sectionFilled,sectionLines} from "@/platform/intake/case-form-contract";
import {useEffect,useState} from "react";
import {z} from "zod";
import {caseFormSchema,type CaseForm,type CaseFormTemplate} from "@/platform/intake/case-form-contract";

export function HostedCaseForms({caseId,editable,canReview,templates}:{caseId:string;editable:boolean;canReview:boolean;templates:CaseFormTemplate[]}):React.JSX.Element{
 const [items,setItems]=useState<CaseForm[]>([]),[draft,setDraft]=useState<{id:string;code:string;title:string;expectedVersion:number;answers:Record<string,string>}|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{let alive=true;setLoading(true);setDraft(null);setError("");setNotice("");setItems([]);void fetch(`/api/v1/work/cases/${caseId}/forms`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error(r.status===403?"Akses formulir tidak diizinkan.":"Formulir belum dapat dimuat. Hubungan database perlu diperiksa.");return z.object({items:z.array(caseFormSchema)}).parse(await r.json());}).then(r=>{if(alive)setItems(r.items);}).catch(e=>{if(alive)setError(e.message);}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[caseId]);
 const [operations,setOperations]=useState<CaseOperations|null>(null),[operationNote,setOperationNote]=useState(""),[reference,setReference]=useState(""),[referenceAsset,setReferenceAsset]=useState("");
 useEffect(()=>{let alive=true;setOperations(null);void fetch(`/api/v1/work/cases/${caseId}/operations`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error("Register dan workflow belum dapat dimuat.");return caseOperationsSchema.parse((await r.json()).item);}).then(r=>{if(alive)setOperations(r);}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[caseId]);
 async function operation(item:CaseForm,action:string){setBusy(true);setError("");setNotice("");try{const response=await fetch(`/api/v1/work/cases/${caseId}/operations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id,expectedVersion:item.version,action,note:operationNote,...(action==="RECORD_AUTHORIZATION"?{reference,assetId:referenceAsset}:{})})});if(!response.ok)throw new Error(response.status===409?"Formulir berubah. Muat ulang halaman.":response.status===403?"Tindakan memerlukan izin dan pemeriksa yang berbeda.":"Periksa tahap formulir, catatan, dan dokumen rujukan.");setOperations(caseOperationsSchema.parse((await response.json()).item));const r=await fetch(`/api/v1/work/cases/${caseId}/forms`,{cache:"no-store"});if(!r.ok)throw new Error("Status tersimpan; muat ulang daftar formulir.");setItems(z.object({items:z.array(caseFormSchema)}).parse(await r.json()).items);setOperationNote("");setNotice("Tahap pemeriksaan tercatat. Tidak mengesahkan keputusan atau mengubah status kasus.");}catch(e){setError(e instanceof Error?e.message:"Tindakan gagal.");}finally{setBusy(false);}}
 const stageLabels:Record<string,string>={DRAFT:"Draf",SUBMITTED:"Diajukan",CHANGES_REQUESTED:"Perlu revisi",REVIEWED:"Diperiksa",AUTHORIZATION_RECORDED:"Dokumen otorisasi dicatat — belum aktivasi"};
 const template=templates.find(t=>t.code===draft?.code);
 async function save(){if(!draft||busy)return;setBusy(true);setError("");setNotice("");try{const response=await fetch(`/api/v1/work/cases/${caseId}/forms`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});if(!response.ok)throw new Error(response.status===409?"Draf sudah berubah. Tutup editor dan muat ulang halaman sebelum melanjutkan.":response.status===403?"Izin pengelolaan kasus tidak tersedia.":"Draf belum tersimpan. Periksa isian, tahap kasus, dan koneksi.");const {item}=z.object({item:caseFormSchema}).parse(await response.json());setItems(previous=>[...previous.filter(f=>f.id!==item.id),item]);setDraft({...draft,expectedVersion:item.version});setNotice("Draf dan riwayat revisi tersimpan. Ini belum merupakan dokumen yang disahkan.");}catch(e){setError(e instanceof Error?e.message:"Penyimpanan gagal.");}finally{setBusy(false);}}
 return <section aria-labelledby="case-forms-title" className="case-forms"><h3 id="case-forms-title">Formulir penanganan kasus</h3><p>Tujuh format mengikuti dokumen KPI. Catat informasi yang diperlukan saja; pisahkan pernyataan pihak, fakta terverifikasi, rekomendasi, dan keputusan. Unggah dokumen yang sudah ditandatangani melalui lampiran kasus.</p>{loading?<p role="status">Memuat formulir…</p>:null}{error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
 {!loading&&editable&&!draft?<label>Buat draf formulir<select value="" disabled={busy||!!error} onChange={e=>{const t=templates.find(f=>f.code===e.target.value);if(t){setDraft({id:crypto.randomUUID(),code:t.code,title:t.name,expectedVersion:0,answers:{}});setNotice("");}}}><option value="">Pilih format</option>{templates.map(t=><option key={t.code} value={t.code}>{t.code} · {t.name}</option>)}</select></label>:null}
 {operations?<><section><h4>Kelengkapan berkas</h4><p>Indikator pencatatan, bukan penetapan dokumen wajib atau pengesahan. Lampiran yang dapat Anda akses: {operations.attachments.length} · Bukti tercatat: {operations.evidence.length}.</p><ul>{templates.map(t=>{const records=items.filter(f=>f.code===t.code);return <li key={t.code}><strong>{t.code} · {t.name}</strong> — {records.length?`${records.length} catatan tersimpan`:"belum dicatat"}{records.map(f=><details key={f.id}><summary>{f.title} · {t.sections.filter(s=>sectionFilled(f.answers[s.key])).length}/{t.sections.length} bagian tercatat</summary><ul>{t.sections.filter(s=>!sectionFilled(f.answers[s.key])).map(s=><li key={s.key}>{s.title} — belum diisi atau belum diberi alasan tidak berlaku</li>)}</ul></details>)}</li>;})}</ul></section><CaseEvidenceRegister caseId={caseId} data={operations} editable={editable&&!busy} onChanged={setOperations}/></>:null}
 {(editable||canReview)&&operations?<details><summary>Catatan untuk pengajuan dan pemeriksaan</summary><label>Catatan tindakan<textarea minLength={3} maxLength={2000} value={operationNote} disabled={busy} onChange={e=>setOperationNote(e.target.value)}/></label><label>Nomor / rujukan dokumen otorisasi<input maxLength={500} value={reference} disabled={busy} onChange={e=>setReference(e.target.value)}/></label><label>Dokumen otorisasi terlampir<select value={referenceAsset} disabled={busy} onChange={e=>setReferenceAsset(e.target.value)}><option value="">Pilih dokumen yang dapat diakses</option>{operations.attachments.map(a=><option key={a.assetId} value={a.assetId}>{a.name}</option>)}</select></label><p>Pencatatan dokumen tidak memverifikasi tanda tangan dan tidak mengaktifkan keputusan resmi. Aktivasi menunggu mandat.</p></details>:null}
 {items.length?<ul className="hosted-task-list">{items.map(item=><li key={item.id}><strong>{item.code} · {item.title}</strong><p>{stageLabels[item.stage]} · revisi {item.version} · {item.authorName} · {new Date(item.updatedAt).toLocaleString("id-ID",{timeZone:"Africa/Cairo"})}</p><details><summary>Isi dan riwayat revisi</summary>{item.history.map(revision=><details key={revision.version}><summary>Revisi {revision.version} · {revision.authorName}</summary>{templates.find(t=>t.code===item.code)?.sections.filter(s=>sectionFilled(revision.answers[s.key])).map(s=><div key={s.key}><h4>{s.title}</h4><p className="case-source-text">{sectionLines(s,revision.answers[s.key]).join("\n")}</p></div>)}</details>)}</details>{editable&&!draft&&["DRAFT","CHANGES_REQUESTED"].includes(item.stage)?<button className="button button--quiet" type="button" onClick={()=>{setDraft({id:item.id,code:item.code,title:item.title,expectedVersion:item.version,answers:item.answers});setNotice("");}}>Edit draf</button>:null}<div className="button-row"><a className="button button--quiet" href={`/api/v1/work/cases/${caseId}/export?formId=${item.id}&download=1`}>Ekspor HTML</a><a className="button button--quiet" target="_blank" rel="noopener noreferrer" href={`/api/v1/work/cases/${caseId}/export?formId=${item.id}`}>Cetak / PDF</a>{!draft&&editable&&["DRAFT","CHANGES_REQUESTED"].includes(item.stage)?<button className="button button--quiet" disabled={busy||operationNote.trim().length<3} onClick={()=>void operation(item,"SUBMIT")}>Ajukan pemeriksaan</button>:null}{!draft&&editable&&item.stage==="SUBMITTED"?<button className="button button--quiet" disabled={busy||operationNote.trim().length<3} onClick={()=>void operation(item,"WITHDRAW")}>Tarik pengajuan</button>:null}{!draft&&canReview&&item.stage==="SUBMITTED"?<><button className="button button--quiet" disabled={busy||operationNote.trim().length<3} onClick={()=>void operation(item,"REVIEW")}>Catat pemeriksaan</button><button className="button button--quiet" disabled={busy||operationNote.trim().length<3} onClick={()=>void operation(item,"REQUEST_REVISION")}>Minta revisi</button></>:null}{!draft&&canReview&&item.stage==="REVIEWED"?<button className="button button--quiet" disabled={busy||operationNote.trim().length<3||reference.trim().length<3||!referenceAsset} onClick={()=>void operation(item,"RECORD_AUTHORIZATION")}>Catat dokumen otorisasi</button>:null}</div></li>)}</ul>:!loading?<p>Belum ada formulir yang dicatat untuk kasus ini.</p>:null}
 {draft&&template?<form onSubmit={e=>{e.preventDefault();void save();}}><h4>{template.code} · {template.name}</h4><p>Isian per bagian. Menuliskan nama, tanda tangan, otorisasi, atau sanksi tidak mengaktifkan kewenangan dan tidak mengubah status kasus.</p><label>Judul catatan<input required minLength={3} maxLength={180} disabled={busy||!editable} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label>{template.sections.map(section=><details key={section.key}><summary>{section.title}{sectionFilled(draft.answers[section.key])?" · tercatat":""}</summary><details><summary>Petunjuk formulir asli</summary><pre className="case-source-text">{section.guide}</pre></details><CaseSectionEditor section={section} value={draft.answers[section.key]||""} disabled={busy||!editable} evidence={operations?.evidence||[]} onChange={value=>setDraft({...draft,answers:{...draft.answers,[section.key]:value}})}/></details>)}<div className="button-row"><button className="button button--primary" type="submit" disabled={busy||!editable}>{busy?"Menyimpan…":"Simpan draf"}</button><button className="button button--quiet" type="button" disabled={busy} onClick={()=>setDraft(null)}>Tutup editor</button></div><p>Perubahan belum tersimpan sampai tombol Simpan draf ditekan. Gunakan catatan berbeda untuk setiap pemanggilan, wawancara, atau bukti.</p></form>:null}{operations?.events.length?<details><summary>Riwayat workflow formulir</summary><ul>{operations.events.map((e,i)=><li key={i}>{e.authorName} · {e.action} · revisi {e.version}<p>{e.note}</p>{e.reference?<p>Rujukan: {e.reference}</p>:null}<small>{e.createdAt}</small></li>)}</ul></details>:null}</section>;
}
