"use client";
import {useEffect,useState} from 'react';
import {z} from 'zod';
import {portalJson} from '@/components/portal/hosted-management-workspace';
const schema=z.object({version:z.number(),markers:z.array(z.string()),category:z.enum(['PUBLICATION','NEWS','EVENT','ROSTER']),metadata:z.record(z.string(),z.unknown()),classification:z.string(),schedule:z.object({publishAt:z.string(),status:z.string(),reason:z.string().nullable()}).nullable()});
const categories={PUBLICATION:'Publikasi',NEWS:'Kabar',EVENT:'Kegiatan',ROSTER:'Pengurus'};
export function HostedEditorialReadiness({id,version,editable,canPublish,approved,onChanged}:{id:string;version:number;editable:boolean;canPublish:boolean;approved:boolean;onChanged:()=>Promise<void>}){
 const [data,setData]=useState<z.infer<typeof schema>|null>(null),[category,setCategory]=useState<keyof typeof categories>('PUBLICATION'),[date,setDate]=useState(''),[location,setLocation]=useState(''),[position,setPosition]=useState(''),[period,setPeriod]=useState(''),[consent,setConsent]=useState(''),[note,setNote]=useState(''),[scheduled,setScheduled]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let current=true;setData(null);void portalJson(`/api/v1/work/content/${id}/readiness`).then(r=>{if(!current)return;const d=schema.parse(r.data);setData(d);setCategory(d.category);setDate(String(d.metadata.eventDate||''));setLocation(String(d.metadata.location||''));setPosition(String(d.metadata.position||''));setPeriod(String(d.metadata.periodLabel||''));setConsent(String(d.metadata.consentReference||''));}).catch(e=>{if(current)setError((e as Error).message);});return()=>{current=false;};},[id,version]);
 async function save(body:object){if(busy)return;setBusy(true);setError('');try{await portalJson(`/api/v1/work/content/${id}/readiness`,{expectedVersion:version,...body});await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div><h3>Kesiapan informasi publik</h3>{error&&<p role="alert">{error}</p>}{data&&<><p>Kategori: {categories[data.category]} · Klasifikasi: {data.classification}</p>{data.markers.length?<p role="status">Pola data pribadi ditemukan: {data.markers.join(', ')}. Hapus atau samarkan sebelum diterbitkan.</p>:<p>Tidak ditemukan pola email, nomor kontak/identitas. Tetap periksa nama, konteks kasus, foto, dan persetujuan publikasi secara manual.</p>}<a href={`/portal/kebijakan?resource=${id}`}>Ajukan klasifikasi terbuka</a>{data.schedule&&<p>Jadwal: {new Date(data.schedule.publishAt).toLocaleString('id-ID')} · {data.schedule.status}{data.schedule.reason?` · ${data.schedule.reason}`:''}</p>}</>}
 {editable&&<details><summary>Kategori dan metadata resmi</summary><label>Kategori<select disabled={busy} value={category} onChange={e=>setCategory(e.target.value as keyof typeof categories)}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>{category==='EVENT'&&<><label>Tanggal kegiatan<input type="date" value={date} disabled={busy} onChange={e=>setDate(e.target.value)}/></label><label>Lokasi<input maxLength={200} value={location} disabled={busy} onChange={e=>setLocation(e.target.value)}/></label></>}{category==='ROSTER'&&<><label>Jabatan<input maxLength={180} value={position} disabled={busy} onChange={e=>setPosition(e.target.value)}/></label><label>Periode<input maxLength={100} value={period} disabled={busy} onChange={e=>setPeriod(e.target.value)}/></label><label>Rujukan persetujuan publikasi profil<input maxLength={500} value={consent} disabled={busy} onChange={e=>setConsent(e.target.value)}/></label></>}<label>Catatan<textarea maxLength={2000} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></label><button type="button" disabled={busy||note.trim().length<3} onClick={()=>void save({command:'METADATA',category,note,metadata:category==='EVENT'?{eventDate:date,location}:category==='ROSTER'?{position,periodLabel:period,consentReference:consent}:{}})}>Simpan metadata</button></details>}
 {canPublish&&approved&&<details><summary>Jadwalkan penerbitan</summary><p>Pekerja terjadwal memeriksa kembali versi, izin, periode, klasifikasi, serta persetujuan sebelum menerbitkan. Memerlukan konfigurasi cron production.</p><label>Tanggal dan waktu<input type="datetime-local" disabled={busy} value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label><button type="button" disabled={busy||!scheduled} onClick={()=>void save({command:'SCHEDULE',publishAt:new Date(scheduled).toISOString()})}>Simpan jadwal</button><button type="button" disabled={busy} onClick={()=>void save({command:'SCHEDULE',publishAt:null})}>Batalkan jadwal</button></details>}
 </div>;
}
