"use client";
import {HostedRichEditor} from "./hosted-rich-editor";
import {RichTextView} from "./rich-text-view";
import {HostedEditorialReadiness} from "./hosted-editorial-readiness";
import {HostedAttachments} from "@/components/documents/hosted-attachments";
import {useCallback,useEffect,useRef,useState} from "react";
import {z} from "zod";
import {contentFieldsSchema,hostedContentSchema,type HostedContent} from "@/platform/content/hosted-content-contract";
import {hasHostedPermission,type HostedAccess} from "@/platform/authorization/hosted-access";
import type {HostedTaskScope} from "@/platform/work/hosted-task-contract";
import type {Permission} from "@/platform/authorization/permissions";

const blank={title:"",summary:"",body:"",source:"",locale:"id" as "id"|"en",slug:""};
const labels:Record<HostedContent["status"],string>={DRAFT:"Draf",IN_REVIEW:"Menunggu review",REVISION:"Perlu revisi",APPROVED:"Disetujui",PUBLISHED:"Diterbitkan",ARCHIVED:"Diarsipkan"};
async function api(url:string,body?:unknown):Promise<unknown>{const response=await fetch(url,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});if(!response.ok)throw new Error(response.status===409?"Konten telah berubah. Muat ulang sebelum melanjutkan.":response.status===403?"Izin tindakan tidak tersedia atau review harus dilakukan pengurus lain.":response.status===400?"Periksa isian, alamat artikel dan tahap konten.":response.status===401?"Sesi berakhir. Silakan masuk kembali.":"Layanan konten belum dapat dihubungi.");return response.json();}
export function HostedContentWorkspace({identity,scopes,kind}:{identity:HostedAccess;scopes:HostedTaskScope[];kind:"KNOWLEDGE"|"PUBLICATION"}):React.JSX.Element{
 const [scopeIndex,setScopeIndex]=useState(0),scope=scopes[scopeIndex];
 const [items,setItems]=useState<HostedContent[]>([]),[selected,setSelected]=useState<HostedContent|null>(null),[fields,setFields]=useState(blank),[editing,setEditing]=useState(false);
 const [note,setNote]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[query,setQuery]=useState("");
 const [privacyReviewed,setPrivacyReviewed]=useState(false);
 const generation=useRef(0),detailGeneration=useRef(0),key=useRef<string|null>(null);
 const permissionScope={...scope,divisionCode:scope.divisionCode||undefined};
 const write:Permission=kind==="KNOWLEDGE"?"KNOWLEDGE_WRITE":"CONTENT_DRAFT_WRITE",review:Permission=kind==="KNOWLEDGE"?"KNOWLEDGE_REVIEW":"CONTENT_REVIEW",publish:Permission=kind==="KNOWLEDGE"?"KNOWLEDGE_REVIEW":"CONTENT_PUBLISH";
 const canWrite=hasHostedPermission(identity,write,permissionScope);
 const reload=useCallback(async()=>{const current=++generation.current;setLoading(true);setError("");const p=new URLSearchParams({organizationCode:scope.organizationCode,periodCode:scope.periodCode,kind});if(scope.divisionCode)p.set("divisionCode",scope.divisionCode);try{const result=z.object({items:z.array(hostedContentSchema)}).parse(await api(`/api/v1/work/content?${p}`));if(current===generation.current)setItems(result.items);}catch(failure){if(current===generation.current){setItems([]);setError(failure instanceof Error?failure.message:"Gagal membaca konten.");}}finally{if(current===generation.current)setLoading(false);}},[scope.organizationCode,scope.periodCode,scope.divisionCode,kind]);
 useEffect(()=>{setSelected(null);setEditing(false);setFields(blank);key.current=null;detailGeneration.current++;void reload();return()=>{generation.current++;detailGeneration.current++;};},[reload]);
 async function open(id:string){const current=++detailGeneration.current;setEditing(false);setError("");try{const {item}=z.object({item:hostedContentSchema}).parse(await api(`/api/v1/work/content/${id}`));if(current===detailGeneration.current){setSelected(item);setPrivacyReviewed(false);setFields(contentFieldsSchema.parse({title:item.title,summary:item.summary,body:item.body,source:item.source,locale:item.locale,slug:item.slug}));setNote("");}}catch(failure){if(current===detailGeneration.current)setError(failure instanceof Error?failure.message:"Gagal membuka konten.");}}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError("");setNotice("");try{const body=editing&&selected?{action:"SAVE",expectedVersion:selected.version,note,fields}:{...scope,kind,fields,idempotencyKey:key.current??(key.current=crypto.randomUUID())};const {item}=z.object({item:hostedContentSchema}).parse(await api(editing&&selected?`/api/v1/work/content/${selected.id}`:"/api/v1/work/content",body));key.current=null;await reload();await open(item.id);setNotice("Konten tersimpan di database KPI.");}catch(failure){setError(failure instanceof Error?failure.message:"Gagal menyimpan konten.");}finally{setBusy(false);}}
 async function act(action:string){if(!selected||busy)return;setBusy(true);setError("");setNotice("");try{const {item}=z.object({item:hostedContentSchema}).parse(await api(`/api/v1/work/content/${selected.id}`,{action,expectedVersion:selected.version,note,privacyReviewed}));await reload();await open(item.id);setNotice("Tahap konten diperbarui.");}catch(failure){setError(failure instanceof Error?failure.message:"Gagal mengubah tahap konten.");}finally{setBusy(false);}}
 const itemScope={...permissionScope,objectId:selected?.id};
 const independent=selected&&identity.accountId!==selected.authorAccountId;
 const actions=selected?[
 ...(hasHostedPermission(identity,write,itemScope)&&["DRAFT","REVISION"].includes(selected.status)?[{action:"SUBMIT",label:"Ajukan review"}]:[]),
 ...(hasHostedPermission(identity,review,itemScope)&&independent&&selected.status==="IN_REVIEW"?[{action:"APPROVE",label:"Setujui konten"},{action:"REQUEST_REVISION",label:"Minta revisi"}]:[]),
 ...(hasHostedPermission(identity,publish,itemScope)&&selected.status==="APPROVED"?[{action:"PUBLISH",label:kind==="PUBLICATION"?"Terbitkan ke publik":"Terbitkan rujukan internal"}]:[]),
 ...(hasHostedPermission(identity,publish,itemScope)&&selected.status==="PUBLISHED"?[{action:"WITHDRAW",label:"Tarik untuk revisi"}]:[]),
 ...(hasHostedPermission(identity,publish,itemScope)&&!["ARCHIVED","IN_REVIEW"].includes(selected.status)?[{action:"ARCHIVE",label:"Arsipkan"}]:[])
 ]:[];
 function field<K extends keyof typeof blank>(name:K,value:(typeof blank)[K]){setFields(f=>({...f,[name]:value}));key.current=null;}
 return <div className="hosted-task-workspace"><section className="portal-form-card"><label>Periode dan divisi<select value={scopeIndex} disabled={busy} onChange={e=>setScopeIndex(Number(e.target.value))}>{scopes.map((s,i)=><option key={JSON.stringify(s)} value={i}>{s.organizationCode} · {s.periodCode}{s.divisionCode?` · ${s.divisionCode}`:""}</option>)}</select></label></section>
 {error?<section className="operations-panel" role="alert"><p>{error}</p><button className="button button--quiet" disabled={busy} onClick={()=>void reload()}>Muat ulang</button></section>:null}{notice?<p role="status">{notice}</p>:null}
 <section className="portal-form-card"><h2>{kind==="KNOWLEDGE"?"Rujukan internal":"Konten redaksi"}</h2><label>Cari judul<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>{loading?<p role="status">Membaca konten…</p>:<ul className="hosted-task-list">{items.filter(i=>i.title.toLocaleLowerCase("id-ID").includes(query.toLocaleLowerCase("id-ID"))).map(i=><li key={i.id}><button type="button" className="hosted-task-list__row" aria-pressed={selected?.id===i.id} disabled={busy} onClick={()=>void open(i.id)}><span><strong>{i.title}</strong><small>{i.locale.toUpperCase()} · Versi {i.version}</small></span><span>{labels[i.status]}</span></button></li>)}</ul>}{!loading&&!items.length?<p>Belum ada konten pada periode ini.</p>:null}<p>Menampilkan 100 konten yang terakhir diperbarui.</p>{canWrite?<button className="button button--quiet" disabled={busy} onClick={()=>{setSelected(null);setFields(blank);setEditing(false);setNote("");key.current=null;}}>Buat draf baru</button>:null}</section>
 {canWrite&&(!selected||editing)?<form className="portal-form-card" onSubmit={save}><h2>{editing?"Ubah draf":"Draf baru"}</h2><label>Judul<input required minLength={3} maxLength={180} value={fields.title} disabled={busy} onChange={e=>field("title",e.target.value)}/></label><label>Alamat artikel<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" maxLength={150} value={fields.slug} disabled={busy} onChange={e=>field("slug",e.target.value)}/></label><p>Gunakan huruf kecil dan tanda hubung, misalnya pedoman-interaksi.</p><label>Ringkasan<textarea required minLength={3} maxLength={1000} rows={3} value={fields.summary} disabled={busy} onChange={e=>field("summary",e.target.value)}/></label><HostedRichEditor value={fields.body} disabled={busy} onChange={body=>field("body",body)}/><label>Sumber dan versi dokumen<input required minLength={3} maxLength={1000} value={fields.source} disabled={busy} onChange={e=>field("source",e.target.value)}/></label><label>Bahasa<select value={fields.locale} disabled={busy} onChange={e=>field("locale",e.target.value as "id"|"en")}><option value="id">Indonesia</option><option value="en">English</option></select></label>{editing?<label>Catatan revisi<textarea required minLength={3} maxLength={2000} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></label>:null}<button className="button button--primary" disabled={busy}>{busy?"Menyimpan…":"Simpan draf"}</button></form>:null}
 {selected&&!editing?<section className="portal-form-card"><h2>{selected.title}</h2><p>{labels[selected.status]} · Versi {selected.version}</p><p>{selected.summary}</p><RichTextView source={selected.body} className="cms-prose"/><p>Sumber: {selected.source}</p>{hasHostedPermission(identity,write,itemScope)&&["DRAFT","REVISION"].includes(selected.status)?<button className="button button--quiet" disabled={busy} onClick={()=>setEditing(true)}>Ubah draf</button>:null}{actions.length?<><label>Catatan tindakan<textarea minLength={3} maxLength={2000} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></label>{kind==="PUBLICATION"&&actions.some(a=>["APPROVE","PUBLISH"].includes(a.action))?<label><input type="checkbox" checked={privacyReviewed} disabled={busy} onChange={e=>setPrivacyReviewed(e.target.checked)}/>Saya telah memeriksa privasi, sumber, dan kelayakan informasi ini untuk publik.</label>:null}<div className="portal-form-actions">{actions.map(a=><button type="button" key={a.action} className="button button--quiet" disabled={busy||note.trim().length<3||(kind==="PUBLICATION"&&["APPROVE","PUBLISH"].includes(a.action)&&!privacyReviewed)} onClick={()=>void act(a.action)}>{a.label}</button>)}</div></>:null}<p>{kind==="KNOWLEDGE"?"Rujukan ini hanya tersedia bagi pengurus yang berizin.":"Konten hanya tampil di website publik setelah review dan penerbitan."} Pembuat atau penulis konten tidak boleh menyetujui kontennya sendiri.</p><HostedAttachments module="CONTENT" entityId={selected.id} version={selected.version} scope={scope} editable={hasHostedPermission(identity,write,itemScope)&&["DRAFT","REVISION"].includes(selected.status)} onChanged={async()=>{await reload();await open(selected.id);}}/>{kind==="PUBLICATION"?<HostedEditorialReadiness id={selected.id} version={selected.version} editable={hasHostedPermission(identity,write,itemScope)&&["DRAFT","REVISION"].includes(selected.status)} canPublish={hasHostedPermission(identity,publish,itemScope)} approved={selected.status==="APPROVED"} onChanged={async()=>{await reload();await open(selected.id);}}/>:null}<h3>Riwayat perubahan</h3><ol>{selected.events.map(e=><li key={e.version}><strong>{e.action} · {e.actorName}</strong><p>{e.note}</p><small>Versi {e.version} · {new Date(e.createdAt).toLocaleString("id-ID")}</small></li>)}</ol></section>:null}</div>;
}
