import assert from 'node:assert/strict';
import test from 'node:test';
import {governanceContextSchema} from '../src/platform/governance/contract';
import {createHostedDatabase,hostedFixture as f,loginHostedFixture} from './fixtures/hosted-database';
const migrations=['00300_hosted_tasks','00400_system_administration','00500_hosted_meetings','00600_hosted_content','00700_publication_organization_scope','00800_hosted_assets','00900_hosted_notifications','01000_hosted_intake_cases','01100_case_notifications','01200_operational_schema_check','01300_confidentiality_sop_v11','01400_sop_asset_case_enforcement','01500_governance_workflows','01600_transition_access_expiry','01700_workflow_approval_binding'].map(s=>`migrations/202610020${s}.sql`);
type R={id:string;version:number;status:string;payload:Record<string,any>;canRead:boolean;events:any[]};
test('SOP workflows persist access decisions, incidents, classification and scoped offboarding',async()=>{
 const db=await createHostedDatabase(migrations,[]);
 const {owner,reviewer,stranger,organization,period}=f;
 const cap=['TASK_READ','TASK_CREATE','ASSET_READ','ASSET_DOWNLOAD','SOP_ACCESS_REVIEW','SOP_ACCESS_SUSPEND','SOP_INCIDENT_HANDLE','SOP_INCIDENT_APPROVE','SOP_BPI_REVIEW','SOP_OFFBOARD_MANAGE','SOP_OFFBOARD_VERIFY','SOP_TECHNICAL_OFFBOARD','INFORMATION_CLASSIFY','INFORMATION_DECLASSIFY','INFORMATION_HOLD','INFORMATION_HOLD_RELEASE'];
 const key=()=>crypto.randomUUID();
 async function create(kind:string,input:Record<string,unknown>,requestKey=key()){return(await db.query<{r:R}>('select public.kpi_governance_create($1,$2,$3) r',[kind,JSON.stringify({organizationId:organization,periodId:period,classification:'INTERNAL',...input}),requestKey])).rows[0].r;}
 async function act(r:R,action:string,input:Record<string,unknown>={}){return(await db.query<{r:R}>('select public.kpi_governance_action($1,$2,$3,$4) r',[r.id,r.version,action,JSON.stringify(input)])).rows[0].r;}
 async function context(){const c=(await db.query<{c:any}>('select public.kpi_governance_context() c')).rows[0].c;governanceContextSchema.parse(c);return c;}
 try{
 await db.exec(`insert into identity.roles(code,name) values('ADMIN_SISTEM','Admin');insert into identity.account_roles(account_id,role_id) select '${stranger}',id from identity.roles where code='ADMIN_SISTEM';insert into identity.system_administrators(account_id,approved_reason) values('${stranger}','Isolated fixture technical approval');insert into org.assignments(account_id,position_id,period_id,starts_on) select '${stranger}',id,'${period}',current_date-1 from org.positions;`);
 const authority:Record<string,string>={};
 for(const account of [reviewer,stranger])authority[account]=(await db.query<{id:string}>('insert into governance.access_authorities(account_id,organization_id,period_id,classifications,permissions,mandate_reference,starts_at,expires_at) values($1,$2,$3,$4,$5,$6,now()-interval \'1 hour\',now()+interval \'1 day\') returning id',[account,organization,period,['INTERNAL','TERBATAS','RAHASIA'],account===stranger?cap.filter(p=>p.startsWith('SOP_')||p.startsWith('INFORMATION_')):cap,'Isolated fixture written mandate'])).rows[0].id;
 await loginHostedFixture(db,owner);
 const input={formReference:'Fixture F01-001',requestType:'GRANT',permissions:['TASK_READ','TASK_CREATE'],purpose:'Fixture coordination',informationScope:'Fixture task metadata',mandateReference:'Fixture assignment',startsAt:new Date(Date.now()-1000).toISOString(),expiresAt:new Date(Date.now()+3600000).toISOString()};
 const requestKey=key();let access=await create('ACCESS',input,requestKey);assert.equal((await create('ACCESS',input,requestKey)).id,access.id);
 await assert.rejects(create('ACCESS',{...input,purpose:'Changed purpose'},requestKey),/Request key already used/);
 await assert.rejects(act(access,'DECIDE',{authorityId:authority[reviewer],outcome:'APPROVED',approvedPermissions:['TASK_READ'],reference:'Fixture approval',needFinding:'Fixture need verified',note:'Fixture approved'}),/Independent decision/);
 await loginHostedFixture(db,reviewer);
 await assert.rejects(act(access,'DECIDE',{authorityId:authority[reviewer],outcome:'APPROVED',approvedPermissions:['ASSET_DOWNLOAD'],reference:'Fixture approval',needFinding:'Fixture need verified',note:'Fixture approved'}),/exceeds request/);
 access=await act(access,'DECIDE',{authorityId:authority[reviewer],outcome:'PARTIAL',approvedPermissions:['TASK_READ'],reference:'Fixture approval',needFinding:'Fixture need verified',note:'Fixture read only'});assert.equal(access.status,'PARTIAL');
 await assert.rejects(act({...access,version:1},'IMPLEMENT',{reference:'Fixture technical execution'}),/refresh first/);
 await loginHostedFixture(db,stranger);const technical=(await context()).records.find((r:R)=>r.id===access.id);assert.equal(technical.canRead,false);assert.equal(technical.payload.purpose,undefined);assert.equal(technical.payload.submission,undefined);
 access=await act(access,'IMPLEMENT',{reference:'Fixture technical execution'});assert.equal(access.status,'IMPLEMENTED');
 await loginHostedFixture(db,owner);assert.equal((await context()).register[0].status,'ACTIVE');
 let denied=await create('ACCESS',{...input,formReference:'Fixture F01 denied'});await loginHostedFixture(db,reviewer);denied=await act(denied,'DECIDE',{authorityId:authority[reviewer],outcome:'DENIED',reference:'Fixture rejection',needFinding:'Fixture unnecessary',note:'Fixture rejected'});assert.equal(denied.status,'DENIED');await assert.rejects(act(denied,'IMPLEMENT',{reference:'Fixture denied attempt'}),/finalized/);
 await loginHostedFixture(db,owner);
 let incident=await create('INCIDENT',{formReference:'Fixture F03-001',incidentType:'UNAUTH_ACCESS',description:'Fixture report, facts still incomplete',classification:'RAHASIA',affectedClassification:'UNKNOWN'});assert.equal(incident.status,'SECURITY');
 await loginHostedFixture(db,reviewer);let hidden=(await context()).records.find((r:R)=>r.id===incident.id);assert.equal(hidden.canRead,false);assert.equal(hidden.payload.description,undefined);
 incident=await act(incident,'ASSIGN',{handlerAccountId:reviewer,reference:'Fixture incident assignment',note:'Fixture responsible handler'});assert.equal(incident.canRead,true);
 incident=await act(incident,'CORRECTION',{picAccountId:owner,dueAt:new Date(Date.now()+3600000).toISOString(),note:'Fixture correction'});
 incident=await act(incident,'REQUEST_RECOVERY',{reviewerAccountId:stranger,reference:'Fixture recovery request',residualRisk:'Fixture reduced risk'});
 await loginHostedFixture(db,stranger);await assert.rejects(act(incident,'CLOSE',{reference:'Fixture premature closure',note:'Fixture premature'}),/prerequisites/);
 incident=await act(incident,'VERIFY_CORRECTION',{entryId:incident.payload.corrections[0].id,reference:'Fixture correction verified'});
 incident=await act(incident,'NOTICE_DECISION',{outcome:'NOT_REQUIRED',reference:'Fixture notice assessment',note:'Fixture no affected party identified'});
 incident=await act(incident,'APPROVE_RECOVERY',{reference:'Fixture recovery approval'});
 incident=await act(incident,'CLOSE',{reference:'Fixture closure decision',note:'Fixture technical closure'});assert.equal(incident.status,'CLOSED');assert.equal(incident.payload.bpiStatus,'NOT_APPLICABLE');
 await db.exec('reset role;');const asset=(await db.query<{id:string}>('insert into files.managed_assets(organization_id,period_id,owner_account_id,original_name,mime_type,size_bytes,sha256,object_path,request_key,status) values($1,$2,$3,\'fixture.pdf\',\'application/pdf\',100,$4,\'fixture-evidence\',gen_random_uuid(),\'AVAILABLE\') returning id',[organization,period,owner,'a'.repeat(64)])).rows[0].id;
 await loginHostedFixture(db,reviewer);let classification=await create('CLASSIFICATION',{formReference:'Fixture classify-001',mode:'HOLD',objectId:asset,newClassification:'RAHASIA',reason:'Fixture preserve evidence',basis:'Fixture written evidence hold'});
 await assert.rejects(act(classification,'APPROVE',{reference:'Fixture self approval',note:'Fixture own decision'}),/Independent classification/);
 await loginHostedFixture(db,stranger);classification=await act(classification,'APPROVE',{reference:'Fixture hold approval',note:'Fixture preserve asset'});assert.equal(classification.status,'COMPLETED');
 await db.exec('reset role;');await assert.rejects(db.query('delete from files.managed_assets where id=$1',[asset]),/Evidence hold/);
 await db.exec('reset role;');
 const transitionId=(await db.query<{id:string}>("insert into governance.workflow_records(kind,organization_id,period_id,creator_account_id,classification,status,request_key,payload) values('OFFBOARD',$1,$2,$3,'INTERNAL','APPROVED',gen_random_uuid(),$4) returning id",[organization,period,owner,JSON.stringify({subjectAccountId:owner,effectiveAt:new Date(Date.now()-1000).toISOString(),transitionDecisionIds:access.payload.decisionIds,transitionExpiresAt:new Date(Date.now()+3600000).toISOString()})])).rows[0].id;
 await loginHostedFixture(db,owner);assert.equal((await context()).register.find((d:any)=>d.id===access.payload.decisionIds[0]).status,'ACTIVE');
 await db.exec('reset role;');await db.query("update governance.workflow_records set payload=jsonb_set(payload,'{transitionExpiresAt}',to_jsonb((now()-interval '1 minute')::text)) where id=$1",[transitionId]);
 await loginHostedFixture(db,owner);assert.equal((await context()).register.find((d:any)=>d.id===access.payload.decisionIds[0]).status,'INACTIVE');
 await db.exec('reset role;');await db.query("update governance.workflow_records set status='DRAFT' where id=$1",[transitionId]);
 await loginHostedFixture(db,owner);const reporterView=(await context()).records.find((r:R)=>r.id===incident.id);assert.equal(reporterView.payload.residualRisk,undefined);assert.equal(reporterView.payload.corrections,undefined);assert.equal(reporterView.events.length,1);
 await loginHostedFixture(db,reviewer);
 const decisionId=access.payload.decisionIds[0];
 const review=(await db.query<{id:string}>("select public.kpi_access_review_action('RECORD',$1) id",[JSON.stringify({decisionId,trigger:'PERIODIC',finding:'Fixture scope remains necessary',followUp:'Fixture reassess mandate',picAccountId:owner,dueAt:new Date(Date.now()+3600000).toISOString()})])).rows[0].id;
 await loginHostedFixture(db,owner);await assert.rejects(db.query("select public.kpi_access_review_action('VERIFY',$1)",[JSON.stringify({reviewId:review,reference:'Fixture self follow-up'})]),/Independent review/);
 await loginHostedFixture(db,stranger);await db.query("select public.kpi_access_review_action('VERIFY',$1)",[JSON.stringify({reviewId:review,reference:'Fixture independent review'})]);
 await db.query("select public.kpi_access_review_action('SUSPEND',$1)",[JSON.stringify({reviewId:review,reference:'Fixture protective suspension',finding:'Fixture risk requires protective pause'})]);
 await loginHostedFixture(db,owner);assert.equal((await context()).register.find((d:any)=>d.id===decisionId).status,'SUSPENDED');assert.equal((await context()).reviews[0].suspensionReason,'Fixture risk requires protective pause');
 let restore=await create('ACCESS',{...input,permissions:['TASK_READ'],requestType:'RESTORE',targetDecisionId:decisionId,formReference:'Fixture restore-001'});
 await loginHostedFixture(db,reviewer);restore=await act(restore,'DECIDE',{authorityId:authority[reviewer],outcome:'APPROVED',approvedPermissions:['TASK_READ'],reference:'Fixture restore approval',needFinding:'Fixture risk resolved',note:'Fixture restore limited scope'});
 await loginHostedFixture(db,stranger);restore=await act(restore,'IMPLEMENT',{reference:'Fixture restore execution'});
 await loginHostedFixture(db,owner);assert.equal((await context()).register.find((d:any)=>d.id===restore.payload.decisionIds[0]).status,'ACTIVE');
 let revoke=await create('ACCESS',{...input,permissions:['TASK_READ'],requestType:'REVOKE',targetDecisionId:restore.payload.decisionIds[0],formReference:'Fixture revoke-001'});
 await loginHostedFixture(db,reviewer);revoke=await act(revoke,'DECIDE',{authorityId:authority[reviewer],outcome:'APPROVED',approvedPermissions:['TASK_READ'],reference:'Fixture revoke approval',needFinding:'Fixture need ended',note:'Fixture limited revocation'});
 await loginHostedFixture(db,stranger);revoke=await act(revoke,'IMPLEMENT',{reference:'Fixture revoke execution'});
 await loginHostedFixture(db,owner);assert.equal((await context()).register.find((d:any)=>d.id===restore.payload.decisionIds[0]).status,'REVOKED');
 await loginHostedFixture(db,owner);let change=await create('ACCESS',{...input,permissions:['TASK_CREATE'],requestType:'CHANGE',targetDecisionId:decisionId,formReference:'Fixture change-001'});
 await loginHostedFixture(db,reviewer);change=await act(change,'DECIDE',{authorityId:authority[reviewer],outcome:'APPROVED',approvedPermissions:['TASK_CREATE'],reference:'Fixture changed scope approval',needFinding:'Fixture new task need',note:'Fixture changed actions'});
 await loginHostedFixture(db,stranger);change=await act(change,'IMPLEMENT',{reference:'Fixture changed scope execution'});
 await loginHostedFixture(db,owner);const changedRegister=(await context()).register;assert.equal(changedRegister.find((d:any)=>d.id===decisionId).status,'REVOKED');assert.equal(changedRegister.find((d:any)=>d.id===change.payload.decisionIds[0]).status,'ACTIVE');
 let bpi=await create('INCIDENT',{formReference:'Fixture BPI report',incidentType:'OTHER',description:'Fixture possible personnel concern',classification:'RAHASIA',personnelConcern:true});
 await db.exec('reset role;');await db.query("update governance.access_authorities set permissions=array_remove(permissions,'SOP_BPI_REVIEW') where id=$1",[authority[reviewer]]);
 await loginHostedFixture(db,reviewer);await assert.rejects(act(bpi,'ASSIGN',{handlerAccountId:reviewer,reference:'Fixture invalid routing',note:'Fixture regular handler'}),/denied/);
 await loginHostedFixture(db,stranger);bpi=await act(bpi,'ASSIGN',{handlerAccountId:stranger,reference:'Fixture independent BPI routing',note:'Fixture designated BPI handler'});bpi=await act(bpi,'BPI_RESULT',{reference:'Fixture BPI written result'});assert.equal(bpi.payload.bpiStatus,'RESULT_RECORDED');assert.notEqual(bpi.status,'CLOSED');
 await loginHostedFixture(db,reviewer);
 let release=await create('CLASSIFICATION',{formReference:'Fixture release-001',mode:'RELEASE',objectId:asset,newClassification:'RAHASIA',reason:'Fixture authorized hold release',basis:'Fixture evidence archived'});
 let stale=await create('CLASSIFICATION',{formReference:'Fixture classify-002',mode:'CLASSIFY',objectId:asset,newClassification:'INTERNAL',reason:'Fixture redacted information',basis:'Fixture declassification assessment'});
 await loginHostedFixture(db,stranger);release=await act(release,'APPROVE',{reference:'Fixture release approval',note:'Fixture release verified'});await assert.rejects(act(stale,'APPROVE',{reference:'Fixture stale approval',note:'Fixture stale object'}),/changed/);
 await loginHostedFixture(db,reviewer);let downgrade=await create('CLASSIFICATION',{formReference:'Fixture classify-003',mode:'CLASSIFY',objectId:asset,newClassification:'INTERNAL',reason:'Fixture safe redacted content',basis:'Fixture declassification assessment'});
 await loginHostedFixture(db,stranger);downgrade=await act(downgrade,'APPROVE',{reference:'Fixture classification approval',note:'Fixture authorized downgrade'});assert.equal(downgrade.status,'COMPLETED');
 await loginHostedFixture(db,owner);
 let offboard=await create('OFFBOARD',{formReference:'Fixture F05-001',subjectAccountId:owner,successorAccountId:reviewer,verifierAccountId:stranger,effectiveAt:new Date(Date.now()-1000).toISOString(),basis:'Fixture end of duties',function:'Fixture member'});
 await assert.rejects(act(offboard,'SUBMIT'),/incomplete/);
 await loginHostedFixture(db,reviewer);await assert.rejects(act(offboard,'RECEIVE',{reference:'Fixture receipt before submission'}),/Successor required/);await loginHostedFixture(db,owner);
 for(const check of ['basis','inventory','documents','responsibilities','accounts','evidence','copies','transition','confidentiality'])offboard=await act(offboard,'CHECK',{check,checkStatus:'DONE',note:'Fixture verified reference'});
 offboard=await act(offboard,'SUBMIT');await loginHostedFixture(db,reviewer);offboard=await act(offboard,'RECEIVE',{reference:'Fixture successor receipt'});
 await loginHostedFixture(db,stranger);offboard=await act(offboard,'APPROVE',{reference:'Fixture independent verification'});
 await loginHostedFixture(db,owner);assert.ok((await context()).register.every((d:any)=>d.status!=='ACTIVE'));
 await loginHostedFixture(db,stranger);offboard=await act(offboard,'IMPLEMENT',{reference:'Fixture revocation execution'});offboard=await act(offboard,'CLOSE',{reference:'Fixture completed handover'});assert.equal(offboard.status,'CLOSED');
 await loginHostedFixture(db,owner);assert.ok((await context()).register.every((d:any)=>d.status==='REVOKED'));assert.ok((await context()).records.find((r:R)=>r.id===offboard.id).events.length>=14);
 await db.exec('reset role;set role anon;');await assert.rejects(db.exec('select public.kpi_governance_context()'),/permission denied/);
 }finally{await db.close();}
});
