import assert from 'node:assert/strict';
import test from 'node:test';
import {readdir} from 'node:fs/promises';
import {createHostedDatabase,hostedFixture as f,loginHostedFixture} from './fixtures/hosted-database';
import {validateAiAnswer,requestAiAnswer} from '../src/platform/work/hosted-ai-provider';
import {managementRecord} from '../src/platform/work/hosted-management-contract';
test('management migrations install and deny business access without documented grants',async()=>{
 const names=(await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(n=>/^2026100200(0[3-9]|1[0-9]|2[0-3])00/.test(n)).sort();
 const db=await createHostedDatabase(names.map(n=>'migrations/'+n),[]);
 try{
 await loginHostedFixture(db,f.owner);
 await assert.rejects(db.query("select public.kpi_management_list('FINANCE','KPI','CURRENT',null)"),/Access denied/);
 await assert.rejects(db.query("select public.kpi_operations_snapshot()"),/Technical administrator/);
 await assert.rejects(db.query("select public.kpi_management_create('BUDGET','KPI','CURRENT',null,$1,gen_random_uuid())",[JSON.stringify({title:'Budget fixture',description:'Isolated test',currency:'IDR',amountMinor:100})]),/denied/i);
 assert.equal((await db.query<{ok:boolean}>("select to_regprocedure('public.kpi_ai_draft_commit(uuid,integer,text)') is not null ok")).rows[0].ok,true);
 }finally{await db.close();}
});
test('management workflows enforce evidence, independent approval, budget limits, appeal, handover and confirmed AI writes',async()=>{
 const names=(await readdir(new URL('../supabase/migrations/',import.meta.url))).filter(n=>/^2026100200(0[3-9]|1[0-9]|2[0-3])00/.test(n)).sort();const db=await createHostedDatabase(names.map(n=>'migrations/'+n),[]);
 type R={id:string;version:number;status:string;payload:Record<string,any>};
 const {owner,reviewer,stranger,organization,period}=f;
 const permissions=['WORKSPACE_READ','TASK_READ','TASK_CREATE','MEETING_READ','FINANCE_READ','FINANCE_MANAGE','FINANCE_APPROVE_FINAL','EVALUATION_READ','EVALUATION_WRITE','HANDOVER_READ','HANDOVER_ACCEPT','AI_READ','AI_ACTION_CONFIRM','KNOWLEDGE_READ','KNOWLEDGE_WRITE','NOTIFICATION_READ'];
 async function grant(account:string,permission:string,object:string|null=null){
 await db.exec('reset role;');const authorityAccount=account===owner?reviewer:owner;
 const authority=(await db.query<{id:string}>('insert into governance.access_authorities(account_id,organization_id,period_id,classifications,permissions,mandate_reference,starts_at,expires_at) values($1,$2,$3,$4,$5,\'Isolated test mandate\',now()-interval \'1 day\',now()+interval \'2 days\') returning id',[authorityAccount,organization,period,['TERBATAS','RAHASIA'],[permission]])).rows[0].id;
 const decision=(await db.query<{id:string}>(`insert into governance.access_decisions(authority_id,recipient_account_id,organization_id,period_id,object_id,permission,classification,form_reference,mandate_reference,purpose,information_scope,decision_reference,approved_by_account_id,starts_at,expires_at,review_due_at,implemented_by_account_id,implemented_at) values($1,$2,$3,$4,$5,$6,$7,'Fixture F01','Fixture mandate','Fixture need','Fixture scope','Fixture decision',$8,now()-interval '1 hour',now()+interval '1 day',now()+interval '12 hours',$8,now()) returning id`,[authority,account,organization,period,object,permission,object?'RAHASIA':'TERBATAS',authorityAccount])).rows[0].id;
 await db.query(`insert into identity.permission_grants(account_id,organization_id,period_id,object_id,permission,decision_id,reason,starts_at,expires_at) values($1,$2,$3,$4,$5,$6,'Fixture approved decision',now(),now()+interval '23 hours')`,[account,organization,period,object,permission,decision]);
 }
 async function reserve(kind:string){await loginHostedFixture(db,owner);const slot=(await db.query<{r:{id:string}}>("select public.kpi_management_reserve($1,'KPI','CURRENT',null) r",[kind])).rows[0].r.id;for(const a of [owner,reviewer,stranger])for(const permission of kind==='EVALUATION'?['EVALUATION_READ','EVALUATION_WRITE']:['AI_READ','AI_ACTION_CONFIRM'])await grant(a,permission,slot);await loginHostedFixture(db,owner);return slot;}
 async function create(kind:string,input:Record<string,unknown>,key=crypto.randomUUID()){if(['EVALUATION','AI_DRAFT'].includes(kind))input={...input,reservedId:await reserve(kind)};const result=(await db.query<{r:R}>('select public.kpi_management_create($1,\'KPI\',\'CURRENT\',null,$2,$3) r',[kind,JSON.stringify(input),key])).rows[0].r;managementRecord.parse(result);return result;}
 async function act(r:R,action:string,input:Record<string,unknown>={}){const result=(await db.query<{r:R}>('select public.kpi_management_action($1,$2,$3,$4) r',[r.id,r.version,action,JSON.stringify({note:'Fixture independent action',...input})])).rows[0].r;managementRecord.parse(result);return result;}
 try{
 await db.exec(`insert into org.assignments(account_id,position_id,period_id,starts_on) select '${stranger}',id,'${period}',current_date-1 from org.positions;`);
 for(const a of [owner,reviewer,stranger])for(const p of permissions)await grant(a,p);
 await loginHostedFixture(db,owner);const protectedSlot=(await db.query<{r:{id:string;classification:string}}>("select public.kpi_management_reserve('EVALUATION','KPI','CURRENT',null) r")).rows[0].r;assert.equal(protectedSlot.classification,'RAHASIA');await assert.rejects(db.query("select public.kpi_management_create('EVALUATION','KPI','CURRENT',null,$1,gen_random_uuid())",[JSON.stringify({reservedId:protectedSlot.id,title:'Private assessment',description:'An individual assessment requires object access.',score:80,criteriaReference:'Fixture rubric',subjectAccountId:reviewer})]),/Access denied/);
 await db.exec('reset role;');
 const asset=(await db.query<{id:string}>(`insert into files.managed_assets(organization_id,period_id,owner_account_id,original_name,mime_type,size_bytes,sha256,object_path,request_key,status) values($1,$2,$3,'proof.pdf','application/pdf',100,$4,'isolated-proof',gen_random_uuid(),'AVAILABLE') returning id`,[organization,period,owner,'a'.repeat(64)])).rows[0].id;
 for(const a of [owner,reviewer,stranger])await grant(a,'ASSET_READ',asset);
 await loginHostedFixture(db,owner);
 const input={title:'Approved activity budget',description:'Documented activity allocation',currency:'EGP',amountMinor:10000};const key=crypto.randomUUID();let budget=await create('BUDGET',input,key);assert.equal((await create('BUDGET',input,key)).id,budget.id);await assert.rejects(create('BUDGET',{...input,amountMinor:9000},key),/already used/);
 budget=await act(budget,'SUBMIT');await assert.rejects(act(budget,'APPROVE'),/Independent/);await loginHostedFixture(db,reviewer);budget=await act(budget,'APPROVE');assert.equal(budget.status,'APPROVED');
 await loginHostedFixture(db,owner);let transaction=await create('FINANCE',{...input,title:'Activity supplies reimbursement',amountMinor:7000,budgetId:budget.id});
 await assert.rejects(act(transaction,'SUBMIT'),/evidence/);transaction=await act(transaction,'SUBMIT',{evidenceAssetId:asset});await assert.rejects(act(transaction,'CHECK'),/Independent/);
 await loginHostedFixture(db,reviewer);transaction=await act(transaction,'CHECK');await assert.rejects(act(transaction,'APPROVE'),/Independent/);await loginHostedFixture(db,stranger);transaction=await act(transaction,'APPROVE');assert.equal(transaction.status,'APPROVED');
 await loginHostedFixture(db,owner);transaction=await act(transaction,'RECORD_PAYMENT',{evidenceAssetId:asset,reference:'Fixture receipt 001'});await assert.rejects(act(transaction,'RECONCILE'),/Independent/);await loginHostedFixture(db,reviewer);transaction=await act(transaction,'RECONCILE');assert.equal(transaction.status,'RECONCILED');
 await loginHostedFixture(db,owner);let excess=await create('FINANCE',{...input,title:'Excess allocation attempt',amountMinor:4000,budgetId:budget.id});excess=await act(excess,'SUBMIT',{evidenceAssetId:asset});await loginHostedFixture(db,reviewer);excess=await act(excess,'CHECK');await loginHostedFixture(db,stranger);await assert.rejects(act(excess,'APPROVE'),/Budget exceeded/);
 await loginHostedFixture(db,owner);let evaluation=await create('EVALUATION',{title:'Period performance review',description:'Evidence-based contribution review',score:85,criteriaReference:'Fixture approved rubric',subjectAccountId:reviewer});evaluation=await act(evaluation,'SUBMIT',{evidenceAssetId:asset});await loginHostedFixture(db,reviewer);await assert.rejects(act(evaluation,'APPROVE'),/Independent/);await loginHostedFixture(db,stranger);evaluation=await act(evaluation,'APPROVE');await loginHostedFixture(db,reviewer);evaluation=await act(evaluation,'APPEAL');await loginHostedFixture(db,stranger);evaluation=await act(evaluation,'APPROVE');await loginHostedFixture(db,reviewer);await assert.rejects(act(evaluation,'APPEAL'),/appeal denied/);
 await loginHostedFixture(db,owner);let handover=await create('HANDOVER',{title:'Documented responsibility transfer',description:'Transfer the verified work records',subjectAccountId:reviewer});await assert.rejects(act(handover,'SUBMIT'),/items required/);handover=await act(handover,'ADD_ITEM',{assetId:asset,title:'Activity record'});await assert.rejects(act(handover,'ADD_ITEM',{assetId:asset,title:'Duplicate record'}),/already included/);handover=await act(handover,'SUBMIT');await loginHostedFixture(db,reviewer);await assert.rejects(act(handover,'CLOSE'),/accepted items/);handover=await act(handover,'ACCEPT_ITEM',{itemId:handover.payload.items[0].id});handover=await act(handover,'CLOSE');assert.equal(handover.status,'CLOSED');await assert.rejects(act(handover,'SAVE'),/finalized/);
 await loginHostedFixture(db,owner);let draft=await create('AI_DRAFT',{title:'Prepare activity recap',description:'Prepare a documented recap of the activity for review.',target:'TASK',sources:[]});await assert.rejects(db.query('select public.kpi_ai_draft_commit($1,99,\'Fixture confirm\')',[draft.id]),/changed/);const committed=(await db.query<{r:R}>('select public.kpi_ai_draft_commit($1,$2,\'Fixture confirm\') r',[draft.id,draft.version])).rows[0].r;assert.equal(committed.status,'COMMITTED');assert.equal((await db.query<{r:R}>('select public.kpi_ai_draft_commit($1,$2,\'Fixture confirm\') r',[draft.id,draft.version])).rows[0].r.payload.resultId,committed.payload.resultId);
 draft=await create('AI_DRAFT',{title:'Prepare knowledge recap',description:'A reviewed explanation to be stored as draft knowledge.',target:'KNOWLEDGE',sources:[]});assert.equal((await db.query<{r:R}>('select public.kpi_ai_draft_commit($1,$2,\'Fixture confirm\') r',[draft.id,draft.version])).rows[0].r.status,'COMMITTED');
 const snapshot=(await db.query<{r:{tasks:any[];reviews:any[]}}>("select public.kpi_workspace_snapshot('KPI','CURRENT',null) r")).rows[0].r;assert.equal(snapshot.tasks.length,1);assert.ok(snapshot.reviews.some(r=>r.id===excess.id));
 const source=(await db.query<{r:{id:string}}>("select public.kpi_content_create('KPI','CURRENT','KNOWLEDGE',$1,null) r",[JSON.stringify({idempotencyKey:crypto.randomUUID(),fields:{title:'Verified knowledge source',summary:'Source for the isolated review',body:'A source body with verified scope.',source:'Fixture official source',locale:'id',slug:'fixture-knowledge'}})])).rows[0].r.id;
 let sourced=await create('AI_DRAFT',{title:'Source-based task proposal',description:'Review the selected source and prepare a work note.',target:'TASK',sources:[source]});
 const proposal={reservedId:await reserve('AI_DRAFT'),title:'Reviewed provider proposal',description:'A proposal bound to the exact version of its source.',target:'TASK',sources:[source],sourceVersions:{[source]:1}};
 assert.equal((await db.query<{r:R}>("select public.kpi_ai_proposal_create('KPI','CURRENT',null,$1,gen_random_uuid()) r",[JSON.stringify(proposal)])).rows[0].r.status,'DRAFT');
 await db.exec('reset role;');await db.query('update content.managed_items set version=version+1 where id=$1',[source]);await loginHostedFixture(db,owner);await assert.rejects(db.query('select public.kpi_ai_draft_commit($1,$2,\'Fixture confirm\')',[sourced.id,sourced.version]),/Source version changed/);
 await assert.rejects(db.query("select public.kpi_ai_proposal_create('KPI','CURRENT',null,$1,gen_random_uuid())",[JSON.stringify(proposal)]),/Source version changed/);
 sourced=await act(sourced,'SAVE',{title:'Reviewed source-based proposal',description:'The updated source has been reviewed before confirmation.'});
 await db.exec('reset role;');await db.query("update management.records set payload=jsonb_set(payload,'{previewExpiresAt}',to_jsonb((now()-interval '1 hour')::text)) where id=$1",[sourced.id]);await loginHostedFixture(db,owner);await assert.rejects(db.query('select public.kpi_ai_draft_commit($1,$2,\'Fixture confirm\')',[sourced.id,sourced.version]),/Preview expired/);
 await db.exec('reset role;');await db.query("update governance.access_decisions set suspended_at=now() where recipient_account_id=$1 and permission='KNOWLEDGE_READ'",[owner]);await loginHostedFixture(db,owner);const drafts=(await db.query<{r:R[]}>("select public.kpi_management_list('AI_DRAFT','KPI','CURRENT',null) r")).rows[0].r;assert.equal(drafts.some(r=>r.id===sourced.id),false);await assert.rejects(db.query('select public.kpi_ai_draft_commit($1,$2,\'Fixture confirm\')',[sourced.id,sourced.version]),/denied/);
 for(let i=0;i<8;i++)assert.equal((await db.query<{ok:boolean}>("select public.kpi_ai_consume_quota('KPI','CURRENT',null) ok")).rows[0].ok,true);assert.equal((await db.query<{ok:boolean}>("select public.kpi_ai_consume_quota('KPI','CURRENT',null) ok")).rows[0].ok,false);
 const inbox=(await db.query<{r:{href:string}[]}>('select public.kpi_notifications_list() r')).rows[0].r;assert.ok(inbox.some(n=>n.href==='/portal/keuangan'));assert.ok(inbox.some(n=>n.href==='/portal/handover'));
 await db.exec('reset role;');await db.query("update governance.access_decisions set suspended_at=now() where recipient_account_id=$1 and permission='FINANCE_READ'",[owner]);await loginHostedFixture(db,owner);await assert.rejects(db.query("select public.kpi_management_list('FINANCE','KPI','CURRENT',null)"),/Access denied/);
 await db.exec('reset role;');await db.exec(`insert into identity.roles(code,name) values('ADMIN_SISTEM','Admin');insert into identity.account_roles(account_id,role_id) select '${stranger}',id from identity.roles where code='ADMIN_SISTEM';insert into identity.system_administrators(account_id,approved_reason) values('${stranger}','Isolated fixture');`);await loginHostedFixture(db,stranger);const ops=(await db.query<{r:any}>('select public.kpi_operations_snapshot() r')).rows[0].r;assert.equal(ops.modules.management,true);assert.equal(ops.audit.some((e:any)=>e.metadata||e.payload),false);
 await db.exec('reset role;set role anon;');await assert.rejects(db.query('select * from management.records'),/permission denied/);await assert.rejects(db.query('select public.kpi_operations_snapshot()'),/permission denied/);
 }finally{await db.close();}
});
test('AI provider rejects invented citations and insecure endpoints',async()=>{
 const source=crypto.randomUUID();const response={answer:'Verified answer',citations:[source],draft:null};assert.equal(validateAiAnswer(response,[source]).answer,'Verified answer');assert.throws(()=>validateAiAnswer(response,[]),/citation/);
 let calls=0;const transport:typeof fetch=async()=>{calls++;return new Response(JSON.stringify(response));};await assert.rejects(requestAiAnswer('http://provider.invalid','token','model','question',[],[source],transport),/endpoint/);assert.equal(calls,0);assert.equal((await requestAiAnswer('https://provider.invalid','token','model','question',[],[source],transport)).answer,'Verified answer');assert.equal(calls,1);
});
