"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {permissions} from "@/platform/authorization/permission-catalog";
import {governanceContextSchema,type GovernanceContext,type GovernanceRecord} from "@/platform/governance/contract";
type Field={key:string;label:string;type?:"text"|"textarea"|"date"|"select"|"multi"|"checkbox";options?:[string,string][];optional?:boolean;value?:string;help?:string};
type Values=Record<string,string|boolean|string[]>;
const status:Record<string,string>={SUBMITTED:"Menunggu keputusan",DRAFT:"Sedang disiapkan",APPROVED:"Disetujui",PARTIAL:"Disetujui sebagian",DENIED:"Ditolak",IMPLEMENTED:"Telah dilaksanakan",COMPLETED:"Selesai",CLOSED:"Ditutup",SECURITY:"Pengamanan",RECOVERY:"Pemulihan",INVESTIGATION:"Pemeriksaan",MONITORING:"Pemantauan",ACTIVE:"Aktif",SCHEDULED:"Belum mulai",INACTIVE:"Tidak aktif",EXPIRED:"Berakhir",REVOKED:"Dicabut",SUSPENDED:"Ditangguhkan"};
const checks:[string,string][]=[["basis","Dasar perubahan tercatat"],["inventory","Akun, folder, grup, dan tautan diperiksa"],["access","Akses dicabut atau disesuaikan"],["documents","Dokumen diserahkan"],["responsibilities","Tanggung jawab diserahterimakan"],["accounts","Pengelolaan akun dialihkan"],["evidence","Arsip dan bukti terlindungi"],["copies","Salinan pribadi ditertibkan"],["transition","Akses transisi memiliki batas"],["confidentiality","Kerahasiaan setelah tugas ditegaskan"]];
const categories:[string,string][]=[["INTERNAL","Internal"],["TERBATAS","Terbatas"],["RAHASIA","Rahasia"]];
const permissionOptions: [string,string][]=permissions.map(p=>[p,p.replaceAll("_"," · ")]);
const titles:Record<GovernanceRecord["kind"],string>={ACCESS:"F01 · Permohonan akses",INCIDENT:"F03–F04 · Insiden kerahasiaan",OFFBOARD:"F05 · Pengakhiran akses",CLASSIFICATION:"Klasifikasi & perlindungan bukti"};
const date=(value:unknown)=>typeof value==="string"?new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—";
const text=(value:unknown)=>typeof value==="string"?value:"";
function InputForm({fields,label,busy,onSubmit}:{fields:Field[];label:string;busy:boolean;onSubmit:(v:Values)=>Promise<boolean>}):React.JSX.Element{
 const [values,setValues]=useState<Values>(()=>Object.fromEntries(fields.filter(f=>f.value!==undefined).map(f=>[f.key,f.value!])));
 const change=(key:string,value:Values[string])=>setValues(v=>({...v,[key]:value}));
 return <form className="governance-form" onSubmit={e=>{e.preventDefault();void onSubmit(values).then(ok=>{if(ok){setValues(Object.fromEntries(fields.filter(f=>f.value!==undefined).map(f=>[f.key,f.value!])));}});}}><fieldset disabled={busy}><div className="governance-fields">{fields.map(f=><label key={f.key} className={f.type==="textarea"||f.type==="multi"?"governance-wide":""}><span>{f.label}{f.optional?" (opsional)":""}</span>{f.type==="checkbox"?<input type="checkbox" checked={Boolean(values[f.key])} onChange={e=>change(f.key,e.target.checked)}/>:f.type==="textarea"?<textarea required={!f.optional} maxLength={f.key==="description"?6000:2000} rows={3} value={text(values[f.key])} onChange={e=>change(f.key,e.target.value)}/>:f.type==="multi"?<select multiple required={!f.optional} value={Array.isArray(values[f.key])?values[f.key] as string[]:[]} onChange={e=>change(f.key,Array.from(e.target.selectedOptions,o=>o.value))}>{f.options?.map(([value,name])=><option key={value} value={value}>{name}</option>)}</select>:f.type==="select"?<select required={!f.optional} value={text(values[f.key])} onChange={e=>change(f.key,e.target.value)}><option value="">Pilih {f.label.toLowerCase()}</option>{f.options?.map(([value,name])=><option key={value} value={value}>{name}</option>)}</select>:<input required={!f.optional} type={f.type==="date"?"datetime-local":"text"} maxLength={500} value={text(values[f.key])} onChange={e=>change(f.key,e.target.value)}/>} {f.help?<small>{f.help}</small>:null}</label>)}</div><button className="button button--primary" type="submit">{busy?"Menyimpan…":label}</button></fieldset></form>;
}
export function GovernanceWorkspace({accountId,technicalAdmin}:{accountId:string;technicalAdmin:boolean}):React.JSX.Element{
 const [resourceId,setResourceId]=useState("");
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get("resource")||"";if(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value))setResourceId(value);},[]);
 const [context,setContext]=useState<GovernanceContext|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[tab,setTab]=useState("ACCESS"),[scopeIndex,setScopeIndex]=useState(0),[selectedId,setSelectedId]=useState<string|null>(null);
 const generation=useRef(0),requestKey=useRef<string|null>(null),requestBody=useRef<string|null>(null);
 const reload=useCallback(async()=>{const g=++generation.current;setLoading(true);try{const response=await fetch("/api/v1/work/governance",{cache:"no-store"});if(!response.ok)throw new Error(response.status===401?"Sesi berakhir. Masuk kembali ke portal.":"Tata kelola belum dapat dibaca. Periksa koneksi dan migrasi database.");const result=governanceContextSchema.parse((await response.json()).context);if(g===generation.current)setContext(result);}catch(e){if(g===generation.current){setContext(null);setError(e instanceof Error?e.message:"Gagal membaca data.");}}finally{if(g===generation.current)setLoading(false);}},[]);
 useEffect(()=>{void reload();return()=>{generation.current++;};},[reload]);
 async function send(body:unknown){if(busy)return false;setBusy(true);setError("");setNotice("");try{const response=await fetch("/api/v1/work/governance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw new Error(response.status===409?"Data sudah berubah. Muat ulang sebelum mencoba kembali.":response.status===403?"Tindakan tidak diizinkan. Periksa mandat, konflik, penugasan, dan pemisahan pemberi keputusan.":response.status===400?"Isian atau prasyarat belum lengkap. Periksa tanggal, rujukan, status checklist, dan persetujuan yang diperlukan.":"Data belum tersimpan. Coba lagi dengan isian yang sama.");const result=await response.json();if(result.record)setSelectedId(result.record.id);requestKey.current=null;await reload();setNotice("Tindakan tersimpan dan tercatat dalam riwayat.");return true;}catch(e){setError(e instanceof Error?e.message:"Gagal menyimpan.");return false;}finally{setBusy(false);}}
 function convert(values:Values){return Object.fromEntries(Object.entries(values).map(([key,value])=>[key,(key==="divisionId"&&value==="")?null:key.endsWith("At")&&typeof value==="string"?(value?new Date(value).toISOString():null):value]));}
 const scope=context?.scopes[scopeIndex];
 const accounts: [string,string][]=context?.accounts.map(a=>[a.id,a.name])||[];
 const ownAuthorities=context?.authorities.filter(a=>a.accountId===accountId)||[];
 function can(capability:string,r:GovernanceRecord){return ownAuthorities.some(a=>a.organizationId===r.organizationId&&a.periodId===r.periodId&&(!a.divisionId||a.divisionId===r.divisionId)&&a.classifications.includes(r.classification)&&a.permissions.includes(capability));}
 const current=context?.records.find(r=>r.id===selectedId&&r.kind===tab);
 const reference:Field={key:"reference",label:"Rujukan bukti atau keputusan"};
 const note:Field={key:"note",label:"Catatan dan dasar tindakan",type:"textarea"};
 const fields:Field[]=[{key:"divisionId",label:"ID divisi dalam cakupan",optional:true,help:"Kosongkan untuk cakupan organisasi. Untuk penugasan divisi, gunakan ID divisi resmi."},{key:"formReference",label:"Nomor formulir / rujukan administrasi",help:"Ikuti tata administrasi KPI. Kode F01–F05 bukan nomor surat."}];
 if(tab==="ACCESS")fields.push({key:"classification",label:"Kategori informasi",type:"select",options:categories},{key:"requestType",label:"Jenis permohonan",type:"select",options:[["GRANT","Pemberian"],["CHANGE","Perubahan"],["REVOKE","Pencabutan"],["RESTORE","Pemulihan"]]}, {key:"permissions",label:"Izin yang diminta",type:"multi",options:permissionOptions,help:"Pilih tindakan secara terpisah. Gunakan Ctrl/Cmd untuk beberapa pilihan."},{key:"mandateReference",label:"Dasar penugasan / mandat"},{key:"purpose",label:"Tujuan dan kebutuhan akses",type:"textarea"},{key:"informationScope",label:"Informasi, sistem, dan batas cakupan",type:"textarea"},{key:"startsAt",label:"Mulai akses",type:"date"},{key:"expiresAt",label:"Akhir akses",type:"date"},{key:"endCondition",label:"Kondisi pengakhiran tambahan",optional:true},{key:"objectId",label:"ID objek informasi",optional:true,value:resourceId,help:"Wajib untuk persetujuan akses rahasia. Gunakan UUID objek yang ditunjuk."},{key:"targetDecisionId",label:"ID keputusan sebelumnya",optional:true,help:"Wajib untuk perubahan, pencabutan, atau pemulihan. Tersedia di register F02."});
 if(tab==="INCIDENT")fields.push({key:"incidentType",label:"Jenis insiden",type:"select",options:[["MIS_SEND","Salah kirim"],["LOST","Kehilangan"],["UNAUTH_ACCESS","Akses tanpa izin"],["ACCOUNT_TAKEOVER","Akun diambil alih"],["OTHER","Lainnya"]]},{key:"description",label:"Uraian kejadian yang diketahui",type:"textarea"},{key:"system",label:"Sistem atau informasi terdampak",optional:true},{key:"affectedClassification",label:"Kategori informasi terdampak",type:"select",options:[["UNKNOWN","Belum diketahui"],["TERBUKA","Terbuka"],...categories]},{key:"eventAt",label:"Waktu kejadian",type:"date",optional:true},{key:"discoveredAt",label:"Waktu diketahui",type:"date",optional:true},{key:"impact",label:"Dampak yang diketahui",type:"textarea",optional:true},{key:"initialAction",label:"Tindakan awal",type:"textarea",optional:true},{key:"notifiedParties",label:"Pihak yang telah diberi tahu",optional:true},{key:"evidenceReference",label:"Rujukan bukti privat",optional:true},{key:"unknownDetails",label:"Informasi yang masih perlu dilengkapi",type:"textarea",optional:true},{key:"contact",label:"Kontak terbatas pelapor",optional:true},{key:"personnelConcern",label:"Perlu jalur BPI / terdapat konflik penerima laporan",type:"checkbox",optional:true});
 if(tab==="OFFBOARD")fields.push({key:"classification",label:"Kategori formulir",type:"select",options:categories},{key:"subjectAccountId",label:"Personel yang mengakhiri tugas",type:"select",options:accounts,value:accountId},{key:"function",label:"Jabatan atau fungsi"},{key:"basis",label:"Dasar perubahan tugas",type:"textarea"},{key:"effectiveAt",label:"Tanggal dan waktu berlaku",type:"date"},{key:"successorAccountId",label:"Penerima serah terima",type:"select",options:accounts},{key:"verifierAccountId",label:"Petugas verifikasi berwenang",type:"select",options:accounts.filter(([id])=>context?.authorities.some(a=>a.accountId===id&&a.periodId===scope?.periodId&&a.permissions.includes("SOP_OFFBOARD_VERIFY")))},{key:"revokeTechnical",label:"Pengakhiran mandat admin teknis global (memerlukan kewenangan khusus)",type:"checkbox",optional:true});
 if(tab==="CLASSIFICATION")fields.push({key:"objectId",label:"Objek informasi",type:"select",options:context?.resources.filter(r=>r.periodId===scope?.periodId).map(r=>[r.id,`${r.kind} · ${r.classification} · ${r.id}${r.held?" · Bukti dilindungi":""}`])||[]},{key:"mode",label:"Jenis tindakan",type:"select",options:[["CLASSIFY","Penetapan / perubahan klasifikasi"],["HOLD","Lindungi bukti dari penghapusan"],["RELEASE","Lepaskan perlindungan bukti"]]},{key:"newClassification",label:"Kategori yang diusulkan",type:"select",options:[["TERBUKA","Terbuka"],...categories],help:"Tidak menerbitkan dokumen otomatis. Penurunan kategori memerlukan mandat khusus."},{key:"reason",label:"Alasan",type:"textarea"},{key:"basis",label:"Dasar tertulis"});
 const actionForms:Array<{action:string;label:string;fields:Field[]}>=[];
 if(current&&!['DENIED','CLOSED','COMPLETED'].includes(current.status)){
 const r=current,p=r.payload;
 if(r.kind==="ACCESS"){
  const eligible=ownAuthorities.filter(a=>a.organizationId===r.organizationId&&a.periodId===r.periodId&&a.classifications.includes(r.classification)&&Array.isArray(p.permissions)&&p.permissions.some(v=>typeof v==="string"&&a.permissions.includes(v)));
  if(r.status==="SUBMITTED"&&r.creatorAccountId!==accountId&&eligible.length)actionForms.push({action:"DECIDE",label:"Catat keputusan",fields:[{key:"authorityId",label:"Mandat pemberi keputusan",type:"select",options:eligible.map(a=>[a.id,a.mandateReference||a.id])},{key:"outcome",label:"Keputusan",type:"select",options:[["APPROVED","Disetujui"],["PARTIAL","Disetujui sebagian"],["DENIED","Ditolak"]]},{key:"approvedPermissions",label:"Izin yang disetujui",type:"multi",optional:true,options:permissionOptions.filter(([v])=>Array.isArray(p.permissions)&&p.permissions.includes(v))},{key:"needFinding",label:"Hasil pemeriksaan kebutuhan",type:"textarea"},note,reference]});
  if(technicalAdmin&&r.creatorAccountId!==accountId&&['APPROVED','PARTIAL'].includes(r.status))actionForms.push({action:"IMPLEMENT",label:"Laksanakan keputusan akses",fields:[reference]});
 }
 if(r.kind==="INCIDENT"){
  const cap=p.personnelConcern?"SOP_BPI_REVIEW":"SOP_INCIDENT_HANDLE";
  if(r.creatorAccountId!==accountId&&can(cap,r))actionForms.push({action:"ASSIGN",label:"Tetapkan PIC penanganan",fields:[{key:"handlerAccountId",label:"PIC dengan mandat sesuai",type:"select",options:accounts.filter(([id])=>id!==r.creatorAccountId&&context?.authorities.some(a=>a.accountId===id&&a.periodId===r.periodId&&a.permissions.includes(cap)&&a.classifications.includes(r.classification)))},note,reference]});
  if(r.handlerAccountId===accountId&&can(cap,r)){
   actionForms.push({action:"ACTION",label:"Catat tindakan penanganan",fields:[{key:"phase",label:"Tahap",type:"select",options:[["SECURITY","Pengamanan"],["RECOVERY","Pemulihan"],["INVESTIGATION","Pemeriksaan"],["MONITORING","Pemantauan"]]},note,reference,{key:"residualRisk",label:"Risiko yang tersisa",type:"textarea"}]},{action:"CORRECTION",label:"Tambah perbaikan",fields:[note,{key:"picAccountId",label:"PIC",type:"select",options:accounts},{key:"dueAt",label:"Target penyelesaian",type:"date"}]},{action:"REQUEST_RECOVERY",label:"Ajukan pemulihan untuk diperiksa",fields:[{key:"reviewerAccountId",label:"Pemberi persetujuan independen",type:"select",options:accounts.filter(([id])=>id!==r.creatorAccountId&&id!==r.handlerAccountId&&context?.authorities.some(a=>a.accountId===id&&a.periodId===r.periodId&&a.permissions.includes("SOP_INCIDENT_APPROVE")))},reference,{key:"residualRisk",label:"Risiko yang tersisa",type:"textarea"}]});
   if(p.personnelConcern)actionForms.push({action:"BPI_RESULT",label:"Catat rujukan hasil BPI",fields:[reference]});
  }
  if((r.handlerAccountId===accountId&&can(cap,r))||(r.reviewerAccountId===accountId&&can("SOP_INCIDENT_APPROVE",r)))actionForms.push({action:"VERIFY_CORRECTION",label:"Verifikasi perbaikan",fields:[{key:"entryId",label:"Perbaikan",type:"select",options:arrayObjects(p.corrections).filter(e=>!e.verifiedAt&&e.picAccountId!==accountId).map(e=>[text(e.id),text(e.note)])},reference]});
  if(r.reviewerAccountId===accountId&&can("SOP_INCIDENT_APPROVE",r))actionForms.push({action:"NOTICE_DECISION",label:"Catat keputusan pemberitahuan",fields:[{key:"outcome",label:"Pemberitahuan pihak terdampak",type:"select",options:[["REQUIRED","Diperlukan"],["NOT_REQUIRED","Tidak diperlukan"],["PENDING","Masih dinilai"]]},note,reference]},{action:"APPROVE_RECOVERY",label:"Setujui pemulihan",fields:[reference]},{action:"CLOSE",label:"Tutup insiden teknis",fields:[reference,note]});
 }
 if(r.kind==="OFFBOARD"){
  if(r.status==="DRAFT"&&(r.creatorAccountId===accountId||can("SOP_OFFBOARD_MANAGE",r)))actionForms.push({action:"CHECK",label:"Simpan pemeriksaan checklist",fields:[{key:"check",label:"Pemeriksaan",type:"select",options:checks},{key:"checkStatus",label:"Hasil",type:"select",options:[["DONE","Selesai"],["PENDING","Belum selesai"],["NA","Tidak berlaku (sertakan alasan)"]]},note]},{action:"DETAIL",label:"Catat rincian serah terima",fields:[note,reference]},{action:"EXCEPTION",label:"Catat pekerjaan yang masih tersisa",fields:[note,{key:"picAccountId",label:"PIC",type:"select",options:accounts},{key:"dueAt",label:"Batas waktu",type:"date"},reference]},{action:"TRANSITION",label:"Catat akses transisi yang disetujui",fields:[{key:"decisionIds",label:"Keputusan akses transisi",type:"multi",options:context?.register.filter(d=>d.recipientAccountId===p.subjectAccountId).map(d=>[text(d.id),`${text(d.permission)} · ${text(d.formReference)}`])||[]},{key:"expiresAt",label:"Akhir transisi",type:"date"},{key:"revokerAccountId",label:"ID petugas teknis pencabutan",help:"Gunakan UUID akun admin teknis yang ditugaskan."},reference]},{action:"SUBMIT",label:"Ajukan verifikasi serah terima",fields:[]});
  if(p.successorAccountId===accountId&&!p.receivedAt&&current.status==="SUBMITTED")actionForms.push({action:"RECEIVE",label:"Konfirmasi penerimaan serah terima",fields:[reference]});
  if(r.reviewerAccountId===accountId&&can("SOP_OFFBOARD_VERIFY",r)){
   if(r.status==="SUBMITTED")actionForms.push({action:"APPROVE",label:"Sahkan pemeriksaan pengakhiran akses",fields:[reference]});
   if(arrayObjects(p.exceptions).some(e=>!e.verifiedAt))actionForms.push({action:"VERIFY_EXCEPTION",label:"Verifikasi pekerjaan tersisa",fields:[{key:"entryId",label:"Pekerjaan",type:"select",options:arrayObjects(p.exceptions).filter(e=>!e.verifiedAt&&e.picAccountId!==accountId).map(e=>[text(e.id),text(e.note)])},reference]});
   if(r.status==="IMPLEMENTED")actionForms.push({action:"CLOSE",label:"Selesaikan verifikasi serah terima",fields:[reference]});
  }
  if(technicalAdmin&&p.subjectAccountId!==accountId&&r.status==="APPROVED")actionForms.push({action:"IMPLEMENT",label:"Laksanakan pencabutan akses",fields:[reference]});
 }
 if(r.kind==="CLASSIFICATION"&&r.creatorAccountId!==accountId&&can(p.mode==="HOLD"?"INFORMATION_HOLD":p.mode==="RELEASE"?"INFORMATION_HOLD_RELEASE":"INFORMATION_CLASSIFY",r))actionForms.push({action:"APPROVE",label:"Setujui tindakan klasifikasi / bukti",fields:[reference,note]},{action:"DENY",label:"Tolak usulan",fields:[reference,note]});
 }
 return <div className="hosted-task-workspace governance-workspace">
 <nav className="governance-tabs" aria-label="Alur tata kelola">{[["ACCESS","F01 · Permohonan"],["REGISTER","F02 · Register & review"],["INCIDENT","F03–F04 · Insiden"],["OFFBOARD","F05 · Serah terima"],["CLASSIFICATION","Klasifikasi & bukti"]].map(([key,label])=><button key={key} type="button" className="button button--quiet" aria-pressed={tab===key} onClick={()=>{setTab(key);setSelectedId(null);requestKey.current=null;setNotice("");}}>{label}</button>)}</nav>
 {error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}
 {loading?<p role="status">Membaca tata kelola…</p>:null}
 {context?<><section className="portal-form-card"><label>Organisasi dan periode<select value={scopeIndex} disabled={busy} onChange={e=>{setScopeIndex(Number(e.target.value));setSelectedId(null);requestKey.current=null;}}>{context.scopes.map((s,i)=><option key={s.periodId} value={i}>{s.organizationCode} · {s.periodCode} · {s.status}</option>)}</select></label>{!scope?<p>Belum ada cakupan penugasan yang dapat dipilih. Hubungi pengelola untuk penugasan resmi.</p>:scope.status!=="ACTIVE"?<p>Periode belum aktif. Pengajuan tata kelola dapat dicatat sesuai mandat; akses pekerjaan tetap mengikuti tanggal dan status periode resmi.</p>:null}<p>Jangan masukkan kata sandi, token, atau isi bukti sensitif. Catat rujukan arsip privat. Wewenang keputusan berasal dari mandat tertulis yang terdaftar.</p>{!ownAuthorities.length?<p>Belum ada mandat pemberi keputusan untuk akun Anda. Pengajuan sendiri tetap tersedia dalam cakupan yang diperbolehkan.</p>:null}</section>
 {tab==="REGISTER"?<Register context={context} accountId={accountId} busy={busy} send={send}/>:<>
 {scope?<details className="portal-form-card"><summary>Buat {titles[tab as GovernanceRecord["kind"]]}</summary>{tab==="INCIDENT"?<p>Laporan awal boleh belum lengkap. Waktu pelaporan dicatat server; laporan tidak menetapkan kesalahan personel.</p>:null}<InputForm key={`${tab}-${scope.periodId}-${resourceId}`} fields={fields} label="Simpan pengajuan" busy={busy} onSubmit={v=>{const input={...convert(v),kind:tab,organizationId:scope.organizationId,periodId:scope.periodId,classification:tab==="INCIDENT"?"RAHASIA":v.classification||"INTERNAL",objectId:v.objectId||undefined,targetDecisionId:v.targetDecisionId||undefined};const fingerprint=JSON.stringify(input);if(!requestKey.current||requestBody.current!==fingerprint){requestKey.current=crypto.randomUUID();requestBody.current=fingerprint;}return send({operation:"CREATE",requestKey:requestKey.current,input});}}/></details>:null}
 <div className="governance-columns"><section className="portal-form-card"><h2>Pengajuan terkait akun saya</h2><ul className="hosted-task-list">{context.records.filter(r=>r.kind===tab&&(!scope||r.periodId===scope.periodId)).map(r=><li key={r.id}><button type="button" className="hosted-task-list__row" aria-pressed={r.id===current?.id} onClick={()=>setSelectedId(r.id)}><span><strong>{text(r.payload.formReference)||r.id}</strong><small>{status[r.status]||r.status} · {r.classification}</small><small>{date(r.updatedAt)}</small></span></button></li>)}</ul>{!context.records.some(r=>r.kind===tab&&(!scope||r.periodId===scope.periodId))?<p>Belum ada pengajuan dalam daftar ini.</p>:null}</section>
 <section className="portal-form-card"><h2>{current?text(current.payload.formReference):"Detail dan tindakan"}</h2>{current?<><p>{status[current.status]||current.status} · Versi {current.version}</p>{!current.canRead?<p>Anda melihat metadata yang diperlukan untuk tugas. Isi terbatas hanya tersedia bagi personel yang berwenang.</p>:null}<RecordDetail record={current}/>{actionForms.map(a=><details key={a.action} className="governance-action"><summary>{a.label}</summary><InputForm key={`${current.id}-${current.version}-${a.action}`} fields={a.fields} label={a.label} busy={busy} onSubmit={v=>send({operation:"ACTION",input:{id:current.id,expectedVersion:current.version,action:a.action,input:convert(v)}})}/></details>)}{!actionForms.length?<p>Tidak ada tindakan lanjutan yang tersedia untuk status dan kewenangan akun ini.</p>:null}{current.canRead?<details><summary>Riwayat tindakan ({current.events.length})</summary><ol className="governance-history">{current.events.map(e=><li key={e.id}><strong>{e.action.replaceAll("_"," ")}</strong><p>{e.note}</p>{e.reference?<p>Rujukan: {e.reference}</p>:null}<small>{date(e.at)} · Versi {e.version}</small></li>)}</ol></details>:null}</>:<p>Pilih pengajuan untuk melihat detail, riwayat, dan tindakan yang tersedia.</p>}</section></div>
 </>}
 <button className="button button--quiet" type="button" disabled={busy||loading} onClick={()=>{setError("");void reload();}}>Muat ulang data</button>
 </>:null}
 </div>;
}
function arrayObjects(v:unknown):Record<string,unknown>[]{return Array.isArray(v)?v.filter(e=>typeof e==="object"&&e!==null) as Record<string,unknown>[]:[];}
function RecordDetail({record:r}:{record:GovernanceRecord}):React.JSX.Element{
 const p=r.payload,rows:[string,string][]=[];
 for(const [key,label] of [["requestType","Jenis permohonan"],["purpose","Tujuan"],["informationScope","Cakupan"],["mandateReference","Dasar mandat"],["description","Laporan awal"],["system","Sistem terdampak"],["impact","Dampak yang diketahui"],["unknownDetails","Perlu dilengkapi"],["initialAction","Tindakan awal"],["decisionNote","Catatan keputusan"],["decisionReference","Bukti keputusan"],["basis","Dasar tertulis"],["reason","Alasan"],["objectId","Objek informasi"],["residualRisk","Risiko tersisa"],["noticeDecision","Keputusan pemberitahuan"],["bpiStatus","Pemeriksaan BPI"],["function","Fungsi"],["fromClassification","Kategori sebelumnya"],["newClassification","Usulan kategori"]])if(text(p[key]))rows.push([label,text(p[key])]);
 if(Array.isArray(p.permissions))rows.push(["Izin diminta",p.permissions.join(", ")]);if(Array.isArray(p.approvedPermissions))rows.push(["Izin disetujui",p.approvedPermissions.join(", ")]);
 for(const [key,label] of [["startsAt","Mulai"],["expiresAt","Berakhir"],["effectiveAt","Pengakhiran berlaku"],["transitionExpiresAt","Akhir transisi"],["recoveryApprovedAt","Pemulihan disetujui"]])if(p[key])rows.push([label,date(p[key])]);
 const checklist=p.checklist&&typeof p.checklist==="object"?p.checklist as Record<string,Record<string,unknown>>:null;
 return <><dl className="governance-detail">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{r.kind==="INCIDENT"?<p>Penutupan insiden teknis tidak otomatis menutup pemeriksaan pelanggaran personel.</p>:null}{checklist?<ul className="governance-checklist">{checks.map(([key,label])=><li key={key}><strong>{label}</strong><span>{checklist[key]?.status==="DONE"?"Selesai":checklist[key]?.status==="NA"?"Tidak berlaku":"Belum selesai"}</span><p>{text(checklist[key]?.note)}</p></li>)}</ul>:null}{[...arrayObjects(p.corrections),...arrayObjects(p.exceptions),...arrayObjects(p.details)].map((e,i)=><div key={text(e.id)||i} className="governance-note"><p>{text(e.note)}</p>{e.id?<small>ID: {text(e.id)}</small>:null}{e.dueAt?<p>Target: {date(e.dueAt)}</p>:null}<p>{e.verifiedAt?`Diverifikasi ${date(e.verifiedAt)}`:e.dueAt?"Menunggu verifikasi":"Rincian tercatat"}</p></div>)}</>;
}
function Register({context,accountId,busy,send}:{context:GovernanceContext;accountId:string;busy:boolean;send:(body:unknown)=>Promise<boolean>}):React.JSX.Element{
 const accountOptions:[string,string][]=context.accounts.map(a=>[a.id,a.name]);
 const reference:Field={key:"reference",label:"Rujukan verifikasi / keputusan"};
 const permitted=(d:Record<string,unknown>,cap:string)=>d.recipientAccountId!==accountId&&context.authorities.some(a=>a.accountId===accountId&&a.organizationId===d.organizationId&&a.periodId===d.periodId&&a.classifications.includes(text(d.classification))&&a.permissions.includes(cap));
 return <section className="portal-form-card"><h2>Register akses dan peninjauan</h2><p>Tinjau paling lambat setiap tiga bulan serta ketika tugas berubah, terjadi insiden, atau ditemukan konflik. Pencabutan dan pemulihan memakai permohonan F01 baru.</p>{context.register.length?context.register.map(d=><article className="governance-register" key={text(d.id)}><h3>{text(d.formReference)} · {text(d.permission)}</h3><p>{status[text(d.status)]||text(d.status)} · {text(d.classification)}{d.reviewOverdue?" · Peninjauan sudah jatuh tempo":""}</p><p>{text(d.informationScope)}</p><p>Berlaku sampai {date(d.expiresAt)} · Review paling lambat {date(d.reviewDueAt)}</p><small>ID keputusan: {text(d.id)}</small>{permitted(d,"SOP_ACCESS_REVIEW")?<details><summary>Catat peninjauan F02</summary><InputForm key={`review-${text(d.id)}`} label="Simpan peninjauan" busy={busy} fields={[{key:"trigger",label:"Dasar peninjauan",type:"select",options:[["PERIODIC","Berkala"],["ASSIGNMENT_CHANGE","Perubahan tugas"],["OFFBOARD","Pergantian pengurus"],["CONFLICT","Konflik kepentingan"],["INCIDENT","Insiden"]]},{key:"finding",label:"Temuan",type:"textarea"},{key:"followUp",label:"Tindak lanjut",type:"textarea"},{key:"picAccountId",label:"PIC tindak lanjut",type:"select",options:accountOptions},{key:"dueAt",label:"Target penyelesaian",type:"date"}]} onSubmit={v=>send({operation:"REVIEW",input:{action:"RECORD",decisionId:d.id,...Object.fromEntries(Object.entries(v).map(([k,value])=>[k,k==="dueAt"?new Date(text(value)).toISOString():value]))}})}/></details>:null}{context.reviews.filter(v=>v.decisionId===d.id).map(v=><div key={text(v.id)} className="governance-note"><p>{text(v.finding)}</p><p>{text(v.followUp)} · Target {date(v.dueAt)}</p><p>{text(v.suspensionReason)}{v.suspensionReference?` · Rujukan: ${text(v.suspensionReference)}`:""}</p><p>{v.verifiedAt?`Diverifikasi ${date(v.verifiedAt)}`:"Menunggu verifikasi tindak lanjut"}</p>{!v.verifiedAt&&v.picAccountId!==accountId&&permitted(d,"SOP_ACCESS_REVIEW")?<InputForm fields={[reference]} label="Verifikasi tindak lanjut" busy={busy} onSubmit={values=>send({operation:"REVIEW",input:{action:"VERIFY",reviewId:v.id,...values}})}/>:null}{permitted(d,"SOP_ACCESS_SUSPEND")&&d.status!=="SUSPENDED"&&d.status!=="REVOKED"?<details><summary>Penangguhan untuk pengamanan</summary><p>Penangguhan bukan sanksi atau keputusan bersalah. Pemulihan memerlukan keputusan baru.</p><InputForm fields={[{key:"finding",label:"Alasan pengamanan",type:"textarea"},reference]} label="Catat dan tangguhkan akses" busy={busy} onSubmit={values=>send({operation:"REVIEW",input:{action:"SUSPEND",reviewId:v.id,...values}})}/></details>:null}</div>)}</article>):<p>Belum ada keputusan akses terkait akun Anda.</p>}</section>;
}
