"use client";
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {adminDirectorySchema,type AdminDirectory} from '@/platform/identity/hosted-admin-contract';
import {permissions} from '@/platform/authorization/permission-catalog';
import {portalJson,scopeQuery} from '@/components/portal/hosted-management-workspace';
const rosterSchema=z.object({accounts:z.array(z.object({id:z.string(),name:z.string(),email:z.string(),status:z.string()})),divisions:z.array(z.object({id:z.string(),code:z.string(),name:z.string()})),positions:z.array(z.object({id:z.string(),code:z.string(),name:z.string(),divisionId:z.string().nullable()})),assignments:z.array(z.object({id:z.string(),accountId:z.string(),positionId:z.string(),startsOn:z.string(),endsOn:z.string().nullable(),version:z.number(),decisionReference:z.string().nullable()})),mandates:z.array(z.object({id:z.string(),accountId:z.string(),reference:z.string(),permissions:z.array(z.string()),classifications:z.array(z.string()),status:z.string(),version:z.number(),note:z.string()}))});
const intakeSchema=z.object({routing:z.object({secretaryAccountId:z.string(),iodDivisionId:z.string(),enabled:z.boolean()}).nullable(),ready:z.boolean(),templates:z.array(z.object({id:z.string(),kind:z.string(),title:z.string(),instructions:z.string(),fields:z.array(z.object({key:z.string(),label:z.string(),required:z.boolean()})),reference:z.string(),status:z.string(),version:z.number(),createdBy:z.string()}))});
const commands={DIVISION:'Divisi / subbidang',POSITION:'Jabatan',ASSIGN:'Penugasan pengurus',MANDATE_PROPOSE:'Ajukan pencatatan mandat',ROUTING:'Penerimaan pengaduan',TEMPLATE_CREATE:'Template formulir'};
export function HostedRosterAdministration(){
 const [directory,setDirectory]=useState<AdminDirectory>({organizations:[],periods:[]}),[periodId,setPeriodId]=useState(''),[roster,setRoster]=useState<z.infer<typeof rosterSchema>|null>(null),[intake,setIntake]=useState<z.infer<typeof intakeSchema>|null>(null),[command,setCommand]=useState<keyof typeof commands>('DIVISION'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[selectedPermissions,setSelectedPermissions]=useState<string[]>([]);const generation=useRef(0);
 const period=directory.periods.find(p=>p.id===periodId),organization=directory.organizations.find(o=>o.id===period?.organizationId);const scope=organization&&period?{organizationCode:organization.code,periodCode:period.code,divisionCode:null}:null;
 useEffect(()=>{let current=true;void portalJson('/api/v1/auth/administration').then(r=>{if(current){const d=adminDirectorySchema.parse(r);setDirectory(d);setPeriodId(d.periods[0]?.id||'');}}).catch(e=>{if(current)setError((e as Error).message);});return()=>{current=false;};},[]);
 async function reload(){if(!scope)return;const current=++generation.current;setRoster(null);setIntake(null);try{const [r,i]=await Promise.all([portalJson('/api/v1/work/administration?'+scopeQuery(scope)),portalJson('/api/v1/work/administration?mode=INTAKE&'+scopeQuery(scope))]);if(current===generation.current){setRoster(rosterSchema.parse(r.data));setIntake(intakeSchema.parse(i.data));}}catch(e){if(current===generation.current)setError((e as Error).message);}}
 useEffect(()=>{setError('');setNotice('');void reload();return()=>{generation.current++;};},[periodId]);
 async function run(action:string,input:object){if(!scope||busy)return;setBusy(true);setError('');setNotice('');try{await portalJson('/api/v1/work/administration',{...scope,command:action,input:{note,...input}});await reload();setNotice('Perubahan administrasi tersimpan. Penugasan tidak otomatis memberikan izin membaca isi pekerjaan.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),text=(k:string)=>String(f.get(k)||'');let input:object;
  if(command==='DIVISION'||command==='POSITION')input={code:text('code'),name:text('name'),...(command==='POSITION'?{divisionId:text('divisionId')||null}:{})};
  else if(command==='ASSIGN'){const existing=roster?.assignments.find(a=>a.accountId===text('accountId')&&a.positionId===text('positionId'));input={accountId:text('accountId'),positionId:text('positionId'),startsOn:text('startsOn'),endsOn:text('endsOn'),decisionReference:text('reference'),...(existing?{expectedVersion:existing.version}:{})};}
  else if(command==='MANDATE_PROPOSE')input={accountId:text('accountId'),divisionId:text('divisionId')||null,reference:text('reference'),permissions:selectedPermissions,classifications:f.getAll('classifications').map(String),startsAt:new Date(text('startsAt')).toISOString(),expiresAt:new Date(text('expiresAt')).toISOString()};
  else if(command==='ROUTING')input={secretaryAccountId:text('accountId'),iodDivisionId:text('divisionId'),enabled:f.get('enabled')==='on'};
  else input={kind:text('kind'),title:text('title'),instructions:text('instructions'),reference:text('reference'),fields:text('questions').split('\n').map(l=>l.trim()).filter(Boolean).map((label,i)=>({key:`question_${i+1}`,label,required:true}))};
  await run(command,input);
 }
 const accountSelect=<label>Akun pengurus aktif<select name="accountId" required disabled={busy}><option value="">Pilih akun</option>{roster?.accounts.filter(a=>a.status==='ACTIVE').map(a=><option key={a.id} value={a.id}>{a.name} · {a.email}</option>)}</select></label>;
 const divisionSelect=<label>Divisi / subbidang<select name="divisionId" required={command==='ROUTING'} disabled={busy}><option value="">{command==='ROUTING'?'Pilih divisi IOD resmi':'Lingkup organisasi'}</option>{roster?.divisions.map(d=><option key={d.id} value={d.id}>{d.name} · {d.code}</option>)}</select></label>;
 return <section className="portal-form-card"><h2>Pengurus, unit kerja, mandat, dan penerimaan</h2><label>Periode resmi<select value={periodId} disabled={busy} onChange={e=>setPeriodId(e.target.value)}><option value="">Pilih periode</option>{directory.periods.map(p=><option key={p.id} value={p.id}>{p.code} · {p.status}</option>)}</select></label>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{roster&&intake&&<><form onSubmit={submit}><label>Pengaturan<select value={command} disabled={busy} onChange={e=>setCommand(e.target.value as keyof typeof commands)}>{Object.entries(commands).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
 {['DIVISION','POSITION'].includes(command)&&<><label>Kode<input required name="code" pattern="[A-Z][A-Z0-9_]{1,39}" maxLength={40} disabled={busy}/></label><label>Nama resmi<input required name="name" minLength={3} maxLength={180} disabled={busy}/></label></>}{['POSITION','MANDATE_PROPOSE','ROUTING'].includes(command)&&divisionSelect}{['ASSIGN','MANDATE_PROPOSE','ROUTING'].includes(command)&&accountSelect}
 {command==='ASSIGN'&&<><label>Jabatan<select name="positionId" required disabled={busy}><option value="">Pilih jabatan</option>{roster.positions.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Mulai penugasan<input required type="date" name="startsOn" min={period?.startsOn} max={period?.endsOn} disabled={busy}/></label><label>Berakhir<input required type="date" name="endsOn" min={period?.startsOn} max={period?.endsOn} disabled={busy}/></label></>}
 {command==='MANDATE_PROPOSE'&&<><p>Usulan belum mengaktifkan kewenangan. Persetujuan independen membutuhkan mandat pengelolaan identitas yang sudah terdaftar. Mandat pertama tetap harus disahkan KPI dan dicatat melalui prosedur bootstrap resmi.</p><label>Mulai berlaku<input required type="datetime-local" name="startsAt" disabled={busy}/></label><label>Berakhir<input required type="datetime-local" name="expiresAt" disabled={busy}/></label><fieldset disabled={busy}><legend>Klasifikasi sesuai mandat</legend>{['TERBUKA','INTERNAL','TERBATAS','RAHASIA'].map(c=><label key={c}><input type="checkbox" name="classifications" value={c}/>{c}</label>)}</fieldset><label>Izin / kewenangan dalam mandat<select multiple value={selectedPermissions} disabled={busy} onChange={e=>setSelectedPermissions(Array.from(e.target.selectedOptions,o=>o.value))}>{[...permissions,'ACCESS_REVIEW','CLASSIFICATION_APPROVE','CLASSIFICATION_DOWNGRADE','EVIDENCE_HOLD','EVIDENCE_RELEASE'].map(p=><option key={p} value={p}>{p}</option>)}</select></label></>}
 {command==='ROUTING'&&<><p>Penerimaan: {intake.ready?'Terbuka dan siap':'Belum siap menerima'}. Sekretaris: {roster.accounts.find(a=>a.id===intake.routing?.secretaryAccountId)?.name||'Belum ditetapkan'}. Divisi tindak lanjut: {roster.divisions.find(d=>d.id===intake.routing?.iodDivisionId)?.name||'Belum ditetapkan'}.</p><label><input type="checkbox" name="enabled" disabled={busy}/>Buka penerimaan sesuai mandat resmi (periode dan izin petugas harus siap)</label></>}
 {command==='TEMPLATE_CREATE'&&<><label>Jenis formulir<select name="kind" disabled={busy}><option value="PENGADUAN">Pengaduan</option><option value="SARAN">Saran</option><option value="PERTANYAAN">Pertanyaan</option></select></label><label>Judul<input required name="title" minLength={3} maxLength={180} disabled={busy}/></label><label>Panduan pengisian<textarea required name="instructions" minLength={3} maxLength={2000} disabled={busy}/></label><label>Pertanyaan tambahan (satu per baris, maksimal enam)<textarea name="questions" rows={6} maxLength={1100} disabled={busy}/></label><p>Pertanyaan tambahan wajib diisi dan dibatasi 300 karakter. Template perlu persetujuan independen sebelum tampil untuk masyarakat.</p></>}
 {['ASSIGN','MANDATE_PROPOSE','TEMPLATE_CREATE'].includes(command)&&<label>Rujukan keputusan / dokumen resmi<input name="reference" required minLength={3} maxLength={1000} disabled={busy}/></label>}<label>Catatan tindakan<textarea required minLength={3} maxLength={2000} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></label><button className="button button--primary" disabled={busy||note.trim().length<3}>Simpan pengaturan</button></form>
 <h3>Penugasan tercatat</h3>{roster.assignments.map(a=><div className="hm-line" key={a.id}><strong>{roster.accounts.find(x=>x.id===a.accountId)?.name} · {roster.positions.find(p=>p.id===a.positionId)?.name}</strong><span>{a.startsOn} – {a.endsOn||'Belum ditetapkan'} · v{a.version}</span><small>{a.decisionReference||'Rujukan keputusan belum dicatat'}</small><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void run('END_ASSIGNMENT',{id:a.id,expectedVersion:a.version,endsOn:String(data.get('endsOn')),decisionReference:String(data.get('reference'))});}}><label>Tanggal pengakhiran<input type="date" name="endsOn" required min={a.startsOn} max={period?.endsOn} disabled={busy}/></label><label>Rujukan keputusan<input name="reference" required minLength={3} maxLength={1000} disabled={busy}/></label><button disabled={busy||note.trim().length<3}>Akhiri penugasan</button></form></div>)}<h3>Mandat</h3>{!roster.mandates.length&&<p>Belum ada usulan mandat.</p>}{roster.mandates.map(m=><div className="hm-line" key={m.id}><strong>{m.reference} · {m.status}</strong><span>{roster.accounts.find(a=>a.id===m.accountId)?.name} · {m.permissions.join(', ')}</span><div className="portal-form-actions">{(m.status==='PENDING'?['MANDATE_APPROVE','MANDATE_REJECT']:m.status==='APPROVED'?['MANDATE_REVOKE']:[]).map(c=><button type="button" disabled={busy||note.trim().length<3} key={c} onClick={()=>void run(c,{id:m.id,expectedVersion:m.version})}>{c==='MANDATE_APPROVE'?'Setujui mandat':c==='MANDATE_REJECT'?'Tolak':'Cabut mandat'}</button>)}</div></div>)}<h3>Template formulir</h3>{!intake.templates.length&&<p>Belum ada template.</p>}{intake.templates.map(t=><div className="hm-line" key={t.id}><strong>{t.title} · {t.status}</strong><span>{t.instructions}</span><div className="portal-form-actions">{(t.status==='DRAFT'?['TEMPLATE_APPROVE']:t.status==='APPROVED'?['TEMPLATE_WITHDRAW']:[]).map(c=><button type="button" disabled={busy||note.trim().length<3} key={c} onClick={()=>void run(c,{id:t.id,expectedVersion:t.version})}>{c==='TEMPLATE_APPROVE'?'Setujui template':'Tarik template'}</button>)}</div></div>)}</>}</section>;
}
