"use client";
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {taskExtensionsSchema,taskPeopleSchema,taskTemplatesSchema} from '@/platform/work/hosted-task-extensions';
import {type HostedTask,hostedTaskSchema,type HostedTaskScope} from '@/platform/work/hosted-task-contract';
import {portalJson,scopeQuery} from '@/components/portal/hosted-management-workspace';
export function HostedTaskTemplatePicker({scope,disabled,onSelect}:{scope:HostedTaskScope;disabled:boolean;onSelect:(title:string,description:string)=>void}){
 const [templates,setTemplates]=useState<z.infer<typeof taskTemplatesSchema>>([]),[message,setMessage]=useState('');
 useEffect(()=>{let current=true;setTemplates([]);setMessage('');void portalJson('/api/v1/work/tasks/templates?'+scopeQuery(scope)).then(r=>{if(current)setTemplates(taskTemplatesSchema.parse(r.templates));}).catch(()=>{if(current)setMessage('Template belum dapat dimuat.');});return()=>{current=false;};},[scope.organizationCode,scope.periodCode,scope.divisionCode]);
 return <label>Gunakan template (opsional)<select disabled={disabled||!templates.length} value="" onChange={e=>{const t=templates.find(t=>t.id===e.target.value);if(t)onSelect(t.title,t.description);}}><option value="">{templates.length?'Pilih template':'Belum ada template dalam lingkup ini'}</option>{templates.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select>{message&&<small>{message}</small>}</label>;
}
export function HostedTaskTools({task,tasks,canManage,accountId,onChanged,onOpen}:{task:HostedTask;tasks:HostedTask[];canManage:boolean;accountId:string;onChanged:(task:HostedTask)=>Promise<void>;onOpen:(task:HostedTask)=>void}){
 const [extensions,setExtensions]=useState<z.infer<typeof taskExtensionsSchema>|null>(null),[people,setPeople]=useState<z.infer<typeof taskPeopleSchema>>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[owner,setOwner]=useState(''),[deadline,setDeadline]=useState(''),[childTitle,setChildTitle]=useState(''),[childDescription,setChildDescription]=useState(''),[dependency,setDependency]=useState('');const generation=useRef(0);const key=useRef<string|null>(null);
 useEffect(()=>{const current=++generation.current;setExtensions(null);setPeople([]);setError('');setNote('');setOwner('');setDependency('');key.current=null;
 void (async()=>{try{const results=await Promise.all([portalJson(`/api/v1/work/tasks/${task.id}/extensions`),canManage?portalJson(`/api/v1/work/tasks/${task.id}/extensions?people=1`):Promise.resolve({people:[]})]);if(current===generation.current){setExtensions(taskExtensionsSchema.parse(results[0].extensions));setPeople(taskPeopleSchema.parse(results[1].people));}}catch(e){if(current===generation.current)setError((e as Error).message);}})();return()=>{generation.current++;};},[task.id,task.version,canManage]);
 async function run(command:string,extra:object={}){if(busy)return;setBusy(true);setError('');try{const r=await portalJson(`/api/v1/work/tasks/${task.id}/extensions`,{command,expectedVersion:task.version,note,...extra});key.current=null;await onChanged(hostedTaskSchema.parse(r.task));setChildTitle('');setChildDescription('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const editable=canManage&&['OPEN','IN_PROGRESS','REVISION'].includes(task.status);const ready=!busy&&note.trim().length>=3;
 return <div className="hosted-task-tools">{error&&<p role="alert">{error}</p>}{extensions&&<><h3>Hubungan pekerjaan</h3>{extensions.blocked&&<p role="status">Selesaikan seluruh subtugas dan prasyarat sebelum mengajukan hasil.</p>}{extensions.parentTaskId&&<a href={`/portal/tugas?task=${extensions.parentTaskId}`}>Buka tugas induk</a>}{[...extensions.subtasks.map(t=>({t,label:'Subtugas'})),...extensions.dependencies.map(t=>({t,label:'Prasyarat'}))].map(({t,label})=><div className="hm-line" key={`${label}-${t.id}`}><button type="button" className="button button--quiet" disabled={busy} onClick={()=>onOpen(t)}>{label}: {t.title} · {t.status}</button>{editable&&label==='Prasyarat'&&<button type="button" disabled={!ready} onClick={()=>void run('DEPENDENCY_REMOVE',{prerequisiteId:t.id})}>Lepas prasyarat</button>}</div>)}{!extensions.subtasks.length&&!extensions.dependencies.length&&<p>Belum ada subtugas atau prasyarat.</p>}</>}
 <label>Catatan perubahan atau diskusi<textarea rows={3} maxLength={2000} disabled={busy} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="button button--quiet" type="button" disabled={!ready||task.status==='CANCELLED'} onClick={()=>void run('COMMENT')}>Kirim diskusi</button>
 {editable&&<details><summary>Delegasi, tenggat, dan perincian tugas</summary><div className="portal-form-grid"><label>Pelaksana baru<select value={owner} disabled={busy} onChange={e=>setOwner(e.target.value)}><option value="">Pilih pengurus berizin</option>{people.filter(p=>p.accountId!==task.ownerAccountId).map(p=><option key={p.accountId} value={p.accountId}>{p.name}</option>)}</select></label><button type="button" disabled={!ready||!owner} onClick={()=>void run('DELEGATE',{ownerAccountId:owner})}>Delegasikan tugas</button><label>Tenggat baru (kosongkan untuk menghapus)<input type="datetime-local" value={deadline} disabled={busy} onChange={e=>setDeadline(e.target.value)}/></label><button type="button" disabled={!ready} onClick={()=>void run('DEADLINE',{dueAt:deadline?new Date(deadline).toISOString():null})}>Perbarui tenggat</button></div>
 <h4>Subtugas</h4><label>Judul subtugas<input minLength={3} maxLength={180} disabled={busy} value={childTitle} onChange={e=>{key.current=null;setChildTitle(e.target.value);}}/></label><label>Uraian<textarea maxLength={4000} rows={3} disabled={busy} value={childDescription} onChange={e=>{key.current=null;setChildDescription(e.target.value);}}/></label><p>Subtugas baru ditugaskan kepada Anda. Setelah tersimpan, delegasikan bila diperlukan. Tugas dengan klasifikasi terbatas/rahasia membutuhkan pengaturan objek tersendiri.</p><button type="button" disabled={!ready||childTitle.trim().length<3} onClick={()=>{key.current??=crypto.randomUUID();void run('SUBTASK',{title:childTitle,description:childDescription,ownerAccountId:accountId,requestKey:key.current});}}>Tambahkan subtugas</button>
 <h4>Prasyarat</h4><label>Pekerjaan yang harus selesai dahulu<select value={dependency} disabled={busy} onChange={e=>setDependency(e.target.value)}><option value="">Pilih tugas dalam divisi yang sama</option>{tasks.filter(t=>t.id!==task.id&&t.divisionCode===task.divisionCode&&t.status!=='CANCELLED').map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><button type="button" disabled={!ready||!dependency} onClick={()=>void run('DEPENDENCY_ADD',{prerequisiteId:dependency})}>Tambahkan prasyarat</button><h4>Template pekerjaan</h4><p>Template menyimpan judul dan uraian. Pelaksana, tenggat, serta riwayat tidak ikut disalin.</p><button type="button" disabled={!ready} onClick={()=>void run('TEMPLATE')}>Simpan sebagai template</button></details>}
 </div>;
}
