import Link from "next/link";
import { cookies } from "next/headers";
import { getTestSession, sessionCookieName } from "@/platform/identity/test-auth";

const editorialSteps = ["Draft", "Review", "Approved", "Published"];

export default async function EditorPage(): Promise<React.JSX.Element> {
  const identity = getTestSession((await cookies()).get(sessionCookieName)?.value);
  if (!identity) return <div className="portal-shell"><header className="page-heading"><p className="eyebrow">C01–C07 · CMS</p><h1>Masuk diperlukan.</h1><p>Editor hanya dapat dibuka setelah sesi TEST terbentuk.</p></header><Link className="button button--primary" href="/masuk">Masuk ke portal</Link></div>;
  return <div className="portal-shell"><header className="page-heading"><div className="intro-panel__topline"><p className="eyebrow">E04 · CMS editorial</p><span className="status-chip">UI TEST</span></div><h1>Terbitkan dengan jejak.</h1><p>Draft, review, persetujuan, dan publikasi dipisahkan agar versi publik tidak tertukar dengan catatan internal.</p></header><section className="editor-flow" aria-label="Tahap editorial">{editorialSteps.map((step, index) => <div className={`editor-step ${index === 0 ? "editor-step--active" : ""}`} key={step}><span>0{index + 1}</span><strong>{step}</strong>{index === 0 ? <small>Aktif di TEST</small> : <small>Menunggu tahap sebelumnya</small>}</div>)}</section><section className="editor-layout"><article className="editor-canvas"><p className="eyebrow">C02 · Draft bilingual</p><input aria-label="Judul draft" defaultValue="Judul informasi publik · TEST" /><textarea aria-label="Isi draft" defaultValue="Isi resmi akan ditulis oleh editor KPI setelah konten diserahkan." rows={8} /><div className="language-row"><span className="status-chip">ID · Draft</span><span className="status-chip">EN · Belum tersedia</span></div><button className="button button--primary" type="button">Simpan draft TEST</button></article><aside className="editor-sidebar"><p className="eyebrow">C03–C04 · Review & publish</p><h2>Checklist penerbitan</h2><ul><li>Owner editorial ditetapkan</li><li>Versi bahasa diperiksa</li><li>Aset memiliki klasifikasi</li><li>Approver sesuai scope</li><li>Preview publik aman</li></ul><p className="editor-note">Tombol publish tetap nonaktif sampai service approval dan konten resmi tersedia.</p></aside></section><Link className="button button--quiet" href="/portal">Kembali ke portal</Link></div>;
}
