'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import type {HostedTaskScope} from '@/platform/work/hosted-task-contract';
import {internalScreens} from '@/lib/internal-screen-registry';
import {portalJson,scopeQuery,HostedManagementWorkspace,type AiDraftProposal} from './hosted-management-workspace';
import type {HostedAccess} from '@/platform/authorization/hosted-access';
type Snapshot={tasks:{id:string;title:string;status:string;dueAt:string|null;canReview:boolean}[];meetings:{id:string;title:string;startsAt:string;status:string}[];reviews:{id:string;kind:string;title:string;status:string}[];notifications:unknown[]};
type Operations={databaseReady:boolean;privateStorage:boolean;periods:{code:string;status:string;startsOn:string;endsOn:string}[];modules:Record<string,boolean>;processors:{purpose:string;classifications:string[];expiresAt:string}[];audit:{id:string;action:string;module:string;result:string;at:string}[]};
export function HostedWorkspaceDashboard({scopes}:{scopes:HostedTaskScope[]}){
 const [index,setIndex]=useState(0),[data,setData]=useState<Snapshot|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);const scope=scopes[index];
 async function load(){if(!scope)return;setLoading(true);setMessage('');setData(null);try{setData((await portalJson('/api/v1/work/workspace?'+scopeQuery(scope))).data);}catch(e){setMessage((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[index]);
 if(!scope)return <section className="state-panel"><h2>Belum ada periode dan izin kerja aktif</h2><p>Ringkasan pekerjaan muncul setelah penugasan resmi dan izin ruang kerja tersedia.</p><Link href="/portal/akses">Periksa hak akses</Link></section>;
 return <section><div className="hm-toolbar"><label>Lingkup kerja<select value={index} onChange={e=>setIndex(Number(e.target.value))}>{scopes.map((s,i)=><option key={i} value={i}>{s.organizationCode} · {s.periodCode} {s.divisionCode}</option>)}</select></label><button disabled={loading} onClick={()=>void load()}>Muat ulang</button></div>{message&&<p role="status">{message}</p>}{data&&<><div className="hm-metrics">{[['Tugas terbuka',data.tasks.length],['Rapat mendatang',data.meetings.length],['Catatan dalam pemeriksaan',data.reviews.length],['Notifikasi',data.notifications.length]].map(([name,count])=><article key={name}><span>{name}</span><strong>{count}</strong></article>)}</div><div className="hm-columns"><section className="portal-form-card"><h2>Tugas & tenggat</h2>{!data.tasks.length&&<p>Belum ada tugas yang terbuka.</p>}{data.tasks.map(t=><article className="hm-line" key={t.id}><strong>{t.title}</strong><span>{t.status}{t.canReview?' · Perlu pemeriksaan':''}</span><small>{t.dueAt?new Date(t.dueAt).toLocaleString('id-ID'):'Tanpa tenggat'}</small></article>)}<Link href="/portal/tugas">Buka daftar tugas</Link></section><section className="portal-form-card"><h2>Rapat & pemeriksaan</h2>{data.meetings.map(m=><article className="hm-line" key={m.id}><strong>{m.title}</strong><span>{new Date(m.startsAt).toLocaleString('id-ID')}</span></article>)}{data.reviews.map(r=><article className="hm-line" key={r.id}><strong>{r.title}</strong><Link href={r.kind==='EVALUATION'?'/portal/evaluasi':r.kind==='HANDOVER'?'/portal/handover':r.kind==='RECOVERY_CHECK'?'/portal/operasi':'/portal/keuangan'}>Buka modul pemeriksaan</Link></article>)}{!data.meetings.length&&!data.reviews.length&&<p>Belum ada rapat atau pemeriksaan.</p>}<Link href="/portal/rapat">Buka rapat</Link></section></div></>}</section>;
}
function useOperations(enabled:boolean){const [data,setData]=useState<Operations|null>(null),[message,setMessage]=useState('');async function load(){if(!enabled)return;setMessage('');try{setData((await portalJson('/api/v1/work/operations')).data);}catch(e){setMessage((e as Error).message);}}useEffect(()=>{void load();},[enabled]);return {data,message,load};}
export function HostedOperationsPanel({administrator}:{administrator:boolean}){
 const {data,message,load}=useOperations(administrator);const [filter,setFilter]=useState('');
 if(!administrator)return <p role="status">Ringkasan operasi hanya tersedia bagi administrator teknis.</p>;
 const events=data?.audit.filter(e=>`${e.action} ${e.module} ${e.result}`.toLowerCase().includes(filter.toLowerCase()))||[];
 function exportAudit(){const cell=(s:string)=>'"'+(/^[=+\-@]/.test(s)?'\t':'')+s.replaceAll('"','""')+'"';const csv=[['Waktu','Modul','Tindakan','Hasil'],...events.map(e=>[e.at,e.module,e.action,e.result])].map(row=>row.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='audit-kpi.csv';a.click();URL.revokeObjectURL(url);}
 return <section className="portal-form-card"><div className="hm-toolbar"><h2>Kesiapan layanan</h2><button onClick={()=>void load()}>Muat ulang</button></div>{message&&<p role="status">{message}</p>}{data&&<><div className="hm-metrics"><article><span>Database operasional</span><strong>{data.databaseReady?'Tersambung':'Perlu migrasi'}</strong></article><article><span>Storage privat</span><strong>{data.privateStorage?'Tersedia':'Belum tersedia'}</strong></article><article><span>Periode aktif</span><strong>{data.periods.filter(p=>p.status==='ACTIVE').length}</strong></article><article><span>Penyedia berizin</span><strong>{data.processors.length}</strong></article></div><h3>Periode kepengurusan</h3>{data.periods.map(p=><p key={p.code}>{p.code} · {p.status} · {p.startsOn} – {p.endsOn}</p>)}<h3>Jejak tindakan</h3><p>100 tindakan terbaru. Ringkasan teknis tidak menampilkan isi kasus atau dokumen.</p><div className="hm-toolbar"><input aria-label="Cari audit" placeholder="Cari tindakan atau modul" value={filter} onChange={e=>setFilter(e.target.value)}/><button onClick={exportAudit}>Unduh CSV</button></div><div className="hm-table"><table><thead><tr><th>Waktu</th><th>Modul</th><th>Tindakan</th><th>Hasil</th></tr></thead><tbody>{events.map(e=><tr key={e.id}><td>{new Date(e.at).toLocaleString('id-ID')}</td><td>{e.module}</td><td>{e.action}</td><td>{e.result}</td></tr>)}</tbody></table></div><p>Uji pemulihan di bawah mencatat bukti pencadangan dan pemulihan yang telah dilakukan. Pelaksanaan backup dan restore tetap dilakukan pada layanan database dengan prosedur yang disetujui.</p></>}</section>;
}
export function HostedScreenCatalog({administrator}:{administrator:boolean}){
 const {data,message}=useOperations(administrator);const [query,setQuery]=useState(''),[group,setGroup]=useState('');const screens=internalScreens.filter(s=>(!group||s.group===group)&&`${s.id} ${s.title} ${s.acceptance}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="portal-form-card"><h2>Peta rancangan internal</h2><p>{internalScreens.length} layar rujukan. Satu halaman modul dapat mencakup beberapa layar atau keadaan alur.</p>{message&&<p role="status">{message}</p>}{data&&<p>{Object.values(data.modules).filter(Boolean).length}/{Object.keys(data.modules).length} sambungan database modul terdeteksi. Angka ini tidak menyatakan seluruh layar sudah diuji.</p>}<div className="hm-toolbar"><input aria-label="Cari layar" placeholder="Cari kode atau fitur" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Kelompok layar" value={group} onChange={e=>setGroup(e.target.value)}><option value="">Semua kelompok</option>{[...new Set(internalScreens.map(s=>s.group))].map(g=><option key={g}>{g}</option>)}</select></div><div className="hm-table"><table><thead><tr><th>Layar</th><th>Modul</th><th>Alur yang dirancang</th><th>Tujuan</th></tr></thead><tbody>{screens.map(s=><tr key={s.id}><td><strong>{s.id}</strong><br/>{s.title}</td><td>{s.group}</td><td>{s.acceptance}</td><td><Link href={s.route}>Buka modul</Link></td></tr>)}</tbody></table></div></section>;
}
export function HostedAiSurface({identity,scopes}:{identity:HostedAccess;scopes:HostedTaskScope[]}){const [proposal,setProposal]=useState<AiDraftProposal|null>(null);return <><HostedAiPanel scopes={scopes} onDraft={setProposal}/><HostedManagementWorkspace identity={identity} scopes={scopes} initialKind="AI_DRAFT" proposal={proposal}/></>;}
export function HostedAiPanel({scopes,onDraft}:{scopes:HostedTaskScope[];onDraft:(draft:AiDraftProposal)=>void}){
 const [index,setIndex]=useState(0),[question,setQuestion]=useState(''),[sources,setSources]=useState<{id:string;title:string}[]>([]),[picked,setPicked]=useState<string[]>([]),[answer,setAnswer]=useState<{answer:string;citations:string[];sourceVersions:Record<string,number>;draft:{title:string;description:string;target:string}|null}|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const scope=scopes[index];
 useEffect(()=>{setAnswer(null);setPicked([]);setSources([]);},[index]);
 async function loadSources(){if(!scope)return;try{const q=scopeQuery(scope);q.set('kind','KNOWLEDGE');const response=await portalJson('/api/v1/work/content?'+q);setSources(response.items||response.content||[]);}catch(e){setMessage((e as Error).message);}}
 async function ask(e:React.FormEvent){e.preventDefault();if(!scope)return;setBusy(true);setAnswer(null);setMessage('');try{setAnswer((await portalJson('/api/v1/work/ai',{...scope,question,sources:picked})).answer);}catch(e){setMessage((e as Error).message+' Anda tetap dapat menulis dan mengonfirmasi draf sendiri di bawah.');}finally{setBusy(false);}}
 if(!scope)return <p>Asisten membutuhkan periode dan izin AI yang aktif.</p>;
 return <section className="portal-form-card"><h2>Ceritakan kebutuhan Anda</h2><p>Penyedia AI harus dikonfigurasi dan memiliki persetujuan pemrosesan informasi. Jawaban tidak menjalankan tindakan atau mengubah izin.</p><form onSubmit={ask}><label>Lingkup<select value={index} onChange={e=>setIndex(Number(e.target.value))}>{scopes.map((s,i)=><option key={i} value={i}>{s.organizationCode} · {s.periodCode} {s.divisionCode}</option>)}</select></label><label>Pesan<textarea required minLength={3} maxLength={4000} rows={4} value={question} onChange={e=>setQuestion(e.target.value)}/></label><button type="button" onClick={()=>void loadSources()}>Pilih sumber pengetahuan</button><div className="hm-source-list">{sources.map(s=><label key={s.id}><input type="checkbox" checked={picked.includes(s.id)} disabled={!picked.includes(s.id)&&picked.length>=5} onChange={e=>setPicked(e.target.checked?[...picked,s.id]:picked.filter(id=>id!==s.id))}/>{s.title}</label>)}</div><button className="button button--primary" disabled={busy} type="submit">{busy?'Memproses…':'Kirim ke asisten'}</button></form>{message&&<p role="status">{message}</p>}{answer&&<article className="hm-ai-answer"><h3>Jawaban asisten</h3><p>{answer.answer}</p><ul>{answer.citations.map(id=><li key={id}>{sources.find(s=>s.id===id)?.title||id}</li>)}</ul>{answer.draft&&<><h3>Usulan draf · belum disimpan</h3><strong>{answer.draft.title}</strong><p>{answer.draft.description}</p><p>Tujuan: {answer.draft.target==='TASK'?'Tugas':'Pengetahuan'}. Periksa draf pada formulir di bawah sebelum menyimpan.</p><button onClick={()=>onDraft({...answer.draft!,sources:picked,sourceVersions:answer.sourceVersions,scope,key:crypto.randomUUID()})}>Gunakan draf untuk diperiksa</button><p>Sumber: {picked.join(', ')||'Tidak menggunakan sumber dokumen'}</p></>}</article>}</section>;
}
