'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {hasHostedPermission,type HostedAccess} from '@/platform/authorization/hosted-access';
import type {Permission} from '@/platform/authorization/permission-catalog';
import type {HostedTaskScope} from '@/platform/work/hosted-task-contract';
import {managementRecord,type ManagementKind,type ManagementRecord} from '@/platform/work/hosted-management-contract';
const names:Record<ManagementKind,string>={BUDGET:'Anggaran',FINANCE:'Transaksi',EVALUATION:'Evaluasi',HANDOVER:'Serah terima',AI_DRAFT:'Draf asisten',RECOVERY_CHECK:'Uji pemulihan'};
const read:Record<ManagementKind,Permission>={BUDGET:'FINANCE_READ',FINANCE:'FINANCE_READ',EVALUATION:'EVALUATION_READ',HANDOVER:'HANDOVER_READ',AI_DRAFT:'AI_READ',RECOVERY_CHECK:'SYSTEM_CONFIGURATION_READ'};
const write:Record<ManagementKind,Permission>={BUDGET:'FINANCE_MANAGE',FINANCE:'FINANCE_MANAGE',EVALUATION:'EVALUATION_WRITE',HANDOVER:'HANDOVER_ACCEPT',AI_DRAFT:'AI_ACTION_CONFIRM',RECOVERY_CHECK:'SYSTEM_CONFIGURATION_READ'};
const labels:Record<string,string>={DRAFT:'Draf',REVISION:'Perlu revisi',IN_REVIEW:'Menunggu pemeriksaan',CHECKED:'Telah diperiksa',APPROVED:'Disetujui',PAID:'Pembayaran dicatat',RECONCILED:'Direkonsiliasi',APPEALED:'Dalam keberatan',CLOSED:'Selesai',COMMITTED:'Draf sudah diterapkan',REJECTED:'Ditolak',SAVE:'Simpan revisi',SUBMIT:'Ajukan pemeriksaan',CHECK:'Verifikasi bukti',APPROVE:'Setujui',REQUEST_REVISION:'Minta revisi',REJECT:'Tolak',RECORD_PAYMENT:'Catat pembayaran',RECONCILE:'Rekonsiliasi',APPEAL:'Ajukan keberatan',CLOSE:'Selesaikan serah terima',COMMIT:'Konfirmasi dan buat data',ADD_ITEM:'Tambahkan dokumen',ACCEPT_ITEM:'Terima dokumen'};
export function scopeQuery(scope:HostedTaskScope){const q=new URLSearchParams({organizationCode:scope.organizationCode,periodCode:scope.periodCode});if(scope.divisionCode)q.set('divisionCode',scope.divisionCode);return q;}
export async function portalJson(url:string,body?:unknown){const response=await fetch(url,{cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(!response.ok)throw new Error(response.status===409?'Data berubah. Muat ulang sebelum mencoba lagi.':response.status===403?'Tindakan ditolak. Periksa izin, pemeriksa yang berbeda, dan bukti dokumen.':response.status===429?'Batas permintaan tercapai. Tunggu sebentar sebelum mencoba lagi.':response.status===503?'Layanan belum dikonfigurasi atau belum disetujui.':response.status===401?'Sesi berakhir. Silakan masuk kembali.':'Data belum lengkap atau tidak sesuai alur.');return response.json();}
export type AiDraftProposal={title:string;description:string;target:string;sources:string[];sourceVersions:Record<string,number>;scope:HostedTaskScope;key:string};
export function HostedManagementWorkspace({identity,scopes,initialKind,proposal}:{identity:HostedAccess;scopes:HostedTaskScope[];initialKind:ManagementKind;proposal?:AiDraftProposal|null}){
 const [scopeIndex,setScopeIndex]=useState(0),[kind,setKind]=useState(initialKind),[records,setRecords]=useState<ManagementRecord[]>([]),[budgets,setBudgets]=useState<ManagementRecord[]>([]),[people,setPeople]=useState<{id:string;name:string}[]>([]),[assets,setAssets]=useState<{id:string;name?:string;originalName?:string;status:string}[]>([]),[selected,setSelected]=useState<ManagementRecord|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState('');
 const [fields,setFields]=useState<Record<string,string>>({currency:'EGP',target:'TASK'});const key=useRef<string|null>(null);const generation=useRef(0);const scope=scopes[scopeIndex];
 const permit=(p:Permission,r?:ManagementRecord)=>!!scope&&hasHostedPermission(identity,p,{...scope,divisionCode:r?r.divisionCode||undefined:scope.divisionCode||undefined,objectId:r?.id})&&(!r||!['EVALUATION','AI_DRAFT'].includes(r.kind)||identity.grants.some(g=>g.objectId===r.id&&g.permission===p));
 const confidential=['EVALUATION','AI_DRAFT'].includes(kind);
 const slotReady=!confidential||!!fields.reservedId&&[read[kind],write[kind]].every(p=>identity.grants.some(g=>g.objectId===fields.reservedId&&g.permission===p&&hasHostedPermission(identity,p,{...scope,divisionCode:scope?.divisionCode||undefined,objectId:fields.reservedId})));

 async function load(){if(!scope)return;const current=++generation.current;setBusy(true);setMessage('');try{const q=scopeQuery(scope);q.set('kind',kind);const result=await portalJson('/api/v1/work/management?'+q);const nextRecords=result.data.map((r:unknown)=>managementRecord.parse(r));let nextBudgets:ManagementRecord[]=[],nextPeople:{id:string;name:string}[]=[];
 if(kind==='FINANCE'){q.set('kind','BUDGET');nextBudgets=(await portalJson('/api/v1/work/management?'+q)).data.filter((r:ManagementRecord)=>r.status==='APPROVED');}
 if((kind==='EVALUATION'||kind==='HANDOVER')&&permit(write[kind])){q.set('people','1');nextPeople=(await portalJson('/api/v1/work/management?'+q)).data;}
 if(current!==generation.current)return;setRecords(nextRecords);setBudgets(nextBudgets);setPeople(nextPeople);setSelected(old=>old?nextRecords.find((r:ManagementRecord)=>r.id===old.id)||null:null);
 }catch(e){if(current===generation.current){setRecords([]);setSelected(null);setMessage((e as Error).message);}}finally{if(current===generation.current)setBusy(false);}}
 useEffect(()=>{setSelected(null);setRecords([]);setFields(proposal&&JSON.stringify(proposal.scope)===JSON.stringify(scope)?{title:proposal.title,description:proposal.description,target:proposal.target,sources:proposal.sources.join(','),sourceVersions:JSON.stringify(proposal.sourceVersions)}:{currency:'EGP',target:'TASK'});setAssets([]);setPeople([]);key.current=null;void load();return ()=>{generation.current++;};},[scopeIndex,kind]);
 useEffect(()=>{if(!proposal)return;const index=scopes.findIndex(s=>JSON.stringify(s)===JSON.stringify(proposal.scope));if(index<0)return;setScopeIndex(index);setSelected(null);setFields({title:proposal.title,description:proposal.description,target:proposal.target,sources:proposal.sources.join(','),sourceVersions:JSON.stringify(proposal.sourceVersions)});key.current=null;setMessage('Usulan asisten dimuat. Periksa judul, uraian, sumber, dan tujuan sebelum menyimpan.');},[proposal]);
 async function loadAssets(){if(!scope)return;const current=generation.current;try{const result=await portalJson('/api/v1/work/assets?'+scopeQuery(scope));if(current!==generation.current)return;setAssets(result.assets.filter((a:{status:string})=>a.status==='AVAILABLE'));setMessage(result.assets.some((a:{status:string})=>a.status==='AVAILABLE')?'Dokumen terverifikasi dimuat.':'Belum ada dokumen terverifikasi.');}catch(e){setMessage((e as Error).message);}}
 const editable=!selected||(selected.creatorAccountId===identity.accountId&&['DRAFT','REVISION'].includes(selected.status));
 const value=(name:string)=>fields[name]??'';
 const field=(name:string,label:string,type='text',required=true)=><label key={name}>{label}<input type={type} readOnly={!!selected&&!editable&&['title','amount','score','criteriaReference'].includes(name)} step={name==='amount'?'any':undefined} required={required} value={value(name)} min={type==='number'?0:undefined} max={name==='score'?100:undefined} maxLength={name==='title'?180:500} onChange={e=>setFields({...fields,[name]:e.target.value})}/></label>;
 const select=(name:string,label:string,options:{value:string;label:string}[],required=true)=><label key={name}>{label}<select disabled={!!selected&&name==='currency'} required={required} value={value(name)} onChange={e=>setFields({...fields,[name]:e.target.value})}><option value="">Pilih</option>{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
 function input(){const result:Record<string,unknown>={...fields};if(kind==='BUDGET'||kind==='FINANCE'){const decimals=value('currency')==='IDR'?0:2;const amount=Number(value('amount'));result.amountMinor=Math.round(amount*10**decimals);if(!Number.isFinite(amount)||amount<=0||Math.abs(amount*10**decimals-Number(result.amountMinor))>0.00001)throw new Error('Jumlah harus positif; IDR tanpa desimal, EGP/USD maksimal dua desimal.');delete result.amount;}if(kind==='EVALUATION')result.score=Number(value('score'));if(kind==='AI_DRAFT'&&value('sourceVersions'))result.sourceVersions=JSON.parse(value('sourceVersions'));if(kind==='AI_DRAFT')result.sources=(value('sources')||'').split(',').map(s=>s.trim()).filter(Boolean);return result;}
 async function create(event:React.FormEvent){event.preventDefault();if(!scope)return;setBusy(true);try{const body=input();key.current??=crypto.randomUUID();const result=await portalJson('/api/v1/work/management',{operation:'CREATE',...scope,kind,input:body,idempotencyKey:key.current});key.current=null;setFields({currency:'EGP',target:'TASK'});await load();choose(managementRecord.parse(result.data));setMessage('Data tersimpan di database.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function reserve(){if(!scope)return;setBusy(true);try{const result=await portalJson('/api/v1/work/management',{operation:'RESERVE',kind,...scope});setFields({...fields,reservedId:result.data.id});setMessage('Nomor catatan rahasia dibuat. Ajukan izin baca dan pengelolaan khusus untuk ID ini melalui F01, lalu muat ulang halaman setelah izin diterapkan. Belum ada isi penilaian atau draf yang disimpan.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function choose(r:ManagementRecord){setSelected(r);setFields({title:r.title,description:String(r.payload.description||''),currency:String(r.payload.currency||'EGP'),amount:String(Number(r.payload.amountMinor||0)/(r.payload.currency==='IDR'?1:100)),score:String(r.payload.score??''),criteriaReference:String(r.payload.criteriaReference||''),target:String(r.payload.target||'TASK')});}
 async function act(action:string,extra:Record<string,unknown>={}){if(!selected)return;setBusy(true);try{const result=await portalJson('/api/v1/work/management',action==='COMMIT'?{operation:'COMMIT',id:selected.id,expectedVersion:selected.version,note:value('note')}:{operation:'ACTION',id:selected.id,expectedVersion:selected.version,action,input:{...(action==='SAVE'?input():fields),...extra}});await load();choose(managementRecord.parse(result.data));setMessage('Tindakan berhasil disimpan.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function actions(r:ManagementRecord){const owner=r.creatorAccountId===identity.accountId,subject=r.subjectAccountId===identity.accountId,result:string[]=[];if(owner&&['DRAFT','REVISION'].includes(r.status)&&permit(write[kind],r))result.push('SAVE',kind==='AI_DRAFT'?'COMMIT':'SUBMIT');if(kind==='FINANCE'){if(!owner&&r.status==='IN_REVIEW'&&permit('FINANCE_MANAGE',r))result.push('CHECK');if(!owner&&r.payload.checkedBy!==identity.accountId&&r.status==='CHECKED'&&permit('FINANCE_APPROVE_FINAL',r))result.push('APPROVE');if(r.status==='APPROVED'&&permit('FINANCE_MANAGE',r))result.push('RECORD_PAYMENT');if(r.status==='PAID'&&r.payload.paymentRecordedBy!==identity.accountId&&permit('FINANCE_APPROVE_FINAL',r))result.push('RECONCILE');}
 if(['BUDGET','EVALUATION','RECOVERY_CHECK'].includes(kind)&&!owner&&!subject&&['IN_REVIEW','APPEALED'].includes(r.status)&&permit(kind==='BUDGET'?'FINANCE_APPROVE_FINAL':write[kind],r))result.push('APPROVE');if(!owner&&(!subject||kind==='HANDOVER')&&['IN_REVIEW','CHECKED','APPEALED'].includes(r.status)&&permit(['BUDGET','FINANCE'].includes(kind)?'FINANCE_APPROVE_FINAL':write[kind],r)&&(kind!=='HANDOVER'||subject))result.push('REQUEST_REVISION','REJECT');if(kind==='EVALUATION'&&subject&&r.status==='APPROVED'&&!r.payload.appealAt)result.push('APPEAL');if(kind==='HANDOVER'&&subject&&r.status==='IN_REVIEW'&&permit(write[kind],r))result.push('CLOSE');return result;}
 if(!scope)return <section className="state-panel"><h2>Belum ada lingkup kerja yang aktif</h2><p>Penugasan, periode, dan izin {names[kind].toLowerCase()} diperlukan sebelum data operasional dapat dibaca atau dibuat.</p><Link href="/portal/kebijakan">Ajukan akses</Link></section>;
 return <div className="hm-workspace"><div className="hm-toolbar"><label>Lingkup kerja<select disabled={busy} value={scopeIndex} onChange={e=>setScopeIndex(Number(e.target.value))}>{scopes.map((s,i)=><option key={i} value={i}>{s.organizationCode} · {s.periodCode}{s.divisionCode?' · '+s.divisionCode:''}</option>)}</select></label>{['BUDGET','FINANCE'].includes(initialKind)&&<label>Jenis catatan<select disabled={busy} value={kind} onChange={e=>setKind(e.target.value as ManagementKind)}><option value="FINANCE">Transaksi</option><option value="BUDGET">Anggaran</option></select></label>}<button disabled={busy} onClick={()=>void load()}>Muat ulang</button></div>
 {message&&<p className="hm-message" role="status">{message}</p>}
 <div className="hm-columns"><section className="portal-form-card"><div className="hm-toolbar"><input aria-label="Cari catatan" placeholder="Cari judul" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua status</option>{[...new Set(records.map(r=>r.status))].map(s=><option key={s} value={s}>{labels[s]||s}</option>)}</select></div><h2>{names[kind]}</h2><p>{records.length} catatan dalam lingkup ini</p><div className="hm-records">{records.filter(r=>r.title.toLowerCase().includes(search.toLowerCase())&&(!status||r.status===status)).map(r=><button disabled={busy} key={r.id} aria-pressed={selected?.id===r.id} onClick={()=>choose(r)}><strong>{r.title}</strong><span>{labels[r.status]||r.status} · v{r.version}</span><small>{new Date(r.updatedAt).toLocaleString('id-ID')}</small></button>)}</div>{!records.length&&!busy&&<p>Belum ada catatan. Data yang dibuat akan tersimpan dan dapat dimuat kembali.</p>}<button disabled={busy} onClick={()=>{setSelected(null);setFields({currency:'EGP',target:'TASK'});key.current=null;}}>Buat catatan baru</button></section>
 <section className="portal-form-card"><h2>{selected?'Detail catatan':'Catatan baru'}</h2>{!selected&&['EVALUATION','AI_DRAFT'].includes(kind)&&<section className="hm-confidential"><h3>Akses khusus catatan rahasia</h3><p>Buat nomor catatan terlebih dahulu. Isi baru boleh disimpan setelah izin baca dan pengelolaan untuk catatan ini disetujui melalui F01.</p><button disabled={busy} onClick={()=>void reserve()}>Buat / ambil nomor catatan</button>{field('reservedId','ID catatan yang telah diberi izin','text',false)}<Link href="/portal/kebijakan">Ajukan akses F01</Link>{!slotReady&&<p>Izin khusus baca dan pengelolaan belum tersedia untuk nomor ini.</p>}</section>}<form onSubmit={create}><div className="portal-form-grid">{field('title','Judul')}
 {['BUDGET','FINANCE'].includes(kind)&&<>{field('amount','Jumlah','number')}{select('currency','Mata uang',[{value:'IDR',label:'Rupiah (IDR)'},{value:'EGP',label:'Pound Mesir (EGP)'},{value:'USD',label:'Dolar AS (USD)'}])}{kind==='FINANCE'&&!selected&&select('budgetId','Anggaran yang disetujui',budgets.map(r=>({value:r.id,label:r.title})))}</>}
 {['EVALUATION','HANDOVER'].includes(kind)&&!selected&&select('subjectAccountId',kind==='EVALUATION'?'Anggota yang dievaluasi':'Penerima serah terima',people.filter(p=>kind!=='HANDOVER'||p.id!==identity.accountId).map(p=>({value:p.id,label:p.name})))}
 {kind==='EVALUATION'&&<>{field('score','Nilai (0–100)','number')}{field('criteriaReference','Rujukan kriteria resmi')}</>}
 {kind==='RECOVERY_CHECK'&&!selected&&<>{field('backupReference','Referensi bukti pencadangan')}{field('restorationReference','Referensi bukti uji pemulihan')}</>}
 {kind==='AI_DRAFT'&&!selected&&<>{select('target','Tujuan draf',[{value:'TASK',label:'Tugas untuk saya'},{value:'KNOWLEDGE',label:'Draf pengetahuan'}])}{field('sources','ID sumber pengetahuan, dipisahkan koma','text',false)}</>}
 </div><label>Uraian<textarea required minLength={kind==='AI_DRAFT'?10:3} maxLength={4000} readOnly={!editable} rows={5} value={value('description')} onChange={e=>setFields({...fields,description:e.target.value})}/></label>
 {!selected&&permit(write[kind])&&<button className="button button--primary" disabled={busy||!slotReady} type="submit">Simpan draf</button>}</form>
 {selected&&<><dl className="hm-summary"><dt>Status</dt><dd>{labels[selected.status]||selected.status}</dd><dt>Versi</dt><dd>{selected.version}</dd>{['criteriaReference','backupReference','restorationReference','paymentReference','target','previewExpiresAt'].filter(k=>selected.payload[k]).map(k=><div key={k} style={{display:'contents'}}><dt>{{criteriaReference:'Rujukan kriteria',backupReference:'Bukti backup',restorationReference:'Bukti pemulihan',paymentReference:'Bukti pembayaran',target:'Tujuan draf',previewExpiresAt:'Batas pratinjau'}[k]}</dt><dd>{String(selected.payload[k])}</dd></div>)}{Boolean(selected.payload.resultId)&&<><dt>Data yang dibuat</dt><dd><Link href={selected.payload.target==='TASK'?'/portal/tugas':'/portal/knowledge'}>Buka modul tujuan</Link></dd></>}</dl><label>Catatan tindakan<textarea rows={2} minLength={3} maxLength={2000} value={value('note')} onChange={e=>setFields({...fields,note:e.target.value})}/></label>
 {['FINANCE','EVALUATION','HANDOVER'].includes(kind)&&<><button type="button" disabled={busy} onClick={()=>void loadAssets()}>Muat dokumen terverifikasi</button>{select(kind==='HANDOVER'?'assetId':'evidenceAssetId','Dokumen bukti',assets.map(a=>({value:a.id,label:a.originalName||a.name||a.id})),false)}<Link href="/portal/dokumen">Kelola dokumen</Link></>}
 {kind==='FINANCE'&&field('reference','Referensi pembayaran','text',false)}
 {kind==='HANDOVER'&&<><ul className="hm-items">{(selected.payload.items as {id:string;title:string;acceptedAt:string|null}[]||[]).map(item=><li key={item.id}><span>{item.title} · {item.acceptedAt?'Diterima':'Belum diterima'}</span>{!item.acceptedAt&&selected.subjectAccountId===identity.accountId&&selected.status==='IN_REVIEW'&&<button disabled={busy||value('note').trim().length<3} onClick={()=>void act('ACCEPT_ITEM',{itemId:item.id})}>Terima</button>}</li>)}</ul>{selected.creatorAccountId===identity.accountId&&['DRAFT','REVISION'].includes(selected.status)&&<>{field('itemTitle','Nama dokumen serah terima','text',false)}<button disabled={busy||!value('assetId')||value('note').trim().length<3} onClick={()=>void act('ADD_ITEM',{title:value('itemTitle')})}>Tambahkan dokumen</button></>}</>}
 <div className="hm-actions">{actions(selected).map(action=><button className={action==='COMMIT'?'button button--primary':'button button--quiet'} key={action} disabled={busy||value('note').trim().length<3} onClick={()=>void act(action)}>{labels[action]}</button>)}</div>
 <details><summary>Riwayat tindakan ({selected.events.length})</summary><ol className="hm-history">{selected.events.map(event=><li key={event.id}><strong>{labels[event.action]||event.action} · v{event.version}</strong><p>{event.note}</p><small>{new Date(event.at).toLocaleString('id-ID')}</small></li>)}</ol></details></>}
 </section></div></div>;
}
