"use client";
import {useEffect,useRef,useState} from "react";
import {z} from "zod";
const templateSchema=z.object({id:z.string().uuid(),version:z.number().int(),title:z.string(),instructions:z.string(),fields:z.array(z.object({key:z.string(),label:z.string(),required:z.boolean()}))});
const trackingLabels:Record<string,string>={RECEIVED:"Diterima",TRIAGED:"Ditugaskan",IN_PROGRESS:"Ditindaklanjuti",IN_REVIEW:"Menunggu review",CLOSED:"Ditutup"};
export function HostedIntakeForm({complaint=false}:{complaint?:boolean}):React.JSX.Element{
 const [token,setToken]=useState(""),[tracking,setTracking]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sent,setSent]=useState(false);
 const [kind,setKind]=useState(complaint?"PENGADUAN":"SARAN"),[template,setTemplate]=useState<z.infer<typeof templateSchema>|null>(null),[templateLoading,setTemplateLoading]=useState(true),[templateError,setTemplateError]=useState("");
 useEffect(()=>{let live=true;setTemplateLoading(true);setTemplate(null);setTemplateError("");void fetch(`/api/v1/public/intake-template?kind=${kind}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return z.object({template:templateSchema.nullable()}).parse(await r.json());}).then(r=>{if(live)setTemplate(r.template);}).catch(()=>{if(live)setTemplateError("Formulir belum dapat dimuat. Muat ulang halaman sebelum mengirim.");}).finally(()=>{if(live)setTemplateLoading(false);});return()=>{live=false;};},[kind]);
 const retry=useRef<{payload:string;key:string;token:string}|null>(null);
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();if(busy||templateLoading||templateError)return;setBusy(true);setError("");
  const form=new FormData(event.currentTarget);const fields={kind,subject:form.get("subject"),description:form.get("description"),contact:form.get("contact"),website:form.get("website"),consent:form.get("consent")==="on",...(template?{templateId:template.id,templateVersion:template.version,answers:Object.fromEntries(template.fields.map(f=>[f.key,String(form.get(`answer_${f.key}`)||"")]))}:{})};const payload=JSON.stringify(fields);
  if(retry.current?.payload!==payload)retry.current={payload,key:crypto.randomUUID(),token:Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,"0")).join("")};
  try{const response=await fetch("/api/v1/public/aspirations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...fields,idempotencyKey:retry.current.key,trackingToken:retry.current.token})});
   if(!response.ok)throw new Error(response.status===429?"Batas pengiriman tercapai. Tunggu 15 menit sebelum mencoba kembali.":response.status===503?"Penerimaan laporan belum tersedia. Jangan kirim ulang sampai layanan dibuka.":response.status===409?"Isian berubah dari pengiriman sebelumnya. Periksa formulir dan coba kembali.":"Pengiriman belum tersimpan. Periksa isian lalu coba kembali.");
   const result=z.object({trackingToken:z.string().regex(/^[a-f0-9]{64}$/)}).parse(await response.json());setToken(result.trackingToken);setSent(true);
  }catch(e){setError(e instanceof Error?e.message:"Pengiriman gagal. Coba kembali.");}finally{setBusy(false);}
 }
 async function track(){if(busy)return;setBusy(true);setError("");setTracking("");try{const response=await fetch("/api/v1/public/aspirations/track",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({trackingToken:token.trim()})});if(!response.ok)throw new Error(response.status===404?"Kode pelacakan tidak ditemukan.":response.status===429?"Terlalu banyak pemeriksaan. Coba kembali setelah 15 menit.":"Status belum dapat dibaca. Coba kembali.");const result=z.object({tracking:z.object({status:z.string(),latestUpdate:z.string()})}).parse(await response.json());setTracking(`${trackingLabels[result.tracking.status]||result.tracking.status}: ${result.tracking.latestUpdate}`);}catch(e){setError(e instanceof Error?e.message:"Gagal membaca status.");}finally{setBusy(false);}}
 return <div>{sent?<section className="submission-result"><h3>Laporan telah diterima</h3><p>Simpan kode ini di tempat pribadi untuk memeriksa tindak lanjut. Jangan bagikan kode kepada pihak lain. Laporan yang diterima akan diperiksa; penerimaan bukan penetapan kebenaran peristiwa.</p><p className="tracking-token" style={{overflowWrap:"anywhere"}}>{token}</p></section>:<form className="public-form" onSubmit={submit}><input className="sr-only" name="website" type="text" tabIndex={-1} autoComplete="off" aria-hidden="true"/>{!complaint?<label>Jenis aspirasi<select name="kind" value={kind} onChange={e=>setKind(e.target.value)} disabled={busy}><option value="SARAN">Saran</option><option value="PERTANYAAN">Pertanyaan</option></select></label>:null}<label>Subjek<input name="subject" required minLength={3} maxLength={180} disabled={busy}/></label><label>Uraian<textarea name="description" required minLength={20} maxLength={6000} rows={6} disabled={busy}/></label>{template?<fieldset><legend>{template.title}</legend><p>{template.instructions}</p>{template.fields.map(field=><label key={field.key}>{field.label}{field.required?"":" (opsional)"}<textarea name={`answer_${field.key}`} required={field.required} maxLength={300} rows={2} disabled={busy}/></label>)}</fieldset>:null}{templateLoading?<p role="status">Memuat formulir…</p>:null}{templateError?<p role="alert">{templateError}</p>:null}<label>Email kontak (opsional)<input name="contact" type="email" autoComplete="email" maxLength={254} disabled={busy}/></label><label className="check-field"><input name="consent" type="checkbox" required disabled={busy}/> Saya memahami informasi ini disimpan untuk pemeriksaan dan tindak lanjut oleh personel KPI yang berwenang.</label><button type="submit" className="button button--primary" disabled={busy||templateLoading||!!templateError}>{busy?"Mengirim…":complaint?"Kirim pengaduan":"Kirim aspirasi"}</button></form>}
  <section className="public-form"><h3>Periksa tindak lanjut</h3><label>Kode pelacakan<input value={token} onChange={e=>setToken(e.target.value)} autoComplete="off" spellCheck={false} disabled={busy}/></label><button type="button" className="button button--quiet" disabled={busy||!/^[a-f0-9]{64}$/.test(token.trim())} onClick={()=>void track()}>Periksa status</button>{tracking?<p role="status">{tracking}</p>:null}</section>{error?<p role="alert">{error}</p>:null}
 </div>;
}
