import {z} from 'zod';
import {createHostedAuthClient,resolveHostedAccess} from '@/platform/identity/hosted-auth';
import {errorResponse} from '@/platform/http/response';
import {getRequestId} from '@/platform/http/request-id';
import {hostedTaskScopeSchema} from '@/platform/work/hosted-task-contract';
const input=z.object({note:z.string().trim().min(3).max(2000),code:z.string().regex(/^[A-Z][A-Z0-9_]{1,39}$/).optional(),name:z.string().min(3).max(180).optional(),divisionId:z.string().uuid().nullable().optional(),accountId:z.string().uuid().optional(),positionId:z.string().uuid().optional(),startsOn:z.string().date().optional(),endsOn:z.string().date().optional(),decisionReference:z.string().max(1000).optional(),expectedVersion:z.number().int().positive().optional(),id:z.string().uuid().optional(),permissions:z.array(z.string().regex(/^[A-Z][A-Z0-9_]{1,63}$/)).max(100).optional(),classifications:z.array(z.enum(['TERBUKA','INTERNAL','TERBATAS','RAHASIA'])).max(4).optional(),reference:z.string().min(3).max(1000).optional(),startsAt:z.string().datetime({offset:true}).optional(),expiresAt:z.string().datetime({offset:true}).optional(),secretaryAccountId:z.string().uuid().optional(),iodDivisionId:z.string().uuid().optional(),enabled:z.boolean().optional(),kind:z.enum(['SARAN','PERTANYAAN','PENGADUAN']).optional(),title:z.string().min(3).max(180).optional(),instructions:z.string().min(3).max(2000).optional(),fields:z.array(z.object({key:z.string().regex(/^[a-z][a-z0-9_]{1,30}$/),label:z.string().min(3).max(180),required:z.boolean()}).strict()).max(6).optional()}).strict();
const command=hostedTaskScopeSchema.extend({command:z.enum(['DIVISION','POSITION','ASSIGN','END_ASSIGNMENT','MANDATE_PROPOSE','MANDATE_APPROVE','MANDATE_REJECT','MANDATE_REVOKE','ROUTING','TEMPLATE_CREATE','TEMPLATE_APPROVE','TEMPLATE_WITHDRAW']),input}).strict();
async function handle(request:Request){const requestId=getRequestId(request.headers.get('x-request-id'));try{
 const post=request.method==='POST';if(post&&request.headers.get('origin')!==new URL(request.url).origin)return errorResponse('AUTHORIZATION_DENIED',requestId,403);const client=await createHostedAuthClient();if(!client)return errorResponse('CONFIGURATION_INVALID',requestId,503);const {data:auth,error:failure}=await client.auth.getUser();const identity=failure?null:await resolveHostedAccess(client,auth.user);if(!identity)return errorResponse('AUTHENTICATION_REQUIRED',requestId,401);if(!identity.systemAdmin)return errorResponse('AUTHORIZATION_DENIED',requestId,403);
 let rpc:string,args:Record<string,unknown>;if(post){if(Number(request.headers.get('content-length'))>16000)return errorResponse('WORK_INPUT_INVALID',requestId,413);const raw=await request.text();if(new TextEncoder().encode(raw).length>16000)return errorResponse('WORK_INPUT_INVALID',requestId,413);const p=command.parse(JSON.parse(raw));rpc=p.command==='ROUTING'||p.command.startsWith('TEMPLATE_')?'kpi_intake_configure':'kpi_roster_action';args={organization_code:p.organizationCode,period_code:p.periodCode,command:p.command,input:p.input};}
 else{const q=new URL(request.url).searchParams,p=hostedTaskScopeSchema.parse({organizationCode:q.get('organizationCode'),periodCode:q.get('periodCode'),divisionCode:null});rpc=q.get('mode')==='INTAKE'?'kpi_intake_configuration':'kpi_roster_directory';args={organization_code:p.organizationCode,period_code:p.periodCode};}
 const {data,error}=await client.rpc(rpc,args);if(error)return errorResponse(error.code==='42501'?'AUTHORIZATION_DENIED':error.code==='40001'||error.code==='23505'?'WORK_VERSION_CONFLICT':['22023','23502','23514'].includes(error.code)?'WORK_INPUT_INVALID':'CONFIGURATION_INVALID',requestId,error.code==='42501'?403:error.code==='40001'||error.code==='23505'?409:['22023','23502','23514'].includes(error.code)?400:503);
 return Response.json({data},{headers:{'Cache-Control':'private, no-store'}});
}catch(e){return errorResponse(e instanceof z.ZodError||e instanceof SyntaxError?'WORK_INPUT_INVALID':'CONFIGURATION_INVALID',requestId,e instanceof z.ZodError||e instanceof SyntaxError?400:503);}}
export const GET=handle;export const POST=handle;
