"use client";

import { useState } from "react";

export function AiWorkspace(): React.JSX.Element {
  const [question, setQuestion] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [approved, setApproved] = useState(false);
  return <><section className="ai-banner"><div><span className="eyebrow">Status provider</span><strong>Nonaktif · menunggu OD-08</strong></div><p>Data Restricted/Rahasia tidak dikirim. Panel ini hanya memperlihatkan kontrak UX dan guardrail.</p></section><section className="ai-layout"><article className="ai-panel"><p className="eyebrow">I01–I03 · Tanya jawab & sumber</p><h2>Tanya dokumen TEST</h2><textarea aria-label="Pertanyaan AI" onChange={(event) => setQuestion(event.target.value)} placeholder="Contoh: apa status paket handover TEST?" rows={4} value={question} /><button className="button button--primary" disabled={!question.trim()} onClick={() => setSubmitted(true)} type="button">Kirim ke preview</button>{submitted ? <div className="ai-answer"><strong>Jawaban preview belum tersedia.</strong><p>Provider/model belum disetujui. UI sengaja tidak mengarang jawaban ketika sumber tidak tersedia.</p><div className="citation-row"><span>Sumber TEST</span><span className="status-chip">Akses diperiksa saat dibuka</span></div></div> : null}</article><article className="ai-panel"><p className="eyebrow">I04–I06 · Registry & governance</p><h2>Registry model dan prompt</h2><div className="ai-registry-row"><span>Provider</span><strong>Belum dipilih</strong></div><div className="ai-registry-row"><span>Lokasi proses</span><strong>Belum ditetapkan</strong></div><div className="ai-registry-row"><span>Retensi</span><strong>Menunggu keputusan</strong></div><div className="ai-registry-row"><span>Prompt registry</span><strong>Draft TEST</strong></div></article></section><section className="ai-action-panel"><div><p className="eyebrow">I05 · Usulan tindakan</p><h2>Review sebelum menjalankan aksi.</h2><p>Target, payload, konsekuensi, expiry, dan izin diperiksa ulang saat eksekusi.</p></div><div className="ai-action-preview"><span>Target</span><strong>Task TEST · tidak dikirim</strong><span>Payload</span><strong>Draft usulan · berubah jika sumber berubah</strong><label className="check-field"><input checked={approved} onChange={(event) => setApproved(event.target.checked)} type="checkbox" /> Saya sudah meninjau payload TEST</label><button className="button button--primary" disabled={!approved} type="button">Konfirmasi preview</button></div></section><p className="task-footnote">AI produksi tetap nonaktif sampai provider, region, retensi, sumber berizin, dan kebijakan manusia disetujui.</p></>;
}
