"use client";

import { useState } from "react";

const items = [
  { id: "H-TEST-01", title: "Paket tugas berjalan", owner: "Koordinator TEST", status: "Menunggu review" },
  { id: "H-TEST-02", title: "Dokumen dan keputusan", owner: "Admin TEST", status: "Lengkap" },
  { id: "H-TEST-03", title: "Peralihan akses penerus", owner: "Ketua TEST", status: "Perlu klarifikasi" },
  { id: "H-TEST-04", title: "Panduan operasi & insiden", owner: "Tim teknis TEST", status: "Draft" }
];

export function HandoverWorkspace(): React.JSX.Element {
  const [selected, setSelected] = useState(items[0]);
  const [accepted, setAccepted] = useState(false);
  return <><section className="handover-summary"><div><span className="finance-summary__label">Item paket</span><strong>4</strong><small>TEST preview</small></div><div><span className="finance-summary__label">Lengkap</span><strong>1</strong><small>Perlu pemeriksaan</small></div><div><span className="finance-summary__label">Outstanding</span><strong>2</strong><small>Punya owner</small></div><div><span className="finance-summary__label">Restore drill</span><strong>Belum</strong><small>Menunggu layanan</small></div></section><section className="handover-layout"><div className="handover-list" aria-label="Daftar item handover">{items.map((item) => <button className={`handover-row ${selected.id === item.id ? "handover-row--selected" : ""}`} key={item.id} onClick={() => setSelected(item)} type="button"><span className="workspace-card__number">{item.id}</span><strong>{item.title}</strong><span>{item.owner}</span><span className="status-chip">{item.status}</span></button>)}</div><aside className="handover-detail"><p className="eyebrow">H02–H03 · Review penerimaan</p><h2>{selected.title}</h2><p>{selected.owner} · {selected.status}</p><div className="handover-checks"><span>✓ Sumber item dicatat</span><span>✓ Pemilik outstanding terlihat</span><span>○ Penerus mengonfirmasi</span><span>○ Akses lama dijadwalkan dicabut</span></div><label className="check-field"><input checked={accepted} onChange={(event) => setAccepted(event.target.checked)} type="checkbox" /> Saya menerima item TEST ini untuk pemeriksaan</label><button className="button button--primary" disabled={!accepted} type="button">Catat penerimaan TEST</button></aside></section><section className="operations-grid"><article className="operations-panel"><p className="eyebrow">A12–A14 · Konfigurasi & retensi</p><h2>Perubahan butuh jejak.</h2><div className="config-line"><span>Retensi dokumen</span><strong>Belum ditetapkan</strong></div><div className="config-line"><span>Audit hold</span><strong>TEST preview</strong></div><div className="config-line"><span>Konfigurasi environment</span><strong>Local TEST</strong></div></article><article className="operations-panel"><p className="eyebrow">A15–A16 · Backup & panduan</p><h2>Pemulihan harus terbukti.</h2><div className="config-line"><span>Backup terakhir</span><strong>Belum dikonfigurasi</strong></div><div className="config-line"><span>Restore drill</span><strong>Menunggu staging</strong></div><div className="config-line"><span>Runbook insiden</span><strong>Draft TEST</strong></div></article></section><p className="task-footnote">Data sintetis TEST · handover tidak mencabut akses nyata dan restore belum dijalankan.</p></>;
}
