"use client";
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {hostedTaskSchema,type HostedTask} from '@/platform/work/hosted-task-contract';
import {portalJson} from '@/components/portal/hosted-management-workspace';
export function HostedMeetingFollowups({id,version,editable,onChanged}:{id:string;version:number;editable:boolean;onChanged:()=>Promise<void>}){
 const [tasks,setTasks]=useState<HostedTask[]>([]),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[due,setDue]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const key=useRef<string|null>(null);
 useEffect(()=>{let current=true;setError('');setTasks([]);void portalJson(`/api/v1/work/meetings/${id}/followups`).then(r=>{if(current)setTasks(z.array(hostedTaskSchema).parse(r.tasks));}).catch(e=>{if(current)setError((e as Error).message);});return()=>{current=false;};},[id,version]);
 async function create(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');key.current??=crypto.randomUUID();try{await portalJson(`/api/v1/work/meetings/${id}/followups`,{expectedVersion:version,title,description,dueAt:due?new Date(due).toISOString():null,note,requestKey:key.current});key.current=null;setTitle('');setDescription('');setDue('');setNote('');await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div><h3>Tindak lanjut rapat</h3>{error&&<p role="alert">{error}</p>}{tasks.map(t=><p key={t.id}><a href={`/portal/tugas?task=${t.id}`}>{t.title}</a> · {t.status}</p>)}{!tasks.length&&<p>Belum ada tindak lanjut yang dapat Anda baca.</p>}{editable&&<details><summary>Buat tugas dari keputusan rapat</summary><form onSubmit={create}><p>Tugas dibuat untuk Anda dari notulen yang telah disetujui. Delegasikan melalui halaman tugas. Informasi terbatas/rahasia memerlukan izin objek tersendiri.</p><label>Judul<input required minLength={3} maxLength={180} disabled={busy} value={title} onChange={e=>{key.current=null;setTitle(e.target.value);}}/></label><label>Uraian<textarea maxLength={4000} disabled={busy} value={description} onChange={e=>{key.current=null;setDescription(e.target.value);}}/></label><label>Tenggat<input type="datetime-local" disabled={busy} value={due} onChange={e=>{key.current=null;setDue(e.target.value);}}/></label><label>Rujukan keputusan atau catatan<textarea required minLength={3} maxLength={2000} disabled={busy} value={note} onChange={e=>{key.current=null;setNote(e.target.value);}}/></label><button className="button button--primary" disabled={busy}>Simpan tugas tindak lanjut</button></form></details>}</div>;
}
