"use client";
import {HostedAttachments} from "@/components/documents/hosted-attachments";
import {HostedMeetingFollowups} from "./hosted-meeting-followups";

import { useCallback, useEffect, useRef, useState } from "react";
import { z } from "zod";
import { meetingSchema, type HostedMeeting } from "@/platform/work/hosted-meeting-contract";
import { hasHostedPermission, type HostedAccess } from "@/platform/authorization/hosted-access";
import type { HostedTaskScope } from "@/platform/work/hosted-task-contract";

async function api(url: string, body?: unknown): Promise<unknown> {
 const response = await fetch(url,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});
 if(!response.ok) throw new Error(response.status===409?"Rapat sudah berubah. Muat ulang sebelum melanjutkan.":response.status===403?"Anda tidak memiliki izin untuk tindakan ini.":response.status===400?"Periksa isian dan tahap rapat.":response.status===401?"Sesi berakhir. Masuk kembali.":"Layanan rapat belum dapat dihubungi.");
 return response.json();
}
const labels: Record<HostedMeeting["status"],string>={DRAFT:"Notulen draf",IN_REVIEW:"Menunggu review",REVISION:"Perlu revisi",FINAL:"Notulen final",ARCHIVED:"Diarsipkan"};
const date=(value:string)=>new Date(value).toLocaleString("id-ID",{timeZone:"Africa/Cairo",dateStyle:"medium",timeStyle:"short"});

export function HostedMeetingWorkspace({identity,scopes}:{identity:HostedAccess;scopes:HostedTaskScope[]}):React.JSX.Element {
 const [scopeIndex,setScopeIndex]=useState(0), scope=scopes[scopeIndex];
 const [meetings,setMeetings]=useState<HostedMeeting[]>([]),[selected,setSelected]=useState<HostedMeeting|null>(null);
 const [members,setMembers]=useState<{accountId:string;name:string}[]>([]),[participants,setParticipants]=useState<string[]>([]);
 const [title,setTitle]=useState(""),[agenda,setAgenda]=useState(""),[startsAt,setStartsAt]=useState(""),[summary,setSummary]=useState(""),[note,setNote]=useState("");
 const [motionText,setMotionText]=useState(""),[quorum,setQuorum]=useState(1),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const requestKey=useRef<string|null>(null),generation=useRef(0),detailGeneration=useRef(0);
 const permissionScope={...scope,divisionCode:scope.divisionCode||undefined};
 const manage=hasHostedPermission(identity,"MEETING_MANAGE",permissionScope);
 const reload=useCallback(async()=>{
  const current=++generation.current; setLoading(true);setError("");
  const params=new URLSearchParams({organizationCode:scope.organizationCode,periodCode:scope.periodCode});if(scope.divisionCode)params.set("divisionCode",scope.divisionCode);
  try {
   const result=z.object({meetings:z.array(meetingSchema)}).parse(await api(`/api/v1/work/meetings?${params}`));
   const memberResult=manage?z.object({members:z.array(z.object({accountId:z.string().uuid(),name:z.string()}))}).parse(await api(`/api/v1/work/meetings/participants?${params}`)):{members:[]};
   if(current===generation.current){setMeetings(result.meetings);setMembers(memberResult.members);}
  }catch(failure){if(current===generation.current){setMeetings([]);setMembers([]);setError(failure instanceof Error?failure.message:"Gagal membaca rapat.");}}
  finally{if(current===generation.current)setLoading(false);}
 },[scope.organizationCode,scope.periodCode,scope.divisionCode,manage]);
 useEffect(()=>{setSelected(null);setParticipants([]);requestKey.current=null;setNotice("");detailGeneration.current++;void reload();return()=>{generation.current++;detailGeneration.current++;};},[reload]);
 async function open(id:string){const current=++detailGeneration.current;setError("");try{const {meeting}=z.object({meeting:meetingSchema}).parse(await api(`/api/v1/work/meetings/${id}`));if(current===detailGeneration.current){setSelected(meeting);setSummary(meeting.minutesSummary);setNote("");}}catch(failure){if(current===detailGeneration.current)setError(failure instanceof Error?failure.message:"Gagal membuka rapat.");}}
 async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;setBusy(true);setError("");setNotice("");requestKey.current??=crypto.randomUUID();
  try{const {meeting}=z.object({meeting:meetingSchema}).parse(await api("/api/v1/work/meetings",{...scope,title,agenda,startsAt:new Date(startsAt).toISOString(),participantAccountIds:participants,idempotencyKey:requestKey.current}));requestKey.current=null;setTitle("");setAgenda("");setStartsAt("");setParticipants([]);await reload();await open(meeting.id);setNotice("Undangan rapat tersimpan di database KPI.");}
  catch(failure){setError(failure instanceof Error?failure.message:"Gagal menyimpan rapat.");}finally{setBusy(false);}}
 async function act(action:string,extra:object={}){if(!selected||busy)return;setBusy(true);setError("");setNotice("");try{const {meeting}=z.object({meeting:meetingSchema}).parse(await api(`/api/v1/work/meetings/${selected.id}`,{action,expectedVersion:selected.version,note,...extra}));await reload();await open(meeting.id);setNotice("Perubahan rapat tersimpan.");}catch(failure){setError(failure instanceof Error?failure.message:"Gagal memperbarui rapat.");}finally{setBusy(false);}}
 const selectedManage=Boolean(selected&&hasHostedPermission(identity,"MEETING_MANAGE",{...permissionScope,objectId:selected.id}));
 const editable=selected&&["DRAFT","REVISION"].includes(selected.status);
 const independent=selected&&identity.accountId!==selected.createdByAccountId&&identity.accountId!==selected.minutesAuthorId;
 return <div className="hosted-task-workspace">
 <section className="portal-form-card"><label>Periode dan divisi<select disabled={busy} value={scopeIndex} onChange={event=>setScopeIndex(Number(event.target.value))}>{scopes.map((s,i)=><option key={JSON.stringify(s)} value={i}>{s.organizationCode} · {s.periodCode}{s.divisionCode?` · ${s.divisionCode}`:""}</option>)}</select></label><p>Jadwal ditampilkan dalam waktu Kairo. Input waktu mengikuti zona waktu perangkat Anda.</p></section>
 {error?<section className="operations-panel" role="alert"><p>{error}</p><button className="button button--quiet" disabled={busy} onClick={()=>void reload()}>Muat ulang</button></section>:null}{notice?<p role="status">{notice}</p>:null}
 {manage?<form className="portal-form-card" onSubmit={create}><h2>Buat undangan rapat</h2><label>Judul<input required minLength={3} maxLength={180} value={title} disabled={busy} onChange={event=>{setTitle(event.target.value);requestKey.current=null;}}/></label><label>Agenda<textarea required minLength={3} maxLength={6000} rows={4} value={agenda} disabled={busy} onChange={event=>{setAgenda(event.target.value);requestKey.current=null;}}/></label><label>Waktu mulai<input required type="datetime-local" value={startsAt} disabled={busy} onChange={event=>{setStartsAt(event.target.value);requestKey.current=null;}}/></label><fieldset disabled={busy}><legend>Peserta resmi</legend>{members.length?members.map(member=><label key={member.accountId}><input type="checkbox" checked={participants.includes(member.accountId)} onChange={event=>{setParticipants(values=>event.target.checked?[...values,member.accountId]:values.filter(id=>id!==member.accountId));requestKey.current=null;}}/>{member.name}</label>):<p>Belum ada pengurus aktif dalam periode/divisi ini. Lengkapi penugasan resmi terlebih dahulu.</p>}</fieldset><button className="button button--primary" disabled={busy||!participants.length}>{busy?"Menyimpan…":"Simpan undangan"}</button></form>:null}
 <section className="portal-form-card"><h2>Rapat organisasi</h2>{loading?<p role="status">Membaca rapat…</p>:meetings.length?<ul className="hosted-task-list">{meetings.map(meeting=><li key={meeting.id}><button className="hosted-task-list__row" type="button" disabled={busy} aria-pressed={selected?.id===meeting.id} onClick={()=>void open(meeting.id)}><span><strong>{meeting.title}</strong><small>{date(meeting.startsAt)} · Kairo</small></span><span>{labels[meeting.status]}</span></button></li>)}</ul>:<p>Belum ada rapat dalam periode ini.</p>}<p>Menampilkan 100 rapat terbaru berdasarkan jadwal.</p></section>
 {selected?<section className="portal-form-card"><h2>{selected.title}</h2><p>{labels[selected.status]} · Versi {selected.version} · {date(selected.startsAt)}</p><p className="hosted-meeting-text">{selected.agenda}</p><h3>Peserta dan kehadiran</h3><ul>{selected.participants.map(p=><li key={p.accountId}><strong>{p.name}</strong><p>Konfirmasi: {p.response||"Belum menjawab"} · Kehadiran: {p.attendance||"Belum dicatat"}</p>{selectedManage&&editable?<div className="portal-form-actions">{["HADIR","IZIN","TIDAK_HADIR"].map(attendance=><button key={attendance} className="button button--quiet" disabled={busy||note.trim().length<3} onClick={()=>void act("ATTENDANCE",{accountId:p.accountId,attendance})}>{attendance.replaceAll("_"," ")}</button>)}</div>:null}</li>)}</ul>
 {selected.status!=="ARCHIVED"?<label>Catatan tindakan<textarea maxLength={2000} rows={2} value={note} onChange={e=>setNote(e.target.value)} disabled={busy}/></label>:null}
 {selected.participants.some(p=>p.accountId===identity.accountId)&&Date.parse(selected.startsAt)>Date.now()&&selected.status!=="ARCHIVED"?<div className="portal-form-actions">{["HADIR","TIDAK_HADIR","RAGU"].map(response=><button key={response} className="button button--quiet" disabled={busy||note.trim().length<3} onClick={()=>void act("RSVP",{response})}>Konfirmasi {response.replaceAll("_"," ").toLowerCase()}</button>)}</div>:null}
 <h3>Notulen</h3>{selectedManage&&editable?<><label>Isi notulen<textarea minLength={3} maxLength={16000} rows={8} disabled={busy} value={summary} onChange={e=>setSummary(e.target.value)}/></label><div className="portal-form-actions"><button className="button button--quiet" disabled={busy||summary.trim().length<3||note.trim().length<3} onClick={()=>void act("SAVE_MINUTES",{summary})}>Simpan notulen</button><button className="button button--primary" disabled={busy||note.trim().length<3||!selected.minutesSummary||summary!==selected.minutesSummary} onClick={()=>void act("SUBMIT_MINUTES")}>Ajukan review</button></div></>:<p className="hosted-meeting-text">{selected.minutesSummary||"Notulen belum ditulis."}</p>}
 {selectedManage&&independent&&selected.status==="IN_REVIEW"?<div className="portal-form-actions"><button className="button button--primary" disabled={busy||note.trim().length<3} onClick={()=>void act("APPROVE_MINUTES")}>Setujui notulen</button><button className="button button--quiet" disabled={busy||note.trim().length<3} onClick={()=>void act("REQUEST_REVISION")}>Minta revisi</button></div>:null}
 {selectedManage&&selected.status==="FINAL"?<button className="button button--quiet" disabled={busy||note.trim().length<3} onClick={()=>void act("ARCHIVE")}>Arsipkan rapat</button>:null}
 <h3>Mosi dan voting</h3>{selectedManage&&editable&&!selected.motions.some(m=>!m.closedAt)?<><label>Usulan mosi<textarea value={motionText} maxLength={2000} onChange={e=>setMotionText(e.target.value)} disabled={busy}/></label><label>Kuorum sesuai ketentuan rapat<input type="number" min={1} max={100} value={quorum} onChange={e=>setQuorum(Number(e.target.value))} disabled={busy}/></label><button className="button button--quiet" disabled={busy||note.trim().length<3||motionText.trim().length<3} onClick={()=>void act("OPEN_MOTION",{text:motionText,quorum})}>Buka voting</button></>:null}
 {selected.motions.map(m=><article key={m.id}><h4>{m.text}</h4><p>{m.votesCast} suara dari {m.eligibleCount} peserta berhak · Kuorum {m.quorum} · {m.closedAt?"Ditutup":"Terbuka"}</p>{m.tally?<p>Setuju {m.tally.SETUJU} · Tolak {m.tally.TOLAK} · Abstain {m.tally.ABSTAIN}. Hasil keputusan dicatat pada notulen sesuai ketentuan KPI.</p>:<div className="portal-form-actions">{["SETUJU","TOLAK","ABSTAIN"].map(choice=><button className="button button--quiet" key={choice} disabled={busy||note.trim().length<3} onClick={()=>void act("VOTE",{motionId:m.id,choice})}>{choice}</button>)}{selectedManage?<button className="button button--quiet" disabled={busy||note.trim().length<3} onClick={()=>void act("CLOSE_MOTION",{motionId:m.id})}>Tutup voting</button>:null}</div>}</article>)}
 <HostedAttachments module="MEETING" entityId={selected.id} version={selected.version} scope={scope} editable={!!(selectedManage&&editable)} onChanged={async()=>{await reload();await open(selected.id);}}/><HostedMeetingFollowups id={selected.id} version={selected.version} editable={!!(selectedManage&&selected.status==="FINAL"&&hasHostedPermission(identity,"TASK_CREATE",permissionScope))} onChanged={async()=>{await reload();await open(selected.id);}}/><h3>Riwayat rapat</h3><ol>{selected.events.map(event=><li key={event.version}><strong>{event.action} · {event.actorName}</strong><p>{event.note}</p><small>{date(event.createdAt)}</small></li>)}</ol></section>:null}
 </div>;
}
