"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {z} from "zod";
import {hostedAssetSchema,type HostedAsset} from "@/platform/storage/hosted-asset-contract";
import {hasHostedPermission,type HostedAccess} from "@/platform/authorization/hosted-access";
import type {HostedTaskScope} from "@/platform/work/hosted-task-contract";
const labels:Record<HostedAsset["status"],string>={UPLOADING:"Upload belum selesai",PENDING_SCAN:"Menunggu pemeriksaan",AVAILABLE:"Tersedia",REJECTED:"Ditolak pemindai"};
export function HostedDocumentWorkspace({identity,scopes}:{identity:HostedAccess;scopes:HostedTaskScope[]}):React.JSX.Element{
 const [scopeIndex,setScopeIndex]=useState(0),scope=scopes[scopeIndex];const [assets,setAssets]=useState<HostedAsset[]>([]),[scanner,setScanner]=useState(false),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [registeredId,setRegisteredId]=useState("");
 const [versions,setVersions]=useState<HostedAsset[]>([]);
 const [previousAssetId,setPreviousAssetId]=useState("");
 const key=useRef<string|null>(null),generation=useRef(0),inputRef=useRef<HTMLInputElement>(null);
 const reload=useCallback(async()=>{const current=++generation.current;setLoading(true);setError("");const params=new URLSearchParams({organizationCode:scope.organizationCode,periodCode:scope.periodCode});if(scope.divisionCode)params.set("divisionCode",scope.divisionCode);try{const r=await fetch(`/api/v1/work/assets?${params}`,{cache:"no-store"});if(!r.ok)throw new Error("Daftar dokumen belum dapat dibaca. Periksa sesi dan izin Anda.");const result=z.object({assets:z.array(hostedAssetSchema),scannerConfigured:z.boolean()}).parse(await r.json());if(current===generation.current){setAssets(result.assets);setScanner(result.scannerConfigured);}}catch(e){if(current===generation.current){setAssets([]);setError(e instanceof Error?e.message:"Gagal membaca dokumen.");}}finally{if(current===generation.current)setLoading(false);}},[scope.organizationCode,scope.periodCode,scope.divisionCode]);
 useEffect(()=>{setFile(null);setRegisteredId("");setVersions([]);setPreviousAssetId("");key.current=null;if(inputRef.current)inputRef.current.value="";void reload();return()=>{generation.current++;};},[reload]);
 async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!file||busy)return;setBusy(true);setError("");setNotice("");try{key.current??=crypto.randomUUID();const body=new FormData();body.set("file",file);body.set("organizationCode",scope.organizationCode);body.set("periodCode",scope.periodCode);if(scope.divisionCode)body.set("divisionCode",scope.divisionCode);body.set("idempotencyKey",key.current);if(previousAssetId)body.set("previousAssetId",previousAssetId);const r=await fetch("/api/v1/work/assets",{method:"POST",body});if(!r.ok)throw new Error(r.status===413?"Ukuran berkas maksimal 4 MB.":r.status===400?"Jenis atau isi berkas tidak sesuai. Pilih PDF, PNG, JPEG, TXT, DOCX, XLSX atau PPTX yang valid.":r.status===409?"Data upload berubah. Pilih kembali berkas dan coba ulang.":r.status===403?"Anda tidak memiliki izin upload dalam periode ini.":"Upload belum selesai. Coba ulang dengan berkas yang sama.");const {asset}=z.object({asset:hostedAssetSchema}).parse(await r.json());key.current=null;setRegisteredId(asset.id);setFile(null);if(inputRef.current)inputRef.current.value="";await reload();setNotice(asset.status==="AVAILABLE"?"Berkas tersimpan dan lolos pemeriksaan.":asset.status==="REJECTED"?"Berkas ditolak oleh pemindai dan tidak tersedia untuk download.":"Berkas tersimpan secara private dan menunggu pemeriksaan.");}catch(e){setError(e instanceof Error?e.message:"Gagal upload.");}finally{setBusy(false);}}
 async function download(id:string){if(busy)return;setBusy(true);setError("");try{const r=await fetch(`/api/v1/work/assets/${id}/download`,{cache:"no-store"});if(!r.ok)throw new Error(r.status===409?"Berkas belum lolos pemeriksaan.":"Download tidak diizinkan atau layanan belum tersedia.");const blob=await r.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=assets.find(a=>a.id===id)?.name||"document";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:"Gagal download.");}finally{setBusy(false);}}
 async function history(id:string){if(busy)return;setBusy(true);setError("");try{const r=await fetch(`/api/v1/work/assets/${id}/versions`,{cache:"no-store"});if(!r.ok)throw new Error("Riwayat versi tidak dapat dibaca.");setVersions(z.object({versions:z.array(hostedAssetSchema)}).parse(await r.json()).versions);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function rescan(id:string){if(busy)return;setBusy(true);setError("");try{const r=await fetch(`/api/v1/work/assets/${id}/rescan`,{method:"POST"});if(!r.ok)throw new Error("Pemeriksaan belum tersedia. Periksa izin dan persetujuan pemindai.");await reload();setNotice("Hasil pemeriksaan berkas diperbarui.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const canUpload=hasHostedPermission(identity,"ASSET_UPLOAD",{...scope,divisionCode:scope.divisionCode||undefined});
 return <div className="hosted-task-workspace"><section className="portal-form-card"><label>Periode dan divisi<select value={scopeIndex} disabled={busy} onChange={e=>setScopeIndex(Number(e.target.value))}>{scopes.map((s,i)=><option key={JSON.stringify(s)} value={i}>{s.organizationCode} · {s.periodCode}{s.divisionCode?` · ${s.divisionCode}`:""}</option>)}</select></label></section>{error?<p role="alert">{error}</p>:null}{notice?<p role="status">{notice}</p>:null}{registeredId?<section className="portal-form-card"><h2>Akses berkas yang baru diunggah</h2><p>Berkas tersimpan. ID dokumen: <code>{registeredId}</code>. Ajukan klasifikasi dan izin penerima sebelum membagikan isinya.</p><a href={`/portal/kebijakan?resource=${registeredId}`}>Ajukan akses melalui F01/F02</a></section>:null}
 {!scanner&&!loading?<section className="operations-panel"><h2>Pemindai berkas belum dikonfigurasi</h2><p>Upload disimpan di bucket private. Download tetap terkunci sampai pemeriksaan berkas selesai.</p></section>:null}
 {canUpload?<form className="portal-form-card" onSubmit={upload}><h2>Upload dokumen</h2><label>Jenis upload<select disabled={busy} value={previousAssetId} onChange={e=>{key.current=null;setPreviousAssetId(e.target.value);}}><option value="">Dokumen baru</option>{assets.map(a=><option key={a.id} value={a.id}>Versi baru: {a.name} · v{a.revision||1}</option>)}</select></label><label>Berkas<input ref={inputRef} required type="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.docx,.xlsx,.pptx" disabled={busy} onChange={e=>{setFile(e.target.files?.[0]||null);key.current=null;}}/></label><p>PDF, PNG, JPEG, TXT, DOCX, XLSX atau PPTX. Maksimal 4 MB per berkas. Berkas baru diperlakukan sebagai rahasia sampai klasifikasi disahkan. Berkas tidak dipublikasikan dan unduhan memerlukan izin khusus pada objek dokumen.</p><button className="button button--primary" disabled={busy||!file}>{busy?"Mengunggah…":"Upload berkas"}</button></form>:null}
 {versions.length?<section className="portal-form-card"><h2>Riwayat versi yang dapat Anda akses</h2><ol>{versions.map(v=><li key={v.id}>{v.name} · v{v.revision||1} · {labels[v.status]}</li>)}</ol><button type="button" onClick={()=>setVersions([])}>Tutup riwayat</button></section>:null}
 <section className="portal-form-card"><h2>Dokumen tersimpan</h2>{loading?<p role="status">Membaca dokumen…</p>:assets.length?<ul className="hosted-task-list">{assets.map(a=><li key={a.id}><div className="hosted-task-list__row"><span><strong>{a.name}</strong><small>{Math.ceil(a.sizeBytes/1000)} KB · Versi {a.revision||1} · {labels[a.status]}</small></span><button type="button" disabled={busy} onClick={()=>void history(a.id)}>Riwayat versi</button><a href={`/portal/kebijakan?resource=${a.id}`}>Atur penerima melalui F01/F02</a>{a.status==="PENDING_SCAN"&&scanner&&hasHostedPermission(identity,"ASSET_UPLOAD",{...scope,divisionCode:scope.divisionCode||undefined,objectId:a.id})?<button type="button" disabled={busy} onClick={()=>void rescan(a.id)}>Periksa ulang</button>:null}<button type="button" className="button button--quiet" disabled={busy||a.status!=="AVAILABLE"||!hasHostedPermission(identity,"ASSET_DOWNLOAD",{...scope,divisionCode:scope.divisionCode||undefined,objectId:a.id})} onClick={()=>void download(a.id)}>Download</button></div></li>)}</ul>:<p>Belum ada dokumen dalam periode ini.</p>}<button type="button" className="button button--quiet" disabled={busy||loading} onClick={()=>void reload()}>Muat ulang</button></section></div>;
}
