"use client";
import {useEffect,useRef,useState} from 'react';
import {z} from 'zod';
import {hostedAssetSchema} from '@/platform/storage/hosted-asset-contract';
import type {HostedTaskScope} from '@/platform/work/hosted-task-contract';
import {portalJson,scopeQuery} from '@/components/portal/hosted-management-workspace';
const list=z.array(z.object({id:z.string().uuid(),assetId:z.string().uuid(),name:z.string(),mimeType:z.string(),createdAt:z.string()}));
export function HostedAttachments({module,entityId,version,scope,editable,onChanged}:{module:'MEETING'|'CONTENT'|'CASE';entityId:string;version:number;scope:HostedTaskScope;editable:boolean;onChanged:()=>Promise<void>}){
 const [attachments,setAttachments]=useState<z.infer<typeof list>>([]),[assets,setAssets]=useState<z.infer<typeof hostedAssetSchema>[]>([]),[assetId,setAssetId]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const generation=useRef(0);
 useEffect(()=>{const current=++generation.current;setAttachments([]);setAssets([]);setAssetId('');setNote('');setError('');void portalJson(`/api/v1/work/attachments?module=${module}&entityId=${entityId}`).then(r=>{if(current===generation.current)setAttachments(list.parse(r.attachments));}).catch(e=>{if(current===generation.current)setError((e as Error).message);});if(editable)void portalJson('/api/v1/work/assets?'+scopeQuery(scope)).then(r=>{if(current===generation.current)setAssets(z.array(hostedAssetSchema).parse(r.assets).filter(a=>a.status==='AVAILABLE'));}).catch(()=>{});return()=>{generation.current++;};},[module,entityId,version,editable,scope.organizationCode,scope.periodCode,scope.divisionCode]);
 async function act(command:'ATTACH'|'REMOVE',id:string){if(busy)return;setBusy(true);setError('');try{await portalJson('/api/v1/work/attachments',{module,entityId,expectedVersion:version,command,assetId:id,note});await onChanged();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function download(id:string,name:string){setBusy(true);setError('');try{const r=await fetch(`/api/v1/work/assets/${id}/download`,{cache:'no-store'});if(!r.ok)throw new Error('Download denied');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError('Unduhan membutuhkan izin download tersendiri dan berkas yang lolos pemeriksaan.');}finally{setBusy(false);}}
 return <div className="hosted-attachments"><h3>{module==='CASE'?'Bukti kasus':'Lampiran'}</h3>{error&&<p role="alert">{error}</p>}{attachments.length?<ul>{attachments.map(a=><li key={a.id}><span>{a.name}</span><div className="portal-form-actions"><button type="button" className="button button--quiet" disabled={busy} onClick={()=>void download(a.assetId,a.name)}>Unduh</button>{editable&&<button type="button" disabled={busy||note.trim().length<3} onClick={()=>void act('REMOVE',a.assetId)}>Lepas lampiran</button>}</div></li>)}</ul>:<p>Belum ada lampiran yang dapat Anda akses.</p>}{editable&&<details><summary>Kelola lampiran</summary><p>Berkas harus lolos pemindai, mempunyai izin baca, dan klasifikasinya sesuai dengan informasi tujuan. Upload di <a href="/portal/dokumen">Dokumen</a>, lalu ajukan izin objek lewat <a href="/portal/kebijakan">Kerahasiaan & akses</a> bila diperlukan.</p><label>Berkas tersedia<select value={assetId} disabled={busy} onChange={e=>setAssetId(e.target.value)}><option value="">Pilih berkas</option>{assets.filter(a=>!attachments.some(x=>x.assetId===a.id)).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Catatan perubahan<textarea maxLength={2000} rows={2} value={note} disabled={busy} onChange={e=>setNote(e.target.value)}/></label><button type="button" disabled={busy||!assetId||note.trim().length<3} onClick={()=>void act('ATTACH',assetId)}>Lampirkan berkas</button></details>}</div>;
}
